/*
PPG: Proxy Payment Gateway

Testing RefundAPIAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package ppg

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/mostafnamazy/jibit-ppg"
)

func Test_ppg_RefundAPIAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test RefundAPIAPIService CancelRefund", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var refundId int64

		httpRes, err := apiClient.RefundAPIAPI.CancelRefund(context.Background(), refundId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RefundAPIAPIService IgnoreCancellingRefund", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var refundId int64

		httpRes, err := apiClient.RefundAPIAPI.IgnoreCancellingRefund(context.Background(), refundId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RefundAPIAPIService InquiryRefund", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var refundId int64

		resp, httpRes, err := apiClient.RefundAPIAPI.InquiryRefund(context.Background(), refundId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RefundAPIAPIService RefundPurchase", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.RefundAPIAPI.RefundPurchase(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RefundAPIAPIService RetryRefund", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var refundId int64

		httpRes, err := apiClient.RefundAPIAPI.RetryRefund(context.Background(), refundId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RefundAPIAPIService VerifyRefund", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var refundId int64

		httpRes, err := apiClient.RefundAPIAPI.VerifyRefund(context.Background(), refundId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
