/*
PPG: Proxy Payment Gateway

Testing PurchaseAPIAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package jibit-ppg

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/mostafnamazy/jibit-ppg"
)

func Test_jibit-ppg_PurchaseAPIAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test PurchaseAPIAPIService CreatePurchase", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PurchaseAPIAPI.CreatePurchase(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PurchaseAPIAPIService FilterPurchaseHistories", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PurchaseAPIAPI.FilterPurchaseHistories(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PurchaseAPIAPIService FilterPurchases", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PurchaseAPIAPI.FilterPurchases(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PurchaseAPIAPIService ReversePurchase", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PurchaseAPIAPI.ReversePurchase(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PurchaseAPIAPIService VerifyPurchase", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var purchaseId int64

		resp, httpRes, err := apiClient.PurchaseAPIAPI.VerifyPurchase(context.Background(), purchaseId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
