/*
PPG: Proxy Payment Gateway

Testing SettlementAPIAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package jibit-ppg

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/mostafnamazy/jibit-ppg"
)

func Test_jibit-ppg_SettlementAPIAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SettlementAPIAPIService FilterSettlements", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.SettlementAPIAPI.FilterSettlements(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
