/*
PPG: Proxy Payment Gateway

PPG is the Proxy Payment Gateway of Jibit corporation. It lets the users of 3rd-party clients (merchants, banks, organizations, ...) to purchase goodies from them using PPG as a transparent payment gateway. In back-end the user will be redirected to a PSP payment gateway (for example Saman) to pay the price of the purchase.  Using APIs of this application a client can create and initiate the purchase orders and can track the state of these purchases.  Using *Swagger Editor* you could directly call the PPG APIs and also could auto-generate a client for PPG APIs in your preferred programming language.  The base URL of PPG is: `https://napi.jibit.ir/ppg`  Full documentation is available on: https://napi.jibit.ir/ppg/v3/static/docs/index.html

API version: 3.2.48
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ppg

import (
	"encoding/json"
)

// checks if the ClientBalances type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClientBalances{}

// ClientBalances Encapsulates the details of ledger inquiry response.
type ClientBalances struct {
	// Represents the list of ledger account balances which may contain the default wallet and pre-paid/post-paid fees and settleable wallet.
	Balances []Balance `json:"balances,omitempty"`
}

// NewClientBalances instantiates a new ClientBalances object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClientBalances() *ClientBalances {
	this := ClientBalances{}
	return &this
}

// NewClientBalancesWithDefaults instantiates a new ClientBalances object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClientBalancesWithDefaults() *ClientBalances {
	this := ClientBalances{}
	return &this
}

// GetBalances returns the Balances field value if set, zero value otherwise.
func (o *ClientBalances) GetBalances() []Balance {
	if o == nil || IsNil(o.Balances) {
		var ret []Balance
		return ret
	}
	return o.Balances
}

// GetBalancesOk returns a tuple with the Balances field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientBalances) GetBalancesOk() ([]Balance, bool) {
	if o == nil || IsNil(o.Balances) {
		return nil, false
	}
	return o.Balances, true
}

// HasBalances returns a boolean if a field has been set.
func (o *ClientBalances) HasBalances() bool {
	if o != nil && !IsNil(o.Balances) {
		return true
	}

	return false
}

// SetBalances gets a reference to the given []Balance and assigns it to the Balances field.
func (o *ClientBalances) SetBalances(v []Balance) {
	o.Balances = v
}

func (o ClientBalances) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClientBalances) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Balances) {
		toSerialize["balances"] = o.Balances
	}
	return toSerialize, nil
}

type NullableClientBalances struct {
	value *ClientBalances
	isSet bool
}

func (v NullableClientBalances) Get() *ClientBalances {
	return v.value
}

func (v *NullableClientBalances) Set(val *ClientBalances) {
	v.value = val
	v.isSet = true
}

func (v NullableClientBalances) IsSet() bool {
	return v.isSet
}

func (v *NullableClientBalances) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClientBalances(val *ClientBalances) *NullableClientBalances {
	return &NullableClientBalances{value: val, isSet: true}
}

func (v NullableClientBalances) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClientBalances) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


