/*
PPG: Proxy Payment Gateway

PPG is the Proxy Payment Gateway of Jibit corporation. It lets the users of 3rd-party clients (merchants, banks, organizations, ...) to purchase goodies from them using PPG as a transparent payment gateway. In back-end the user will be redirected to a PSP payment gateway (for example Saman) to pay the price of the purchase.  Using APIs of this application a client can create and initiate the purchase orders and can track the state of these purchases.  Using *Swagger Editor* you could directly call the PPG APIs and also could auto-generate a client for PPG APIs in your preferred programming language.  The base URL of PPG is: `https://napi.jibit.ir/ppg`  Full documentation is available on: https://napi.jibit.ir/ppg/v3/static/docs/index.html

API version: 3.2.48
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package jibit-ppg

import (
	"encoding/json"
	"time"
)

// checks if the Transfer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Transfer{}

// Transfer Encapsulates the details of transfers field.
type Transfer struct {
	// represents the purchase identifier of the refund.
	RefundId *int64 `json:"refundId,omitempty"`
	// Represents the position of a partial refund within a batch of refunds for a purchase. It is one-based, meaning it starts at 1.  ** DEPRECATED. Use `transferId` instead**
	// Deprecated
	PartialRefundIndex *int32 `json:"partialRefundIndex,omitempty"`
	TransferMode *string `json:"transferMode,omitempty"`
	Destination *string `json:"destination,omitempty"`
	DestinationFirstName *string `json:"destinationFirstName,omitempty"`
	DestinationLastName *string `json:"destinationLastName,omitempty"`
	Amount *int64 `json:"amount,omitempty"`
	Currency *string `json:"currency,omitempty"`
	Description *string `json:"description,omitempty"`
	Metadata *string `json:"metadata,omitempty"`
	Cancellable *bool `json:"cancellable,omitempty"`
	// State can have these following values:  TRANSFERRED means refund is completely done. FAILED means refund is failed. INITIALIZED and IN_PROGRESS mean refund is in progress. CANCELLING means it is in the middle of cancel process. CANCELLED means refund is cancelled.
	State *string `json:"state,omitempty"`
	FailReason *string `json:"failReason,omitempty"`
	FeeCurrency *string `json:"feeCurrency,omitempty"`
	FeeAmount *int64 `json:"feeAmount,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	ModifiedAt *time.Time `json:"modifiedAt,omitempty"`
	NotifyURL *string `json:"notifyURL,omitempty"`
	PaymentID *string `json:"paymentID,omitempty"`
	BankTransferID *string `json:"bankTransferID,omitempty"`
	TransferID *string `json:"transferID,omitempty"`
}

// NewTransfer instantiates a new Transfer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransfer() *Transfer {
	this := Transfer{}
	return &this
}

// NewTransferWithDefaults instantiates a new Transfer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransferWithDefaults() *Transfer {
	this := Transfer{}
	return &this
}

// GetRefundId returns the RefundId field value if set, zero value otherwise.
func (o *Transfer) GetRefundId() int64 {
	if o == nil || IsNil(o.RefundId) {
		var ret int64
		return ret
	}
	return *o.RefundId
}

// GetRefundIdOk returns a tuple with the RefundId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transfer) GetRefundIdOk() (*int64, bool) {
	if o == nil || IsNil(o.RefundId) {
		return nil, false
	}
	return o.RefundId, true
}

// HasRefundId returns a boolean if a field has been set.
func (o *Transfer) HasRefundId() bool {
	if o != nil && !IsNil(o.RefundId) {
		return true
	}

	return false
}

// SetRefundId gets a reference to the given int64 and assigns it to the RefundId field.
func (o *Transfer) SetRefundId(v int64) {
	o.RefundId = &v
}

// GetPartialRefundIndex returns the PartialRefundIndex field value if set, zero value otherwise.
// Deprecated
func (o *Transfer) GetPartialRefundIndex() int32 {
	if o == nil || IsNil(o.PartialRefundIndex) {
		var ret int32
		return ret
	}
	return *o.PartialRefundIndex
}

// GetPartialRefundIndexOk returns a tuple with the PartialRefundIndex field value if set, nil otherwise
// and a boolean to check if the value has been set.
// Deprecated
func (o *Transfer) GetPartialRefundIndexOk() (*int32, bool) {
	if o == nil || IsNil(o.PartialRefundIndex) {
		return nil, false
	}
	return o.PartialRefundIndex, true
}

// HasPartialRefundIndex returns a boolean if a field has been set.
func (o *Transfer) HasPartialRefundIndex() bool {
	if o != nil && !IsNil(o.PartialRefundIndex) {
		return true
	}

	return false
}

// SetPartialRefundIndex gets a reference to the given int32 and assigns it to the PartialRefundIndex field.
// Deprecated
func (o *Transfer) SetPartialRefundIndex(v int32) {
	o.PartialRefundIndex = &v
}

// GetTransferMode returns the TransferMode field value if set, zero value otherwise.
func (o *Transfer) GetTransferMode() string {
	if o == nil || IsNil(o.TransferMode) {
		var ret string
		return ret
	}
	return *o.TransferMode
}

// GetTransferModeOk returns a tuple with the TransferMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transfer) GetTransferModeOk() (*string, bool) {
	if o == nil || IsNil(o.TransferMode) {
		return nil, false
	}
	return o.TransferMode, true
}

// HasTransferMode returns a boolean if a field has been set.
func (o *Transfer) HasTransferMode() bool {
	if o != nil && !IsNil(o.TransferMode) {
		return true
	}

	return false
}

// SetTransferMode gets a reference to the given string and assigns it to the TransferMode field.
func (o *Transfer) SetTransferMode(v string) {
	o.TransferMode = &v
}

// GetDestination returns the Destination field value if set, zero value otherwise.
func (o *Transfer) GetDestination() string {
	if o == nil || IsNil(o.Destination) {
		var ret string
		return ret
	}
	return *o.Destination
}

// GetDestinationOk returns a tuple with the Destination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transfer) GetDestinationOk() (*string, bool) {
	if o == nil || IsNil(o.Destination) {
		return nil, false
	}
	return o.Destination, true
}

// HasDestination returns a boolean if a field has been set.
func (o *Transfer) HasDestination() bool {
	if o != nil && !IsNil(o.Destination) {
		return true
	}

	return false
}

// SetDestination gets a reference to the given string and assigns it to the Destination field.
func (o *Transfer) SetDestination(v string) {
	o.Destination = &v
}

// GetDestinationFirstName returns the DestinationFirstName field value if set, zero value otherwise.
func (o *Transfer) GetDestinationFirstName() string {
	if o == nil || IsNil(o.DestinationFirstName) {
		var ret string
		return ret
	}
	return *o.DestinationFirstName
}

// GetDestinationFirstNameOk returns a tuple with the DestinationFirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transfer) GetDestinationFirstNameOk() (*string, bool) {
	if o == nil || IsNil(o.DestinationFirstName) {
		return nil, false
	}
	return o.DestinationFirstName, true
}

// HasDestinationFirstName returns a boolean if a field has been set.
func (o *Transfer) HasDestinationFirstName() bool {
	if o != nil && !IsNil(o.DestinationFirstName) {
		return true
	}

	return false
}

// SetDestinationFirstName gets a reference to the given string and assigns it to the DestinationFirstName field.
func (o *Transfer) SetDestinationFirstName(v string) {
	o.DestinationFirstName = &v
}

// GetDestinationLastName returns the DestinationLastName field value if set, zero value otherwise.
func (o *Transfer) GetDestinationLastName() string {
	if o == nil || IsNil(o.DestinationLastName) {
		var ret string
		return ret
	}
	return *o.DestinationLastName
}

// GetDestinationLastNameOk returns a tuple with the DestinationLastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transfer) GetDestinationLastNameOk() (*string, bool) {
	if o == nil || IsNil(o.DestinationLastName) {
		return nil, false
	}
	return o.DestinationLastName, true
}

// HasDestinationLastName returns a boolean if a field has been set.
func (o *Transfer) HasDestinationLastName() bool {
	if o != nil && !IsNil(o.DestinationLastName) {
		return true
	}

	return false
}

// SetDestinationLastName gets a reference to the given string and assigns it to the DestinationLastName field.
func (o *Transfer) SetDestinationLastName(v string) {
	o.DestinationLastName = &v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *Transfer) GetAmount() int64 {
	if o == nil || IsNil(o.Amount) {
		var ret int64
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transfer) GetAmountOk() (*int64, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *Transfer) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given int64 and assigns it to the Amount field.
func (o *Transfer) SetAmount(v int64) {
	o.Amount = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *Transfer) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transfer) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *Transfer) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *Transfer) SetCurrency(v string) {
	o.Currency = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *Transfer) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transfer) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *Transfer) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *Transfer) SetDescription(v string) {
	o.Description = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *Transfer) GetMetadata() string {
	if o == nil || IsNil(o.Metadata) {
		var ret string
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transfer) GetMetadataOk() (*string, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *Transfer) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given string and assigns it to the Metadata field.
func (o *Transfer) SetMetadata(v string) {
	o.Metadata = &v
}

// GetCancellable returns the Cancellable field value if set, zero value otherwise.
func (o *Transfer) GetCancellable() bool {
	if o == nil || IsNil(o.Cancellable) {
		var ret bool
		return ret
	}
	return *o.Cancellable
}

// GetCancellableOk returns a tuple with the Cancellable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transfer) GetCancellableOk() (*bool, bool) {
	if o == nil || IsNil(o.Cancellable) {
		return nil, false
	}
	return o.Cancellable, true
}

// HasCancellable returns a boolean if a field has been set.
func (o *Transfer) HasCancellable() bool {
	if o != nil && !IsNil(o.Cancellable) {
		return true
	}

	return false
}

// SetCancellable gets a reference to the given bool and assigns it to the Cancellable field.
func (o *Transfer) SetCancellable(v bool) {
	o.Cancellable = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *Transfer) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transfer) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *Transfer) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *Transfer) SetState(v string) {
	o.State = &v
}

// GetFailReason returns the FailReason field value if set, zero value otherwise.
func (o *Transfer) GetFailReason() string {
	if o == nil || IsNil(o.FailReason) {
		var ret string
		return ret
	}
	return *o.FailReason
}

// GetFailReasonOk returns a tuple with the FailReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transfer) GetFailReasonOk() (*string, bool) {
	if o == nil || IsNil(o.FailReason) {
		return nil, false
	}
	return o.FailReason, true
}

// HasFailReason returns a boolean if a field has been set.
func (o *Transfer) HasFailReason() bool {
	if o != nil && !IsNil(o.FailReason) {
		return true
	}

	return false
}

// SetFailReason gets a reference to the given string and assigns it to the FailReason field.
func (o *Transfer) SetFailReason(v string) {
	o.FailReason = &v
}

// GetFeeCurrency returns the FeeCurrency field value if set, zero value otherwise.
func (o *Transfer) GetFeeCurrency() string {
	if o == nil || IsNil(o.FeeCurrency) {
		var ret string
		return ret
	}
	return *o.FeeCurrency
}

// GetFeeCurrencyOk returns a tuple with the FeeCurrency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transfer) GetFeeCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.FeeCurrency) {
		return nil, false
	}
	return o.FeeCurrency, true
}

// HasFeeCurrency returns a boolean if a field has been set.
func (o *Transfer) HasFeeCurrency() bool {
	if o != nil && !IsNil(o.FeeCurrency) {
		return true
	}

	return false
}

// SetFeeCurrency gets a reference to the given string and assigns it to the FeeCurrency field.
func (o *Transfer) SetFeeCurrency(v string) {
	o.FeeCurrency = &v
}

// GetFeeAmount returns the FeeAmount field value if set, zero value otherwise.
func (o *Transfer) GetFeeAmount() int64 {
	if o == nil || IsNil(o.FeeAmount) {
		var ret int64
		return ret
	}
	return *o.FeeAmount
}

// GetFeeAmountOk returns a tuple with the FeeAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transfer) GetFeeAmountOk() (*int64, bool) {
	if o == nil || IsNil(o.FeeAmount) {
		return nil, false
	}
	return o.FeeAmount, true
}

// HasFeeAmount returns a boolean if a field has been set.
func (o *Transfer) HasFeeAmount() bool {
	if o != nil && !IsNil(o.FeeAmount) {
		return true
	}

	return false
}

// SetFeeAmount gets a reference to the given int64 and assigns it to the FeeAmount field.
func (o *Transfer) SetFeeAmount(v int64) {
	o.FeeAmount = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Transfer) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transfer) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Transfer) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *Transfer) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetModifiedAt returns the ModifiedAt field value if set, zero value otherwise.
func (o *Transfer) GetModifiedAt() time.Time {
	if o == nil || IsNil(o.ModifiedAt) {
		var ret time.Time
		return ret
	}
	return *o.ModifiedAt
}

// GetModifiedAtOk returns a tuple with the ModifiedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transfer) GetModifiedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ModifiedAt) {
		return nil, false
	}
	return o.ModifiedAt, true
}

// HasModifiedAt returns a boolean if a field has been set.
func (o *Transfer) HasModifiedAt() bool {
	if o != nil && !IsNil(o.ModifiedAt) {
		return true
	}

	return false
}

// SetModifiedAt gets a reference to the given time.Time and assigns it to the ModifiedAt field.
func (o *Transfer) SetModifiedAt(v time.Time) {
	o.ModifiedAt = &v
}

// GetNotifyURL returns the NotifyURL field value if set, zero value otherwise.
func (o *Transfer) GetNotifyURL() string {
	if o == nil || IsNil(o.NotifyURL) {
		var ret string
		return ret
	}
	return *o.NotifyURL
}

// GetNotifyURLOk returns a tuple with the NotifyURL field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transfer) GetNotifyURLOk() (*string, bool) {
	if o == nil || IsNil(o.NotifyURL) {
		return nil, false
	}
	return o.NotifyURL, true
}

// HasNotifyURL returns a boolean if a field has been set.
func (o *Transfer) HasNotifyURL() bool {
	if o != nil && !IsNil(o.NotifyURL) {
		return true
	}

	return false
}

// SetNotifyURL gets a reference to the given string and assigns it to the NotifyURL field.
func (o *Transfer) SetNotifyURL(v string) {
	o.NotifyURL = &v
}

// GetPaymentID returns the PaymentID field value if set, zero value otherwise.
func (o *Transfer) GetPaymentID() string {
	if o == nil || IsNil(o.PaymentID) {
		var ret string
		return ret
	}
	return *o.PaymentID
}

// GetPaymentIDOk returns a tuple with the PaymentID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transfer) GetPaymentIDOk() (*string, bool) {
	if o == nil || IsNil(o.PaymentID) {
		return nil, false
	}
	return o.PaymentID, true
}

// HasPaymentID returns a boolean if a field has been set.
func (o *Transfer) HasPaymentID() bool {
	if o != nil && !IsNil(o.PaymentID) {
		return true
	}

	return false
}

// SetPaymentID gets a reference to the given string and assigns it to the PaymentID field.
func (o *Transfer) SetPaymentID(v string) {
	o.PaymentID = &v
}

// GetBankTransferID returns the BankTransferID field value if set, zero value otherwise.
func (o *Transfer) GetBankTransferID() string {
	if o == nil || IsNil(o.BankTransferID) {
		var ret string
		return ret
	}
	return *o.BankTransferID
}

// GetBankTransferIDOk returns a tuple with the BankTransferID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transfer) GetBankTransferIDOk() (*string, bool) {
	if o == nil || IsNil(o.BankTransferID) {
		return nil, false
	}
	return o.BankTransferID, true
}

// HasBankTransferID returns a boolean if a field has been set.
func (o *Transfer) HasBankTransferID() bool {
	if o != nil && !IsNil(o.BankTransferID) {
		return true
	}

	return false
}

// SetBankTransferID gets a reference to the given string and assigns it to the BankTransferID field.
func (o *Transfer) SetBankTransferID(v string) {
	o.BankTransferID = &v
}

// GetTransferID returns the TransferID field value if set, zero value otherwise.
func (o *Transfer) GetTransferID() string {
	if o == nil || IsNil(o.TransferID) {
		var ret string
		return ret
	}
	return *o.TransferID
}

// GetTransferIDOk returns a tuple with the TransferID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transfer) GetTransferIDOk() (*string, bool) {
	if o == nil || IsNil(o.TransferID) {
		return nil, false
	}
	return o.TransferID, true
}

// HasTransferID returns a boolean if a field has been set.
func (o *Transfer) HasTransferID() bool {
	if o != nil && !IsNil(o.TransferID) {
		return true
	}

	return false
}

// SetTransferID gets a reference to the given string and assigns it to the TransferID field.
func (o *Transfer) SetTransferID(v string) {
	o.TransferID = &v
}

func (o Transfer) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Transfer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RefundId) {
		toSerialize["refundId"] = o.RefundId
	}
	if !IsNil(o.PartialRefundIndex) {
		toSerialize["partialRefundIndex"] = o.PartialRefundIndex
	}
	if !IsNil(o.TransferMode) {
		toSerialize["transferMode"] = o.TransferMode
	}
	if !IsNil(o.Destination) {
		toSerialize["destination"] = o.Destination
	}
	if !IsNil(o.DestinationFirstName) {
		toSerialize["destinationFirstName"] = o.DestinationFirstName
	}
	if !IsNil(o.DestinationLastName) {
		toSerialize["destinationLastName"] = o.DestinationLastName
	}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.Cancellable) {
		toSerialize["cancellable"] = o.Cancellable
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.FailReason) {
		toSerialize["failReason"] = o.FailReason
	}
	if !IsNil(o.FeeCurrency) {
		toSerialize["feeCurrency"] = o.FeeCurrency
	}
	if !IsNil(o.FeeAmount) {
		toSerialize["feeAmount"] = o.FeeAmount
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.ModifiedAt) {
		toSerialize["modifiedAt"] = o.ModifiedAt
	}
	if !IsNil(o.NotifyURL) {
		toSerialize["notifyURL"] = o.NotifyURL
	}
	if !IsNil(o.PaymentID) {
		toSerialize["paymentID"] = o.PaymentID
	}
	if !IsNil(o.BankTransferID) {
		toSerialize["bankTransferID"] = o.BankTransferID
	}
	if !IsNil(o.TransferID) {
		toSerialize["transferID"] = o.TransferID
	}
	return toSerialize, nil
}

type NullableTransfer struct {
	value *Transfer
	isSet bool
}

func (v NullableTransfer) Get() *Transfer {
	return v.value
}

func (v *NullableTransfer) Set(val *Transfer) {
	v.value = val
	v.isSet = true
}

func (v NullableTransfer) IsSet() bool {
	return v.isSet
}

func (v *NullableTransfer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransfer(val *Transfer) *NullableTransfer {
	return &NullableTransfer{value: val, isSet: true}
}

func (v NullableTransfer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransfer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


