/*
PPG: Proxy Payment Gateway

PPG is the Proxy Payment Gateway of Jibit corporation. It lets the users of 3rd-party clients (merchants, banks, organizations, ...) to purchase goodies from them using PPG as a transparent payment gateway. In back-end the user will be redirected to a PSP payment gateway (for example Saman) to pay the price of the purchase.  Using APIs of this application a client can create and initiate the purchase orders and can track the state of these purchases.  Using *Swagger Editor* you could directly call the PPG APIs and also could auto-generate a client for PPG APIs in your preferred programming language.  The base URL of PPG is: `https://napi.jibit.ir/ppg`  Full documentation is available on: https://napi.jibit.ir/ppg/v3/static/docs/index.html

API version: 3.2.48
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ppg

import (
	"encoding/json"
)

// checks if the RefundPurchaseRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RefundPurchaseRequest{}

// RefundPurchaseRequest Encapsulates the information required to refund a purchase.
type RefundPurchaseRequest struct {
	// Represents the reference number provided by client to trace the purchase in our system.
	ClientReferenceNumber *string `json:"clientReferenceNumber,omitempty"`
	// Represents the purchase id.
	PurchaseId *int64 `json:"purchaseId,omitempty"`
	// Represents the refund amount.
	Amount *int64 `json:"amount,omitempty"`
	// Whether to pend the refund request and perform it after one hour.
	Cancellable *bool `json:"cancellable,omitempty"`
}

// NewRefundPurchaseRequest instantiates a new RefundPurchaseRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRefundPurchaseRequest() *RefundPurchaseRequest {
	this := RefundPurchaseRequest{}
	return &this
}

// NewRefundPurchaseRequestWithDefaults instantiates a new RefundPurchaseRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRefundPurchaseRequestWithDefaults() *RefundPurchaseRequest {
	this := RefundPurchaseRequest{}
	return &this
}

// GetClientReferenceNumber returns the ClientReferenceNumber field value if set, zero value otherwise.
func (o *RefundPurchaseRequest) GetClientReferenceNumber() string {
	if o == nil || IsNil(o.ClientReferenceNumber) {
		var ret string
		return ret
	}
	return *o.ClientReferenceNumber
}

// GetClientReferenceNumberOk returns a tuple with the ClientReferenceNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RefundPurchaseRequest) GetClientReferenceNumberOk() (*string, bool) {
	if o == nil || IsNil(o.ClientReferenceNumber) {
		return nil, false
	}
	return o.ClientReferenceNumber, true
}

// HasClientReferenceNumber returns a boolean if a field has been set.
func (o *RefundPurchaseRequest) HasClientReferenceNumber() bool {
	if o != nil && !IsNil(o.ClientReferenceNumber) {
		return true
	}

	return false
}

// SetClientReferenceNumber gets a reference to the given string and assigns it to the ClientReferenceNumber field.
func (o *RefundPurchaseRequest) SetClientReferenceNumber(v string) {
	o.ClientReferenceNumber = &v
}

// GetPurchaseId returns the PurchaseId field value if set, zero value otherwise.
func (o *RefundPurchaseRequest) GetPurchaseId() int64 {
	if o == nil || IsNil(o.PurchaseId) {
		var ret int64
		return ret
	}
	return *o.PurchaseId
}

// GetPurchaseIdOk returns a tuple with the PurchaseId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RefundPurchaseRequest) GetPurchaseIdOk() (*int64, bool) {
	if o == nil || IsNil(o.PurchaseId) {
		return nil, false
	}
	return o.PurchaseId, true
}

// HasPurchaseId returns a boolean if a field has been set.
func (o *RefundPurchaseRequest) HasPurchaseId() bool {
	if o != nil && !IsNil(o.PurchaseId) {
		return true
	}

	return false
}

// SetPurchaseId gets a reference to the given int64 and assigns it to the PurchaseId field.
func (o *RefundPurchaseRequest) SetPurchaseId(v int64) {
	o.PurchaseId = &v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *RefundPurchaseRequest) GetAmount() int64 {
	if o == nil || IsNil(o.Amount) {
		var ret int64
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RefundPurchaseRequest) GetAmountOk() (*int64, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *RefundPurchaseRequest) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given int64 and assigns it to the Amount field.
func (o *RefundPurchaseRequest) SetAmount(v int64) {
	o.Amount = &v
}

// GetCancellable returns the Cancellable field value if set, zero value otherwise.
func (o *RefundPurchaseRequest) GetCancellable() bool {
	if o == nil || IsNil(o.Cancellable) {
		var ret bool
		return ret
	}
	return *o.Cancellable
}

// GetCancellableOk returns a tuple with the Cancellable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RefundPurchaseRequest) GetCancellableOk() (*bool, bool) {
	if o == nil || IsNil(o.Cancellable) {
		return nil, false
	}
	return o.Cancellable, true
}

// HasCancellable returns a boolean if a field has been set.
func (o *RefundPurchaseRequest) HasCancellable() bool {
	if o != nil && !IsNil(o.Cancellable) {
		return true
	}

	return false
}

// SetCancellable gets a reference to the given bool and assigns it to the Cancellable field.
func (o *RefundPurchaseRequest) SetCancellable(v bool) {
	o.Cancellable = &v
}

func (o RefundPurchaseRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RefundPurchaseRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ClientReferenceNumber) {
		toSerialize["clientReferenceNumber"] = o.ClientReferenceNumber
	}
	if !IsNil(o.PurchaseId) {
		toSerialize["purchaseId"] = o.PurchaseId
	}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.Cancellable) {
		toSerialize["cancellable"] = o.Cancellable
	}
	return toSerialize, nil
}

type NullableRefundPurchaseRequest struct {
	value *RefundPurchaseRequest
	isSet bool
}

func (v NullableRefundPurchaseRequest) Get() *RefundPurchaseRequest {
	return v.value
}

func (v *NullableRefundPurchaseRequest) Set(val *RefundPurchaseRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRefundPurchaseRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRefundPurchaseRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRefundPurchaseRequest(val *RefundPurchaseRequest) *NullableRefundPurchaseRequest {
	return &NullableRefundPurchaseRequest{value: val, isSet: true}
}

func (v NullableRefundPurchaseRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRefundPurchaseRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


