/*
PPG: Proxy Payment Gateway

PPG is the Proxy Payment Gateway of Jibit corporation. It lets the users of 3rd-party clients (merchants, banks, organizations, ...) to purchase goodies from them using PPG as a transparent payment gateway. In back-end the user will be redirected to a PSP payment gateway (for example Saman) to pay the price of the purchase.  Using APIs of this application a client can create and initiate the purchase orders and can track the state of these purchases.  Using *Swagger Editor* you could directly call the PPG APIs and also could auto-generate a client for PPG APIs in your preferred programming language.  The base URL of PPG is: `https://napi.jibit.ir/ppg`  Full documentation is available on: https://napi.jibit.ir/ppg/v3/static/docs/index.html

API version: 3.2.48
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ppg

import (
	"encoding/json"
	"time"
)

// checks if the DetailedSettlementDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DetailedSettlementDto{}

// DetailedSettlementDto Encapsulates a detailed view of a settlement.
type DetailedSettlementDto struct {
	// Represents the settlement identifier.
	SettlementId *int64 `json:"settlementId,omitempty"`
	// Represents the terminal Id.
	TerminalId *string `json:"terminalId,omitempty"`
	// Represents the file name which was sent to shaparak.
	FileName *string `json:"fileName,omitempty"`
	// Represents the settlement state.
	State *string `json:"state,omitempty"`
	// Represents the settlement amount.
	Amount *int64 `json:"amount,omitempty"`
	// Represents the settlement wage.
	Wage *int64 `json:"wage,omitempty"`
	// Represents whether settlement is direct settled.
	DirectSettlement *bool `json:"directSettlement,omitempty"`
	// Represents the currency type.
	Currency *string `json:"currency,omitempty"`
	// Cutoff time.
	Cutoff *string `json:"cutoff,omitempty"`
	// Represents the acceptor code.
	AcceptorCode *string `json:"acceptorCode,omitempty"`
	// Represents ledger account of client.
	LedgerAccount *string `json:"ledgerAccount,omitempty"`
	// Represents the iin.
	Iin *int64 `json:"iin,omitempty"`
	// Represents the pf Iban.
	PaymentFacilitatorIban *string `json:"paymentFacilitatorIban,omitempty"`
	// Represents the settlement Iban.
	SettlementIban *string `json:"settlementIban,omitempty"`
	// Represents the reseller code
	ResellerCode *string `json:"resellerCode,omitempty"`
	// Represents the reseller's affiliate fee.
	AffiliateFee *int64 `json:"affiliateFee,omitempty"`
	// Represents the shaparak fail reason.
	ShaparakFailReason *string `json:"shaparakFailReason,omitempty"`
	// Represents the shaparak reference number.
	ShaparakReferenceNumber *string `json:"shaparakReferenceNumber,omitempty"`
	// Represents the shaparak tracking number.
	ShaparakTrackingNumber *string `json:"shaparakTrackingNumber,omitempty"`
	// Represents the shaparak tracking id.
	ShaparakTransactionId *string `json:"shaparakTransactionId,omitempty"`
	// When was the settlement created.
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// When was the settlement modified.
	ModifiedAt *time.Time `json:"modifiedAt,omitempty"`
	// When was the settlement settled.
	SettledAt *time.Time `json:"settledAt,omitempty"`
}

// NewDetailedSettlementDto instantiates a new DetailedSettlementDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDetailedSettlementDto() *DetailedSettlementDto {
	this := DetailedSettlementDto{}
	return &this
}

// NewDetailedSettlementDtoWithDefaults instantiates a new DetailedSettlementDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDetailedSettlementDtoWithDefaults() *DetailedSettlementDto {
	this := DetailedSettlementDto{}
	return &this
}

// GetSettlementId returns the SettlementId field value if set, zero value otherwise.
func (o *DetailedSettlementDto) GetSettlementId() int64 {
	if o == nil || IsNil(o.SettlementId) {
		var ret int64
		return ret
	}
	return *o.SettlementId
}

// GetSettlementIdOk returns a tuple with the SettlementId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedSettlementDto) GetSettlementIdOk() (*int64, bool) {
	if o == nil || IsNil(o.SettlementId) {
		return nil, false
	}
	return o.SettlementId, true
}

// HasSettlementId returns a boolean if a field has been set.
func (o *DetailedSettlementDto) HasSettlementId() bool {
	if o != nil && !IsNil(o.SettlementId) {
		return true
	}

	return false
}

// SetSettlementId gets a reference to the given int64 and assigns it to the SettlementId field.
func (o *DetailedSettlementDto) SetSettlementId(v int64) {
	o.SettlementId = &v
}

// GetTerminalId returns the TerminalId field value if set, zero value otherwise.
func (o *DetailedSettlementDto) GetTerminalId() string {
	if o == nil || IsNil(o.TerminalId) {
		var ret string
		return ret
	}
	return *o.TerminalId
}

// GetTerminalIdOk returns a tuple with the TerminalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedSettlementDto) GetTerminalIdOk() (*string, bool) {
	if o == nil || IsNil(o.TerminalId) {
		return nil, false
	}
	return o.TerminalId, true
}

// HasTerminalId returns a boolean if a field has been set.
func (o *DetailedSettlementDto) HasTerminalId() bool {
	if o != nil && !IsNil(o.TerminalId) {
		return true
	}

	return false
}

// SetTerminalId gets a reference to the given string and assigns it to the TerminalId field.
func (o *DetailedSettlementDto) SetTerminalId(v string) {
	o.TerminalId = &v
}

// GetFileName returns the FileName field value if set, zero value otherwise.
func (o *DetailedSettlementDto) GetFileName() string {
	if o == nil || IsNil(o.FileName) {
		var ret string
		return ret
	}
	return *o.FileName
}

// GetFileNameOk returns a tuple with the FileName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedSettlementDto) GetFileNameOk() (*string, bool) {
	if o == nil || IsNil(o.FileName) {
		return nil, false
	}
	return o.FileName, true
}

// HasFileName returns a boolean if a field has been set.
func (o *DetailedSettlementDto) HasFileName() bool {
	if o != nil && !IsNil(o.FileName) {
		return true
	}

	return false
}

// SetFileName gets a reference to the given string and assigns it to the FileName field.
func (o *DetailedSettlementDto) SetFileName(v string) {
	o.FileName = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *DetailedSettlementDto) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedSettlementDto) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *DetailedSettlementDto) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *DetailedSettlementDto) SetState(v string) {
	o.State = &v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *DetailedSettlementDto) GetAmount() int64 {
	if o == nil || IsNil(o.Amount) {
		var ret int64
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedSettlementDto) GetAmountOk() (*int64, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *DetailedSettlementDto) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given int64 and assigns it to the Amount field.
func (o *DetailedSettlementDto) SetAmount(v int64) {
	o.Amount = &v
}

// GetWage returns the Wage field value if set, zero value otherwise.
func (o *DetailedSettlementDto) GetWage() int64 {
	if o == nil || IsNil(o.Wage) {
		var ret int64
		return ret
	}
	return *o.Wage
}

// GetWageOk returns a tuple with the Wage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedSettlementDto) GetWageOk() (*int64, bool) {
	if o == nil || IsNil(o.Wage) {
		return nil, false
	}
	return o.Wage, true
}

// HasWage returns a boolean if a field has been set.
func (o *DetailedSettlementDto) HasWage() bool {
	if o != nil && !IsNil(o.Wage) {
		return true
	}

	return false
}

// SetWage gets a reference to the given int64 and assigns it to the Wage field.
func (o *DetailedSettlementDto) SetWage(v int64) {
	o.Wage = &v
}

// GetDirectSettlement returns the DirectSettlement field value if set, zero value otherwise.
func (o *DetailedSettlementDto) GetDirectSettlement() bool {
	if o == nil || IsNil(o.DirectSettlement) {
		var ret bool
		return ret
	}
	return *o.DirectSettlement
}

// GetDirectSettlementOk returns a tuple with the DirectSettlement field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedSettlementDto) GetDirectSettlementOk() (*bool, bool) {
	if o == nil || IsNil(o.DirectSettlement) {
		return nil, false
	}
	return o.DirectSettlement, true
}

// HasDirectSettlement returns a boolean if a field has been set.
func (o *DetailedSettlementDto) HasDirectSettlement() bool {
	if o != nil && !IsNil(o.DirectSettlement) {
		return true
	}

	return false
}

// SetDirectSettlement gets a reference to the given bool and assigns it to the DirectSettlement field.
func (o *DetailedSettlementDto) SetDirectSettlement(v bool) {
	o.DirectSettlement = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *DetailedSettlementDto) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedSettlementDto) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *DetailedSettlementDto) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *DetailedSettlementDto) SetCurrency(v string) {
	o.Currency = &v
}

// GetCutoff returns the Cutoff field value if set, zero value otherwise.
func (o *DetailedSettlementDto) GetCutoff() string {
	if o == nil || IsNil(o.Cutoff) {
		var ret string
		return ret
	}
	return *o.Cutoff
}

// GetCutoffOk returns a tuple with the Cutoff field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedSettlementDto) GetCutoffOk() (*string, bool) {
	if o == nil || IsNil(o.Cutoff) {
		return nil, false
	}
	return o.Cutoff, true
}

// HasCutoff returns a boolean if a field has been set.
func (o *DetailedSettlementDto) HasCutoff() bool {
	if o != nil && !IsNil(o.Cutoff) {
		return true
	}

	return false
}

// SetCutoff gets a reference to the given string and assigns it to the Cutoff field.
func (o *DetailedSettlementDto) SetCutoff(v string) {
	o.Cutoff = &v
}

// GetAcceptorCode returns the AcceptorCode field value if set, zero value otherwise.
func (o *DetailedSettlementDto) GetAcceptorCode() string {
	if o == nil || IsNil(o.AcceptorCode) {
		var ret string
		return ret
	}
	return *o.AcceptorCode
}

// GetAcceptorCodeOk returns a tuple with the AcceptorCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedSettlementDto) GetAcceptorCodeOk() (*string, bool) {
	if o == nil || IsNil(o.AcceptorCode) {
		return nil, false
	}
	return o.AcceptorCode, true
}

// HasAcceptorCode returns a boolean if a field has been set.
func (o *DetailedSettlementDto) HasAcceptorCode() bool {
	if o != nil && !IsNil(o.AcceptorCode) {
		return true
	}

	return false
}

// SetAcceptorCode gets a reference to the given string and assigns it to the AcceptorCode field.
func (o *DetailedSettlementDto) SetAcceptorCode(v string) {
	o.AcceptorCode = &v
}

// GetLedgerAccount returns the LedgerAccount field value if set, zero value otherwise.
func (o *DetailedSettlementDto) GetLedgerAccount() string {
	if o == nil || IsNil(o.LedgerAccount) {
		var ret string
		return ret
	}
	return *o.LedgerAccount
}

// GetLedgerAccountOk returns a tuple with the LedgerAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedSettlementDto) GetLedgerAccountOk() (*string, bool) {
	if o == nil || IsNil(o.LedgerAccount) {
		return nil, false
	}
	return o.LedgerAccount, true
}

// HasLedgerAccount returns a boolean if a field has been set.
func (o *DetailedSettlementDto) HasLedgerAccount() bool {
	if o != nil && !IsNil(o.LedgerAccount) {
		return true
	}

	return false
}

// SetLedgerAccount gets a reference to the given string and assigns it to the LedgerAccount field.
func (o *DetailedSettlementDto) SetLedgerAccount(v string) {
	o.LedgerAccount = &v
}

// GetIin returns the Iin field value if set, zero value otherwise.
func (o *DetailedSettlementDto) GetIin() int64 {
	if o == nil || IsNil(o.Iin) {
		var ret int64
		return ret
	}
	return *o.Iin
}

// GetIinOk returns a tuple with the Iin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedSettlementDto) GetIinOk() (*int64, bool) {
	if o == nil || IsNil(o.Iin) {
		return nil, false
	}
	return o.Iin, true
}

// HasIin returns a boolean if a field has been set.
func (o *DetailedSettlementDto) HasIin() bool {
	if o != nil && !IsNil(o.Iin) {
		return true
	}

	return false
}

// SetIin gets a reference to the given int64 and assigns it to the Iin field.
func (o *DetailedSettlementDto) SetIin(v int64) {
	o.Iin = &v
}

// GetPaymentFacilitatorIban returns the PaymentFacilitatorIban field value if set, zero value otherwise.
func (o *DetailedSettlementDto) GetPaymentFacilitatorIban() string {
	if o == nil || IsNil(o.PaymentFacilitatorIban) {
		var ret string
		return ret
	}
	return *o.PaymentFacilitatorIban
}

// GetPaymentFacilitatorIbanOk returns a tuple with the PaymentFacilitatorIban field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedSettlementDto) GetPaymentFacilitatorIbanOk() (*string, bool) {
	if o == nil || IsNil(o.PaymentFacilitatorIban) {
		return nil, false
	}
	return o.PaymentFacilitatorIban, true
}

// HasPaymentFacilitatorIban returns a boolean if a field has been set.
func (o *DetailedSettlementDto) HasPaymentFacilitatorIban() bool {
	if o != nil && !IsNil(o.PaymentFacilitatorIban) {
		return true
	}

	return false
}

// SetPaymentFacilitatorIban gets a reference to the given string and assigns it to the PaymentFacilitatorIban field.
func (o *DetailedSettlementDto) SetPaymentFacilitatorIban(v string) {
	o.PaymentFacilitatorIban = &v
}

// GetSettlementIban returns the SettlementIban field value if set, zero value otherwise.
func (o *DetailedSettlementDto) GetSettlementIban() string {
	if o == nil || IsNil(o.SettlementIban) {
		var ret string
		return ret
	}
	return *o.SettlementIban
}

// GetSettlementIbanOk returns a tuple with the SettlementIban field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedSettlementDto) GetSettlementIbanOk() (*string, bool) {
	if o == nil || IsNil(o.SettlementIban) {
		return nil, false
	}
	return o.SettlementIban, true
}

// HasSettlementIban returns a boolean if a field has been set.
func (o *DetailedSettlementDto) HasSettlementIban() bool {
	if o != nil && !IsNil(o.SettlementIban) {
		return true
	}

	return false
}

// SetSettlementIban gets a reference to the given string and assigns it to the SettlementIban field.
func (o *DetailedSettlementDto) SetSettlementIban(v string) {
	o.SettlementIban = &v
}

// GetResellerCode returns the ResellerCode field value if set, zero value otherwise.
func (o *DetailedSettlementDto) GetResellerCode() string {
	if o == nil || IsNil(o.ResellerCode) {
		var ret string
		return ret
	}
	return *o.ResellerCode
}

// GetResellerCodeOk returns a tuple with the ResellerCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedSettlementDto) GetResellerCodeOk() (*string, bool) {
	if o == nil || IsNil(o.ResellerCode) {
		return nil, false
	}
	return o.ResellerCode, true
}

// HasResellerCode returns a boolean if a field has been set.
func (o *DetailedSettlementDto) HasResellerCode() bool {
	if o != nil && !IsNil(o.ResellerCode) {
		return true
	}

	return false
}

// SetResellerCode gets a reference to the given string and assigns it to the ResellerCode field.
func (o *DetailedSettlementDto) SetResellerCode(v string) {
	o.ResellerCode = &v
}

// GetAffiliateFee returns the AffiliateFee field value if set, zero value otherwise.
func (o *DetailedSettlementDto) GetAffiliateFee() int64 {
	if o == nil || IsNil(o.AffiliateFee) {
		var ret int64
		return ret
	}
	return *o.AffiliateFee
}

// GetAffiliateFeeOk returns a tuple with the AffiliateFee field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedSettlementDto) GetAffiliateFeeOk() (*int64, bool) {
	if o == nil || IsNil(o.AffiliateFee) {
		return nil, false
	}
	return o.AffiliateFee, true
}

// HasAffiliateFee returns a boolean if a field has been set.
func (o *DetailedSettlementDto) HasAffiliateFee() bool {
	if o != nil && !IsNil(o.AffiliateFee) {
		return true
	}

	return false
}

// SetAffiliateFee gets a reference to the given int64 and assigns it to the AffiliateFee field.
func (o *DetailedSettlementDto) SetAffiliateFee(v int64) {
	o.AffiliateFee = &v
}

// GetShaparakFailReason returns the ShaparakFailReason field value if set, zero value otherwise.
func (o *DetailedSettlementDto) GetShaparakFailReason() string {
	if o == nil || IsNil(o.ShaparakFailReason) {
		var ret string
		return ret
	}
	return *o.ShaparakFailReason
}

// GetShaparakFailReasonOk returns a tuple with the ShaparakFailReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedSettlementDto) GetShaparakFailReasonOk() (*string, bool) {
	if o == nil || IsNil(o.ShaparakFailReason) {
		return nil, false
	}
	return o.ShaparakFailReason, true
}

// HasShaparakFailReason returns a boolean if a field has been set.
func (o *DetailedSettlementDto) HasShaparakFailReason() bool {
	if o != nil && !IsNil(o.ShaparakFailReason) {
		return true
	}

	return false
}

// SetShaparakFailReason gets a reference to the given string and assigns it to the ShaparakFailReason field.
func (o *DetailedSettlementDto) SetShaparakFailReason(v string) {
	o.ShaparakFailReason = &v
}

// GetShaparakReferenceNumber returns the ShaparakReferenceNumber field value if set, zero value otherwise.
func (o *DetailedSettlementDto) GetShaparakReferenceNumber() string {
	if o == nil || IsNil(o.ShaparakReferenceNumber) {
		var ret string
		return ret
	}
	return *o.ShaparakReferenceNumber
}

// GetShaparakReferenceNumberOk returns a tuple with the ShaparakReferenceNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedSettlementDto) GetShaparakReferenceNumberOk() (*string, bool) {
	if o == nil || IsNil(o.ShaparakReferenceNumber) {
		return nil, false
	}
	return o.ShaparakReferenceNumber, true
}

// HasShaparakReferenceNumber returns a boolean if a field has been set.
func (o *DetailedSettlementDto) HasShaparakReferenceNumber() bool {
	if o != nil && !IsNil(o.ShaparakReferenceNumber) {
		return true
	}

	return false
}

// SetShaparakReferenceNumber gets a reference to the given string and assigns it to the ShaparakReferenceNumber field.
func (o *DetailedSettlementDto) SetShaparakReferenceNumber(v string) {
	o.ShaparakReferenceNumber = &v
}

// GetShaparakTrackingNumber returns the ShaparakTrackingNumber field value if set, zero value otherwise.
func (o *DetailedSettlementDto) GetShaparakTrackingNumber() string {
	if o == nil || IsNil(o.ShaparakTrackingNumber) {
		var ret string
		return ret
	}
	return *o.ShaparakTrackingNumber
}

// GetShaparakTrackingNumberOk returns a tuple with the ShaparakTrackingNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedSettlementDto) GetShaparakTrackingNumberOk() (*string, bool) {
	if o == nil || IsNil(o.ShaparakTrackingNumber) {
		return nil, false
	}
	return o.ShaparakTrackingNumber, true
}

// HasShaparakTrackingNumber returns a boolean if a field has been set.
func (o *DetailedSettlementDto) HasShaparakTrackingNumber() bool {
	if o != nil && !IsNil(o.ShaparakTrackingNumber) {
		return true
	}

	return false
}

// SetShaparakTrackingNumber gets a reference to the given string and assigns it to the ShaparakTrackingNumber field.
func (o *DetailedSettlementDto) SetShaparakTrackingNumber(v string) {
	o.ShaparakTrackingNumber = &v
}

// GetShaparakTransactionId returns the ShaparakTransactionId field value if set, zero value otherwise.
func (o *DetailedSettlementDto) GetShaparakTransactionId() string {
	if o == nil || IsNil(o.ShaparakTransactionId) {
		var ret string
		return ret
	}
	return *o.ShaparakTransactionId
}

// GetShaparakTransactionIdOk returns a tuple with the ShaparakTransactionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedSettlementDto) GetShaparakTransactionIdOk() (*string, bool) {
	if o == nil || IsNil(o.ShaparakTransactionId) {
		return nil, false
	}
	return o.ShaparakTransactionId, true
}

// HasShaparakTransactionId returns a boolean if a field has been set.
func (o *DetailedSettlementDto) HasShaparakTransactionId() bool {
	if o != nil && !IsNil(o.ShaparakTransactionId) {
		return true
	}

	return false
}

// SetShaparakTransactionId gets a reference to the given string and assigns it to the ShaparakTransactionId field.
func (o *DetailedSettlementDto) SetShaparakTransactionId(v string) {
	o.ShaparakTransactionId = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *DetailedSettlementDto) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedSettlementDto) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *DetailedSettlementDto) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *DetailedSettlementDto) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetModifiedAt returns the ModifiedAt field value if set, zero value otherwise.
func (o *DetailedSettlementDto) GetModifiedAt() time.Time {
	if o == nil || IsNil(o.ModifiedAt) {
		var ret time.Time
		return ret
	}
	return *o.ModifiedAt
}

// GetModifiedAtOk returns a tuple with the ModifiedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedSettlementDto) GetModifiedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ModifiedAt) {
		return nil, false
	}
	return o.ModifiedAt, true
}

// HasModifiedAt returns a boolean if a field has been set.
func (o *DetailedSettlementDto) HasModifiedAt() bool {
	if o != nil && !IsNil(o.ModifiedAt) {
		return true
	}

	return false
}

// SetModifiedAt gets a reference to the given time.Time and assigns it to the ModifiedAt field.
func (o *DetailedSettlementDto) SetModifiedAt(v time.Time) {
	o.ModifiedAt = &v
}

// GetSettledAt returns the SettledAt field value if set, zero value otherwise.
func (o *DetailedSettlementDto) GetSettledAt() time.Time {
	if o == nil || IsNil(o.SettledAt) {
		var ret time.Time
		return ret
	}
	return *o.SettledAt
}

// GetSettledAtOk returns a tuple with the SettledAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedSettlementDto) GetSettledAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.SettledAt) {
		return nil, false
	}
	return o.SettledAt, true
}

// HasSettledAt returns a boolean if a field has been set.
func (o *DetailedSettlementDto) HasSettledAt() bool {
	if o != nil && !IsNil(o.SettledAt) {
		return true
	}

	return false
}

// SetSettledAt gets a reference to the given time.Time and assigns it to the SettledAt field.
func (o *DetailedSettlementDto) SetSettledAt(v time.Time) {
	o.SettledAt = &v
}

func (o DetailedSettlementDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DetailedSettlementDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SettlementId) {
		toSerialize["settlementId"] = o.SettlementId
	}
	if !IsNil(o.TerminalId) {
		toSerialize["terminalId"] = o.TerminalId
	}
	if !IsNil(o.FileName) {
		toSerialize["fileName"] = o.FileName
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.Wage) {
		toSerialize["wage"] = o.Wage
	}
	if !IsNil(o.DirectSettlement) {
		toSerialize["directSettlement"] = o.DirectSettlement
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.Cutoff) {
		toSerialize["cutoff"] = o.Cutoff
	}
	if !IsNil(o.AcceptorCode) {
		toSerialize["acceptorCode"] = o.AcceptorCode
	}
	if !IsNil(o.LedgerAccount) {
		toSerialize["ledgerAccount"] = o.LedgerAccount
	}
	if !IsNil(o.Iin) {
		toSerialize["iin"] = o.Iin
	}
	if !IsNil(o.PaymentFacilitatorIban) {
		toSerialize["paymentFacilitatorIban"] = o.PaymentFacilitatorIban
	}
	if !IsNil(o.SettlementIban) {
		toSerialize["settlementIban"] = o.SettlementIban
	}
	if !IsNil(o.ResellerCode) {
		toSerialize["resellerCode"] = o.ResellerCode
	}
	if !IsNil(o.AffiliateFee) {
		toSerialize["affiliateFee"] = o.AffiliateFee
	}
	if !IsNil(o.ShaparakFailReason) {
		toSerialize["shaparakFailReason"] = o.ShaparakFailReason
	}
	if !IsNil(o.ShaparakReferenceNumber) {
		toSerialize["shaparakReferenceNumber"] = o.ShaparakReferenceNumber
	}
	if !IsNil(o.ShaparakTrackingNumber) {
		toSerialize["shaparakTrackingNumber"] = o.ShaparakTrackingNumber
	}
	if !IsNil(o.ShaparakTransactionId) {
		toSerialize["shaparakTransactionId"] = o.ShaparakTransactionId
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.ModifiedAt) {
		toSerialize["modifiedAt"] = o.ModifiedAt
	}
	if !IsNil(o.SettledAt) {
		toSerialize["settledAt"] = o.SettledAt
	}
	return toSerialize, nil
}

type NullableDetailedSettlementDto struct {
	value *DetailedSettlementDto
	isSet bool
}

func (v NullableDetailedSettlementDto) Get() *DetailedSettlementDto {
	return v.value
}

func (v *NullableDetailedSettlementDto) Set(val *DetailedSettlementDto) {
	v.value = val
	v.isSet = true
}

func (v NullableDetailedSettlementDto) IsSet() bool {
	return v.isSet
}

func (v *NullableDetailedSettlementDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDetailedSettlementDto(val *DetailedSettlementDto) *NullableDetailedSettlementDto {
	return &NullableDetailedSettlementDto{value: val, isSet: true}
}

func (v NullableDetailedSettlementDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDetailedSettlementDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


