/*
PPG: Proxy Payment Gateway

PPG is the Proxy Payment Gateway of Jibit corporation. It lets the users of 3rd-party clients (merchants, banks, organizations, ...) to purchase goodies from them using PPG as a transparent payment gateway. In back-end the user will be redirected to a PSP payment gateway (for example Saman) to pay the price of the purchase.  Using APIs of this application a client can create and initiate the purchase orders and can track the state of these purchases.  Using *Swagger Editor* you could directly call the PPG APIs and also could auto-generate a client for PPG APIs in your preferred programming language.  The base URL of PPG is: `https://napi.jibit.ir/ppg`  Full documentation is available on: https://napi.jibit.ir/ppg/v3/static/docs/index.html

API version: 3.2.48
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package jibit-ppg

import (
	"encoding/json"
)

// checks if the GenerateTokenRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GenerateTokenRequest{}

// GenerateTokenRequest The dto encapsulating the information to generate a pair of access/refresh tokens.
type GenerateTokenRequest struct {
	// Represents the api key of client.
	ApiKey *string `json:"apiKey,omitempty"`
	// Represents the secret key of client.
	SecretKey *string `json:"secretKey,omitempty"`
}

// NewGenerateTokenRequest instantiates a new GenerateTokenRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGenerateTokenRequest() *GenerateTokenRequest {
	this := GenerateTokenRequest{}
	return &this
}

// NewGenerateTokenRequestWithDefaults instantiates a new GenerateTokenRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGenerateTokenRequestWithDefaults() *GenerateTokenRequest {
	this := GenerateTokenRequest{}
	return &this
}

// GetApiKey returns the ApiKey field value if set, zero value otherwise.
func (o *GenerateTokenRequest) GetApiKey() string {
	if o == nil || IsNil(o.ApiKey) {
		var ret string
		return ret
	}
	return *o.ApiKey
}

// GetApiKeyOk returns a tuple with the ApiKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GenerateTokenRequest) GetApiKeyOk() (*string, bool) {
	if o == nil || IsNil(o.ApiKey) {
		return nil, false
	}
	return o.ApiKey, true
}

// HasApiKey returns a boolean if a field has been set.
func (o *GenerateTokenRequest) HasApiKey() bool {
	if o != nil && !IsNil(o.ApiKey) {
		return true
	}

	return false
}

// SetApiKey gets a reference to the given string and assigns it to the ApiKey field.
func (o *GenerateTokenRequest) SetApiKey(v string) {
	o.ApiKey = &v
}

// GetSecretKey returns the SecretKey field value if set, zero value otherwise.
func (o *GenerateTokenRequest) GetSecretKey() string {
	if o == nil || IsNil(o.SecretKey) {
		var ret string
		return ret
	}
	return *o.SecretKey
}

// GetSecretKeyOk returns a tuple with the SecretKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GenerateTokenRequest) GetSecretKeyOk() (*string, bool) {
	if o == nil || IsNil(o.SecretKey) {
		return nil, false
	}
	return o.SecretKey, true
}

// HasSecretKey returns a boolean if a field has been set.
func (o *GenerateTokenRequest) HasSecretKey() bool {
	if o != nil && !IsNil(o.SecretKey) {
		return true
	}

	return false
}

// SetSecretKey gets a reference to the given string and assigns it to the SecretKey field.
func (o *GenerateTokenRequest) SetSecretKey(v string) {
	o.SecretKey = &v
}

func (o GenerateTokenRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GenerateTokenRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ApiKey) {
		toSerialize["apiKey"] = o.ApiKey
	}
	if !IsNil(o.SecretKey) {
		toSerialize["secretKey"] = o.SecretKey
	}
	return toSerialize, nil
}

type NullableGenerateTokenRequest struct {
	value *GenerateTokenRequest
	isSet bool
}

func (v NullableGenerateTokenRequest) Get() *GenerateTokenRequest {
	return v.value
}

func (v *NullableGenerateTokenRequest) Set(val *GenerateTokenRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGenerateTokenRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGenerateTokenRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGenerateTokenRequest(val *GenerateTokenRequest) *NullableGenerateTokenRequest {
	return &NullableGenerateTokenRequest{value: val, isSet: true}
}

func (v NullableGenerateTokenRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGenerateTokenRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


