/*
PPG: Proxy Payment Gateway

PPG is the Proxy Payment Gateway of Jibit corporation. It lets the users of 3rd-party clients (merchants, banks, organizations, ...) to purchase goodies from them using PPG as a transparent payment gateway. In back-end the user will be redirected to a PSP payment gateway (for example Saman) to pay the price of the purchase.  Using APIs of this application a client can create and initiate the purchase orders and can track the state of these purchases.  Using *Swagger Editor* you could directly call the PPG APIs and also could auto-generate a client for PPG APIs in your preferred programming language.  The base URL of PPG is: `https://napi.jibit.ir/ppg`  Full documentation is available on: https://napi.jibit.ir/ppg/v3/static/docs/index.html

API version: 3.2.48
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ppg

import (
	"encoding/json"
)

// checks if the IdPaginatedDetailedPurchaseHistoryDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IdPaginatedDetailedPurchaseHistoryDto{}

// IdPaginatedDetailedPurchaseHistoryDto A Data Transfer Object (DTO) representing a paginated collection of elements, filtered by a next page identifier (`nextPageId`).  This DTO allows efficient pagination using entity identifiers, optimizing for faster response times.
type IdPaginatedDetailedPurchaseHistoryDto struct {
	// The number of elements in the current page.
	Size *int32 `json:"size,omitempty"`
	// The total number of elements. If null, the total count was not calculated for faster response times.
	TotalCount *int64 `json:"totalCount,omitempty"`
	// Indicates if there is another page following the current one.
	HasNext *bool `json:"hasNext,omitempty"`
	// The identifier for fetching the next page of results.  This provides more efficient pagination compared to using a traditional page number.  Note: This can be null if there are no more results or if the result set is empty.
	NextPageId *string `json:"nextPageId,omitempty"`
	// The list of elements in the current page.
	Elements []DetailedPurchaseHistoryDto `json:"elements,omitempty"`
}

// NewIdPaginatedDetailedPurchaseHistoryDto instantiates a new IdPaginatedDetailedPurchaseHistoryDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIdPaginatedDetailedPurchaseHistoryDto() *IdPaginatedDetailedPurchaseHistoryDto {
	this := IdPaginatedDetailedPurchaseHistoryDto{}
	return &this
}

// NewIdPaginatedDetailedPurchaseHistoryDtoWithDefaults instantiates a new IdPaginatedDetailedPurchaseHistoryDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIdPaginatedDetailedPurchaseHistoryDtoWithDefaults() *IdPaginatedDetailedPurchaseHistoryDto {
	this := IdPaginatedDetailedPurchaseHistoryDto{}
	return &this
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *IdPaginatedDetailedPurchaseHistoryDto) GetSize() int32 {
	if o == nil || IsNil(o.Size) {
		var ret int32
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdPaginatedDetailedPurchaseHistoryDto) GetSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *IdPaginatedDetailedPurchaseHistoryDto) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given int32 and assigns it to the Size field.
func (o *IdPaginatedDetailedPurchaseHistoryDto) SetSize(v int32) {
	o.Size = &v
}

// GetTotalCount returns the TotalCount field value if set, zero value otherwise.
func (o *IdPaginatedDetailedPurchaseHistoryDto) GetTotalCount() int64 {
	if o == nil || IsNil(o.TotalCount) {
		var ret int64
		return ret
	}
	return *o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdPaginatedDetailedPurchaseHistoryDto) GetTotalCountOk() (*int64, bool) {
	if o == nil || IsNil(o.TotalCount) {
		return nil, false
	}
	return o.TotalCount, true
}

// HasTotalCount returns a boolean if a field has been set.
func (o *IdPaginatedDetailedPurchaseHistoryDto) HasTotalCount() bool {
	if o != nil && !IsNil(o.TotalCount) {
		return true
	}

	return false
}

// SetTotalCount gets a reference to the given int64 and assigns it to the TotalCount field.
func (o *IdPaginatedDetailedPurchaseHistoryDto) SetTotalCount(v int64) {
	o.TotalCount = &v
}

// GetHasNext returns the HasNext field value if set, zero value otherwise.
func (o *IdPaginatedDetailedPurchaseHistoryDto) GetHasNext() bool {
	if o == nil || IsNil(o.HasNext) {
		var ret bool
		return ret
	}
	return *o.HasNext
}

// GetHasNextOk returns a tuple with the HasNext field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdPaginatedDetailedPurchaseHistoryDto) GetHasNextOk() (*bool, bool) {
	if o == nil || IsNil(o.HasNext) {
		return nil, false
	}
	return o.HasNext, true
}

// HasHasNext returns a boolean if a field has been set.
func (o *IdPaginatedDetailedPurchaseHistoryDto) HasHasNext() bool {
	if o != nil && !IsNil(o.HasNext) {
		return true
	}

	return false
}

// SetHasNext gets a reference to the given bool and assigns it to the HasNext field.
func (o *IdPaginatedDetailedPurchaseHistoryDto) SetHasNext(v bool) {
	o.HasNext = &v
}

// GetNextPageId returns the NextPageId field value if set, zero value otherwise.
func (o *IdPaginatedDetailedPurchaseHistoryDto) GetNextPageId() string {
	if o == nil || IsNil(o.NextPageId) {
		var ret string
		return ret
	}
	return *o.NextPageId
}

// GetNextPageIdOk returns a tuple with the NextPageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdPaginatedDetailedPurchaseHistoryDto) GetNextPageIdOk() (*string, bool) {
	if o == nil || IsNil(o.NextPageId) {
		return nil, false
	}
	return o.NextPageId, true
}

// HasNextPageId returns a boolean if a field has been set.
func (o *IdPaginatedDetailedPurchaseHistoryDto) HasNextPageId() bool {
	if o != nil && !IsNil(o.NextPageId) {
		return true
	}

	return false
}

// SetNextPageId gets a reference to the given string and assigns it to the NextPageId field.
func (o *IdPaginatedDetailedPurchaseHistoryDto) SetNextPageId(v string) {
	o.NextPageId = &v
}

// GetElements returns the Elements field value if set, zero value otherwise.
func (o *IdPaginatedDetailedPurchaseHistoryDto) GetElements() []DetailedPurchaseHistoryDto {
	if o == nil || IsNil(o.Elements) {
		var ret []DetailedPurchaseHistoryDto
		return ret
	}
	return o.Elements
}

// GetElementsOk returns a tuple with the Elements field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdPaginatedDetailedPurchaseHistoryDto) GetElementsOk() ([]DetailedPurchaseHistoryDto, bool) {
	if o == nil || IsNil(o.Elements) {
		return nil, false
	}
	return o.Elements, true
}

// HasElements returns a boolean if a field has been set.
func (o *IdPaginatedDetailedPurchaseHistoryDto) HasElements() bool {
	if o != nil && !IsNil(o.Elements) {
		return true
	}

	return false
}

// SetElements gets a reference to the given []DetailedPurchaseHistoryDto and assigns it to the Elements field.
func (o *IdPaginatedDetailedPurchaseHistoryDto) SetElements(v []DetailedPurchaseHistoryDto) {
	o.Elements = v
}

func (o IdPaginatedDetailedPurchaseHistoryDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IdPaginatedDetailedPurchaseHistoryDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	if !IsNil(o.TotalCount) {
		toSerialize["totalCount"] = o.TotalCount
	}
	if !IsNil(o.HasNext) {
		toSerialize["hasNext"] = o.HasNext
	}
	if !IsNil(o.NextPageId) {
		toSerialize["nextPageId"] = o.NextPageId
	}
	if !IsNil(o.Elements) {
		toSerialize["elements"] = o.Elements
	}
	return toSerialize, nil
}

type NullableIdPaginatedDetailedPurchaseHistoryDto struct {
	value *IdPaginatedDetailedPurchaseHistoryDto
	isSet bool
}

func (v NullableIdPaginatedDetailedPurchaseHistoryDto) Get() *IdPaginatedDetailedPurchaseHistoryDto {
	return v.value
}

func (v *NullableIdPaginatedDetailedPurchaseHistoryDto) Set(val *IdPaginatedDetailedPurchaseHistoryDto) {
	v.value = val
	v.isSet = true
}

func (v NullableIdPaginatedDetailedPurchaseHistoryDto) IsSet() bool {
	return v.isSet
}

func (v *NullableIdPaginatedDetailedPurchaseHistoryDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIdPaginatedDetailedPurchaseHistoryDto(val *IdPaginatedDetailedPurchaseHistoryDto) *NullableIdPaginatedDetailedPurchaseHistoryDto {
	return &NullableIdPaginatedDetailedPurchaseHistoryDto{value: val, isSet: true}
}

func (v NullableIdPaginatedDetailedPurchaseHistoryDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIdPaginatedDetailedPurchaseHistoryDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


