/*
PPG: Proxy Payment Gateway

PPG is the Proxy Payment Gateway of Jibit corporation. It lets the users of 3rd-party clients (merchants, banks, organizations, ...) to purchase goodies from them using PPG as a transparent payment gateway. In back-end the user will be redirected to a PSP payment gateway (for example Saman) to pay the price of the purchase.  Using APIs of this application a client can create and initiate the purchase orders and can track the state of these purchases.  Using *Swagger Editor* you could directly call the PPG APIs and also could auto-generate a client for PPG APIs in your preferred programming language.  The base URL of PPG is: `https://napi.jibit.ir/ppg`  Full documentation is available on: https://napi.jibit.ir/ppg/v3/static/docs/index.html

API version: 3.2.48
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ppg

import (
	"encoding/json"
	"time"
)

// checks if the PurchaseFilterCriteria type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PurchaseFilterCriteria{}

// PurchaseFilterCriteria Encapsulates the information to filter purchases.
type PurchaseFilterCriteria struct {
	// Finds a purchase by its identifier. Can be used to find an exact purchase. The `null` means no filtering at all.
	PurchaseId *int64 `json:"purchaseId,omitempty"`
	// Filters purchases based on their state. The `null` means no filtering at all.
	Status *string `json:"status,omitempty"`
	// Finds a purchase by its client reference number. The `null` means no filtering at all.
	ClientReferenceNumber *string `json:"clientReferenceNumber,omitempty"`
	// Filters purchases by their PSP reference number. The `null` means no filtering at all.
	PspReferenceNumber *string `json:"pspReferenceNumber,omitempty"`
	// Filters purchases by their PSP RRN. The `null` means no filtering at all.
	PspRrn *string `json:"pspRrn,omitempty"`
	// Filters purchases by their PSP trace number. The `null` means no filtering at all.
	PspTraceNumber *string `json:"pspTraceNumber,omitempty"`
	// Filters purchases based on their user identifier. The `null` means no filtering at all.
	UserIdentifier *string `json:"userIdentifier,omitempty"`
	// Filters purchases from their creation date inclusively. The `null` means no filtering at all.
	From *time.Time `json:"from,omitempty"`
	// Filters purchases to their creation date exclusively. The `null` means no filtering at all.
	To *time.Time `json:"to,omitempty"`
	// Represents the page number; One indexed. The `null` means the first page.  The max page number is 20.
	Page *int32 `json:"page,omitempty"`
	// Represents the page size. The `null` means to use default size.  The default page size is 25.  The max page size is 250.
	Size *int32 `json:"size,omitempty"`
}

// NewPurchaseFilterCriteria instantiates a new PurchaseFilterCriteria object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPurchaseFilterCriteria() *PurchaseFilterCriteria {
	this := PurchaseFilterCriteria{}
	return &this
}

// NewPurchaseFilterCriteriaWithDefaults instantiates a new PurchaseFilterCriteria object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPurchaseFilterCriteriaWithDefaults() *PurchaseFilterCriteria {
	this := PurchaseFilterCriteria{}
	return &this
}

// GetPurchaseId returns the PurchaseId field value if set, zero value otherwise.
func (o *PurchaseFilterCriteria) GetPurchaseId() int64 {
	if o == nil || IsNil(o.PurchaseId) {
		var ret int64
		return ret
	}
	return *o.PurchaseId
}

// GetPurchaseIdOk returns a tuple with the PurchaseId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurchaseFilterCriteria) GetPurchaseIdOk() (*int64, bool) {
	if o == nil || IsNil(o.PurchaseId) {
		return nil, false
	}
	return o.PurchaseId, true
}

// HasPurchaseId returns a boolean if a field has been set.
func (o *PurchaseFilterCriteria) HasPurchaseId() bool {
	if o != nil && !IsNil(o.PurchaseId) {
		return true
	}

	return false
}

// SetPurchaseId gets a reference to the given int64 and assigns it to the PurchaseId field.
func (o *PurchaseFilterCriteria) SetPurchaseId(v int64) {
	o.PurchaseId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *PurchaseFilterCriteria) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurchaseFilterCriteria) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *PurchaseFilterCriteria) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *PurchaseFilterCriteria) SetStatus(v string) {
	o.Status = &v
}

// GetClientReferenceNumber returns the ClientReferenceNumber field value if set, zero value otherwise.
func (o *PurchaseFilterCriteria) GetClientReferenceNumber() string {
	if o == nil || IsNil(o.ClientReferenceNumber) {
		var ret string
		return ret
	}
	return *o.ClientReferenceNumber
}

// GetClientReferenceNumberOk returns a tuple with the ClientReferenceNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurchaseFilterCriteria) GetClientReferenceNumberOk() (*string, bool) {
	if o == nil || IsNil(o.ClientReferenceNumber) {
		return nil, false
	}
	return o.ClientReferenceNumber, true
}

// HasClientReferenceNumber returns a boolean if a field has been set.
func (o *PurchaseFilterCriteria) HasClientReferenceNumber() bool {
	if o != nil && !IsNil(o.ClientReferenceNumber) {
		return true
	}

	return false
}

// SetClientReferenceNumber gets a reference to the given string and assigns it to the ClientReferenceNumber field.
func (o *PurchaseFilterCriteria) SetClientReferenceNumber(v string) {
	o.ClientReferenceNumber = &v
}

// GetPspReferenceNumber returns the PspReferenceNumber field value if set, zero value otherwise.
func (o *PurchaseFilterCriteria) GetPspReferenceNumber() string {
	if o == nil || IsNil(o.PspReferenceNumber) {
		var ret string
		return ret
	}
	return *o.PspReferenceNumber
}

// GetPspReferenceNumberOk returns a tuple with the PspReferenceNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurchaseFilterCriteria) GetPspReferenceNumberOk() (*string, bool) {
	if o == nil || IsNil(o.PspReferenceNumber) {
		return nil, false
	}
	return o.PspReferenceNumber, true
}

// HasPspReferenceNumber returns a boolean if a field has been set.
func (o *PurchaseFilterCriteria) HasPspReferenceNumber() bool {
	if o != nil && !IsNil(o.PspReferenceNumber) {
		return true
	}

	return false
}

// SetPspReferenceNumber gets a reference to the given string and assigns it to the PspReferenceNumber field.
func (o *PurchaseFilterCriteria) SetPspReferenceNumber(v string) {
	o.PspReferenceNumber = &v
}

// GetPspRrn returns the PspRrn field value if set, zero value otherwise.
func (o *PurchaseFilterCriteria) GetPspRrn() string {
	if o == nil || IsNil(o.PspRrn) {
		var ret string
		return ret
	}
	return *o.PspRrn
}

// GetPspRrnOk returns a tuple with the PspRrn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurchaseFilterCriteria) GetPspRrnOk() (*string, bool) {
	if o == nil || IsNil(o.PspRrn) {
		return nil, false
	}
	return o.PspRrn, true
}

// HasPspRrn returns a boolean if a field has been set.
func (o *PurchaseFilterCriteria) HasPspRrn() bool {
	if o != nil && !IsNil(o.PspRrn) {
		return true
	}

	return false
}

// SetPspRrn gets a reference to the given string and assigns it to the PspRrn field.
func (o *PurchaseFilterCriteria) SetPspRrn(v string) {
	o.PspRrn = &v
}

// GetPspTraceNumber returns the PspTraceNumber field value if set, zero value otherwise.
func (o *PurchaseFilterCriteria) GetPspTraceNumber() string {
	if o == nil || IsNil(o.PspTraceNumber) {
		var ret string
		return ret
	}
	return *o.PspTraceNumber
}

// GetPspTraceNumberOk returns a tuple with the PspTraceNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurchaseFilterCriteria) GetPspTraceNumberOk() (*string, bool) {
	if o == nil || IsNil(o.PspTraceNumber) {
		return nil, false
	}
	return o.PspTraceNumber, true
}

// HasPspTraceNumber returns a boolean if a field has been set.
func (o *PurchaseFilterCriteria) HasPspTraceNumber() bool {
	if o != nil && !IsNil(o.PspTraceNumber) {
		return true
	}

	return false
}

// SetPspTraceNumber gets a reference to the given string and assigns it to the PspTraceNumber field.
func (o *PurchaseFilterCriteria) SetPspTraceNumber(v string) {
	o.PspTraceNumber = &v
}

// GetUserIdentifier returns the UserIdentifier field value if set, zero value otherwise.
func (o *PurchaseFilterCriteria) GetUserIdentifier() string {
	if o == nil || IsNil(o.UserIdentifier) {
		var ret string
		return ret
	}
	return *o.UserIdentifier
}

// GetUserIdentifierOk returns a tuple with the UserIdentifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurchaseFilterCriteria) GetUserIdentifierOk() (*string, bool) {
	if o == nil || IsNil(o.UserIdentifier) {
		return nil, false
	}
	return o.UserIdentifier, true
}

// HasUserIdentifier returns a boolean if a field has been set.
func (o *PurchaseFilterCriteria) HasUserIdentifier() bool {
	if o != nil && !IsNil(o.UserIdentifier) {
		return true
	}

	return false
}

// SetUserIdentifier gets a reference to the given string and assigns it to the UserIdentifier field.
func (o *PurchaseFilterCriteria) SetUserIdentifier(v string) {
	o.UserIdentifier = &v
}

// GetFrom returns the From field value if set, zero value otherwise.
func (o *PurchaseFilterCriteria) GetFrom() time.Time {
	if o == nil || IsNil(o.From) {
		var ret time.Time
		return ret
	}
	return *o.From
}

// GetFromOk returns a tuple with the From field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurchaseFilterCriteria) GetFromOk() (*time.Time, bool) {
	if o == nil || IsNil(o.From) {
		return nil, false
	}
	return o.From, true
}

// HasFrom returns a boolean if a field has been set.
func (o *PurchaseFilterCriteria) HasFrom() bool {
	if o != nil && !IsNil(o.From) {
		return true
	}

	return false
}

// SetFrom gets a reference to the given time.Time and assigns it to the From field.
func (o *PurchaseFilterCriteria) SetFrom(v time.Time) {
	o.From = &v
}

// GetTo returns the To field value if set, zero value otherwise.
func (o *PurchaseFilterCriteria) GetTo() time.Time {
	if o == nil || IsNil(o.To) {
		var ret time.Time
		return ret
	}
	return *o.To
}

// GetToOk returns a tuple with the To field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurchaseFilterCriteria) GetToOk() (*time.Time, bool) {
	if o == nil || IsNil(o.To) {
		return nil, false
	}
	return o.To, true
}

// HasTo returns a boolean if a field has been set.
func (o *PurchaseFilterCriteria) HasTo() bool {
	if o != nil && !IsNil(o.To) {
		return true
	}

	return false
}

// SetTo gets a reference to the given time.Time and assigns it to the To field.
func (o *PurchaseFilterCriteria) SetTo(v time.Time) {
	o.To = &v
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *PurchaseFilterCriteria) GetPage() int32 {
	if o == nil || IsNil(o.Page) {
		var ret int32
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurchaseFilterCriteria) GetPageOk() (*int32, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *PurchaseFilterCriteria) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given int32 and assigns it to the Page field.
func (o *PurchaseFilterCriteria) SetPage(v int32) {
	o.Page = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *PurchaseFilterCriteria) GetSize() int32 {
	if o == nil || IsNil(o.Size) {
		var ret int32
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurchaseFilterCriteria) GetSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *PurchaseFilterCriteria) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given int32 and assigns it to the Size field.
func (o *PurchaseFilterCriteria) SetSize(v int32) {
	o.Size = &v
}

func (o PurchaseFilterCriteria) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PurchaseFilterCriteria) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PurchaseId) {
		toSerialize["purchaseId"] = o.PurchaseId
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.ClientReferenceNumber) {
		toSerialize["clientReferenceNumber"] = o.ClientReferenceNumber
	}
	if !IsNil(o.PspReferenceNumber) {
		toSerialize["pspReferenceNumber"] = o.PspReferenceNumber
	}
	if !IsNil(o.PspRrn) {
		toSerialize["pspRrn"] = o.PspRrn
	}
	if !IsNil(o.PspTraceNumber) {
		toSerialize["pspTraceNumber"] = o.PspTraceNumber
	}
	if !IsNil(o.UserIdentifier) {
		toSerialize["userIdentifier"] = o.UserIdentifier
	}
	if !IsNil(o.From) {
		toSerialize["from"] = o.From
	}
	if !IsNil(o.To) {
		toSerialize["to"] = o.To
	}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	return toSerialize, nil
}

type NullablePurchaseFilterCriteria struct {
	value *PurchaseFilterCriteria
	isSet bool
}

func (v NullablePurchaseFilterCriteria) Get() *PurchaseFilterCriteria {
	return v.value
}

func (v *NullablePurchaseFilterCriteria) Set(val *PurchaseFilterCriteria) {
	v.value = val
	v.isSet = true
}

func (v NullablePurchaseFilterCriteria) IsSet() bool {
	return v.isSet
}

func (v *NullablePurchaseFilterCriteria) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePurchaseFilterCriteria(val *PurchaseFilterCriteria) *NullablePurchaseFilterCriteria {
	return &NullablePurchaseFilterCriteria{value: val, isSet: true}
}

func (v NullablePurchaseFilterCriteria) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePurchaseFilterCriteria) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


