/*
PPG: Proxy Payment Gateway

PPG is the Proxy Payment Gateway of Jibit corporation. It lets the users of 3rd-party clients (merchants, banks, organizations, ...) to purchase goodies from them using PPG as a transparent payment gateway. In back-end the user will be redirected to a PSP payment gateway (for example Saman) to pay the price of the purchase.  Using APIs of this application a client can create and initiate the purchase orders and can track the state of these purchases.  Using *Swagger Editor* you could directly call the PPG APIs and also could auto-generate a client for PPG APIs in your preferred programming language.  The base URL of PPG is: `https://napi.jibit.ir/ppg`  Full documentation is available on: https://napi.jibit.ir/ppg/v3/static/docs/index.html

API version: 3.2.48
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ppg

import (
	"encoding/json"
)

// checks if the TerminalSwitchingDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TerminalSwitchingDto{}

// TerminalSwitchingDto Data transfer object used for terminal switching configuration.
type TerminalSwitchingDto struct {
	// A list of terminal natural IDs required for terminal switching.  Terminals and their natural IDs can be retrieved via the .  The list's first entry has the highest priority for initializing the purchase, while the last entry has the lowest priority.
	TerminalIds []string `json:"terminalIds,omitempty"`
	// Determines whether terminal switching is automatic or manual.  Defaults to `true`, which enables automatic switching while prioritizing terminals in the `terminalIds` list.  If set to `false`, only the specified terminals will be used without automatic switching.
	AutoSwitching *bool `json:"autoSwitching,omitempty"`
}

// NewTerminalSwitchingDto instantiates a new TerminalSwitchingDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTerminalSwitchingDto() *TerminalSwitchingDto {
	this := TerminalSwitchingDto{}
	return &this
}

// NewTerminalSwitchingDtoWithDefaults instantiates a new TerminalSwitchingDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTerminalSwitchingDtoWithDefaults() *TerminalSwitchingDto {
	this := TerminalSwitchingDto{}
	return &this
}

// GetTerminalIds returns the TerminalIds field value if set, zero value otherwise.
func (o *TerminalSwitchingDto) GetTerminalIds() []string {
	if o == nil || IsNil(o.TerminalIds) {
		var ret []string
		return ret
	}
	return o.TerminalIds
}

// GetTerminalIdsOk returns a tuple with the TerminalIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerminalSwitchingDto) GetTerminalIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.TerminalIds) {
		return nil, false
	}
	return o.TerminalIds, true
}

// HasTerminalIds returns a boolean if a field has been set.
func (o *TerminalSwitchingDto) HasTerminalIds() bool {
	if o != nil && !IsNil(o.TerminalIds) {
		return true
	}

	return false
}

// SetTerminalIds gets a reference to the given []string and assigns it to the TerminalIds field.
func (o *TerminalSwitchingDto) SetTerminalIds(v []string) {
	o.TerminalIds = v
}

// GetAutoSwitching returns the AutoSwitching field value if set, zero value otherwise.
func (o *TerminalSwitchingDto) GetAutoSwitching() bool {
	if o == nil || IsNil(o.AutoSwitching) {
		var ret bool
		return ret
	}
	return *o.AutoSwitching
}

// GetAutoSwitchingOk returns a tuple with the AutoSwitching field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerminalSwitchingDto) GetAutoSwitchingOk() (*bool, bool) {
	if o == nil || IsNil(o.AutoSwitching) {
		return nil, false
	}
	return o.AutoSwitching, true
}

// HasAutoSwitching returns a boolean if a field has been set.
func (o *TerminalSwitchingDto) HasAutoSwitching() bool {
	if o != nil && !IsNil(o.AutoSwitching) {
		return true
	}

	return false
}

// SetAutoSwitching gets a reference to the given bool and assigns it to the AutoSwitching field.
func (o *TerminalSwitchingDto) SetAutoSwitching(v bool) {
	o.AutoSwitching = &v
}

func (o TerminalSwitchingDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TerminalSwitchingDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TerminalIds) {
		toSerialize["terminalIds"] = o.TerminalIds
	}
	if !IsNil(o.AutoSwitching) {
		toSerialize["autoSwitching"] = o.AutoSwitching
	}
	return toSerialize, nil
}

type NullableTerminalSwitchingDto struct {
	value *TerminalSwitchingDto
	isSet bool
}

func (v NullableTerminalSwitchingDto) Get() *TerminalSwitchingDto {
	return v.value
}

func (v *NullableTerminalSwitchingDto) Set(val *TerminalSwitchingDto) {
	v.value = val
	v.isSet = true
}

func (v NullableTerminalSwitchingDto) IsSet() bool {
	return v.isSet
}

func (v *NullableTerminalSwitchingDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTerminalSwitchingDto(val *TerminalSwitchingDto) *NullableTerminalSwitchingDto {
	return &NullableTerminalSwitchingDto{value: val, isSet: true}
}

func (v NullableTerminalSwitchingDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTerminalSwitchingDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


