/*
PPG: Proxy Payment Gateway

PPG is the Proxy Payment Gateway of Jibit corporation. It lets the users of 3rd-party clients (merchants, banks, organizations, ...) to purchase goodies from them using PPG as a transparent payment gateway. In back-end the user will be redirected to a PSP payment gateway (for example Saman) to pay the price of the purchase.  Using APIs of this application a client can create and initiate the purchase orders and can track the state of these purchases.  Using *Swagger Editor* you could directly call the PPG APIs and also could auto-generate a client for PPG APIs in your preferred programming language.  The base URL of PPG is: `https://napi.jibit.ir/ppg`  Full documentation is available on: https://napi.jibit.ir/ppg/v3/static/docs/index.html

API version: 3.2.48
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ppg

import (
	"encoding/json"
)

// checks if the PspFailReason type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PspFailReason{}

// PspFailReason struct for PspFailReason
type PspFailReason struct {
	Code *int32 `json:"code,omitempty"`
	Description *string `json:"description,omitempty"`
	// Deprecated
	PspError *string `json:"pspError,omitempty"`
}

// NewPspFailReason instantiates a new PspFailReason object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPspFailReason() *PspFailReason {
	this := PspFailReason{}
	return &this
}

// NewPspFailReasonWithDefaults instantiates a new PspFailReason object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPspFailReasonWithDefaults() *PspFailReason {
	this := PspFailReason{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *PspFailReason) GetCode() int32 {
	if o == nil || IsNil(o.Code) {
		var ret int32
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PspFailReason) GetCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *PspFailReason) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given int32 and assigns it to the Code field.
func (o *PspFailReason) SetCode(v int32) {
	o.Code = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *PspFailReason) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PspFailReason) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *PspFailReason) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *PspFailReason) SetDescription(v string) {
	o.Description = &v
}

// GetPspError returns the PspError field value if set, zero value otherwise.
// Deprecated
func (o *PspFailReason) GetPspError() string {
	if o == nil || IsNil(o.PspError) {
		var ret string
		return ret
	}
	return *o.PspError
}

// GetPspErrorOk returns a tuple with the PspError field value if set, nil otherwise
// and a boolean to check if the value has been set.
// Deprecated
func (o *PspFailReason) GetPspErrorOk() (*string, bool) {
	if o == nil || IsNil(o.PspError) {
		return nil, false
	}
	return o.PspError, true
}

// HasPspError returns a boolean if a field has been set.
func (o *PspFailReason) HasPspError() bool {
	if o != nil && !IsNil(o.PspError) {
		return true
	}

	return false
}

// SetPspError gets a reference to the given string and assigns it to the PspError field.
// Deprecated
func (o *PspFailReason) SetPspError(v string) {
	o.PspError = &v
}

func (o PspFailReason) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PspFailReason) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.PspError) {
		toSerialize["pspError"] = o.PspError
	}
	return toSerialize, nil
}

type NullablePspFailReason struct {
	value *PspFailReason
	isSet bool
}

func (v NullablePspFailReason) Get() *PspFailReason {
	return v.value
}

func (v *NullablePspFailReason) Set(val *PspFailReason) {
	v.value = val
	v.isSet = true
}

func (v NullablePspFailReason) IsSet() bool {
	return v.isSet
}

func (v *NullablePspFailReason) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePspFailReason(val *PspFailReason) *NullablePspFailReason {
	return &NullablePspFailReason{value: val, isSet: true}
}

func (v NullablePspFailReason) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePspFailReason) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


