/*
PPG: Proxy Payment Gateway

PPG is the Proxy Payment Gateway of Jibit corporation. It lets the users of 3rd-party clients (merchants, banks, organizations, ...) to purchase goodies from them using PPG as a transparent payment gateway. In back-end the user will be redirected to a PSP payment gateway (for example Saman) to pay the price of the purchase.  Using APIs of this application a client can create and initiate the purchase orders and can track the state of these purchases.  Using *Swagger Editor* you could directly call the PPG APIs and also could auto-generate a client for PPG APIs in your preferred programming language.  The base URL of PPG is: `https://napi.jibit.ir/ppg`  Full documentation is available on: https://napi.jibit.ir/ppg/v3/static/docs/index.html

API version: 3.2.48
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package jibit-ppg

import (
	"encoding/json"
)

// checks if the TokenDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TokenDto{}

// TokenDto The dto encapsulating the newly generated access and refresh tokens.
type TokenDto struct {
	// Represents the new access token.
	AccessToken *string `json:"accessToken,omitempty"`
	// Represents the new refresh token.
	RefreshToken *string `json:"refreshToken,omitempty"`
}

// NewTokenDto instantiates a new TokenDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokenDto() *TokenDto {
	this := TokenDto{}
	return &this
}

// NewTokenDtoWithDefaults instantiates a new TokenDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenDtoWithDefaults() *TokenDto {
	this := TokenDto{}
	return &this
}

// GetAccessToken returns the AccessToken field value if set, zero value otherwise.
func (o *TokenDto) GetAccessToken() string {
	if o == nil || IsNil(o.AccessToken) {
		var ret string
		return ret
	}
	return *o.AccessToken
}

// GetAccessTokenOk returns a tuple with the AccessToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenDto) GetAccessTokenOk() (*string, bool) {
	if o == nil || IsNil(o.AccessToken) {
		return nil, false
	}
	return o.AccessToken, true
}

// HasAccessToken returns a boolean if a field has been set.
func (o *TokenDto) HasAccessToken() bool {
	if o != nil && !IsNil(o.AccessToken) {
		return true
	}

	return false
}

// SetAccessToken gets a reference to the given string and assigns it to the AccessToken field.
func (o *TokenDto) SetAccessToken(v string) {
	o.AccessToken = &v
}

// GetRefreshToken returns the RefreshToken field value if set, zero value otherwise.
func (o *TokenDto) GetRefreshToken() string {
	if o == nil || IsNil(o.RefreshToken) {
		var ret string
		return ret
	}
	return *o.RefreshToken
}

// GetRefreshTokenOk returns a tuple with the RefreshToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenDto) GetRefreshTokenOk() (*string, bool) {
	if o == nil || IsNil(o.RefreshToken) {
		return nil, false
	}
	return o.RefreshToken, true
}

// HasRefreshToken returns a boolean if a field has been set.
func (o *TokenDto) HasRefreshToken() bool {
	if o != nil && !IsNil(o.RefreshToken) {
		return true
	}

	return false
}

// SetRefreshToken gets a reference to the given string and assigns it to the RefreshToken field.
func (o *TokenDto) SetRefreshToken(v string) {
	o.RefreshToken = &v
}

func (o TokenDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TokenDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccessToken) {
		toSerialize["accessToken"] = o.AccessToken
	}
	if !IsNil(o.RefreshToken) {
		toSerialize["refreshToken"] = o.RefreshToken
	}
	return toSerialize, nil
}

type NullableTokenDto struct {
	value *TokenDto
	isSet bool
}

func (v NullableTokenDto) Get() *TokenDto {
	return v.value
}

func (v *NullableTokenDto) Set(val *TokenDto) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenDto) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenDto(val *TokenDto) *NullableTokenDto {
	return &NullableTokenDto{value: val, isSet: true}
}

func (v NullableTokenDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


