/*
PPG: Proxy Payment Gateway

PPG is the Proxy Payment Gateway of Jibit corporation. It lets the users of 3rd-party clients (merchants, banks, organizations, ...) to purchase goodies from them using PPG as a transparent payment gateway. In back-end the user will be redirected to a PSP payment gateway (for example Saman) to pay the price of the purchase.  Using APIs of this application a client can create and initiate the purchase orders and can track the state of these purchases.  Using *Swagger Editor* you could directly call the PPG APIs and also could auto-generate a client for PPG APIs in your preferred programming language.  The base URL of PPG is: `https://napi.jibit.ir/ppg`  Full documentation is available on: https://napi.jibit.ir/ppg/v3/static/docs/index.html

API version: 3.2.48
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ppg

import (
	"encoding/json"
)

// checks if the RefundActionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RefundActionRequest{}

// RefundActionRequest Encapsulated the information required to do an action on a (partial) refund.
type RefundActionRequest struct {
	// This is the unique identifier of a partial refund.  * If there is only one refund in the batch, you do not need to specify `transferId`.  * If there are multiple refunds in the batch: You must specify `transferId` to indicate the position of the partial refund.
	TransferId *string `json:"transferId,omitempty"`
}

// NewRefundActionRequest instantiates a new RefundActionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRefundActionRequest() *RefundActionRequest {
	this := RefundActionRequest{}
	return &this
}

// NewRefundActionRequestWithDefaults instantiates a new RefundActionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRefundActionRequestWithDefaults() *RefundActionRequest {
	this := RefundActionRequest{}
	return &this
}

// GetTransferId returns the TransferId field value if set, zero value otherwise.
func (o *RefundActionRequest) GetTransferId() string {
	if o == nil || IsNil(o.TransferId) {
		var ret string
		return ret
	}
	return *o.TransferId
}

// GetTransferIdOk returns a tuple with the TransferId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RefundActionRequest) GetTransferIdOk() (*string, bool) {
	if o == nil || IsNil(o.TransferId) {
		return nil, false
	}
	return o.TransferId, true
}

// HasTransferId returns a boolean if a field has been set.
func (o *RefundActionRequest) HasTransferId() bool {
	if o != nil && !IsNil(o.TransferId) {
		return true
	}

	return false
}

// SetTransferId gets a reference to the given string and assigns it to the TransferId field.
func (o *RefundActionRequest) SetTransferId(v string) {
	o.TransferId = &v
}

func (o RefundActionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RefundActionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TransferId) {
		toSerialize["transferId"] = o.TransferId
	}
	return toSerialize, nil
}

type NullableRefundActionRequest struct {
	value *RefundActionRequest
	isSet bool
}

func (v NullableRefundActionRequest) Get() *RefundActionRequest {
	return v.value
}

func (v *NullableRefundActionRequest) Set(val *RefundActionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRefundActionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRefundActionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRefundActionRequest(val *RefundActionRequest) *NullableRefundActionRequest {
	return &NullableRefundActionRequest{value: val, isSet: true}
}

func (v NullableRefundActionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRefundActionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


