/*
PPG: Proxy Payment Gateway

PPG is the Proxy Payment Gateway of Jibit corporation. It lets the users of 3rd-party clients (merchants, banks, organizations, ...) to purchase goodies from them using PPG as a transparent payment gateway. In back-end the user will be redirected to a PSP payment gateway (for example Saman) to pay the price of the purchase.  Using APIs of this application a client can create and initiate the purchase orders and can track the state of these purchases.  Using *Swagger Editor* you could directly call the PPG APIs and also could auto-generate a client for PPG APIs in your preferred programming language.  The base URL of PPG is: `https://napi.jibit.ir/ppg`  Full documentation is available on: https://napi.jibit.ir/ppg/v3/static/docs/index.html

API version: 3.2.48
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package jibit-ppg

import (
	"encoding/json"
)

// checks if the HealthDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HealthDto{}

// HealthDto Represents the health status of the service.
type HealthDto struct {
	// The current health status of the service.                      UP if the service is operational, or DOWN if it is not.
	Status *string `json:"status,omitempty"`
	// A map containing the health status of various PSP vendors.
	PspStatusMap *map[string]string `json:"pspStatusMap,omitempty"`
}

// NewHealthDto instantiates a new HealthDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHealthDto() *HealthDto {
	this := HealthDto{}
	return &this
}

// NewHealthDtoWithDefaults instantiates a new HealthDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHealthDtoWithDefaults() *HealthDto {
	this := HealthDto{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *HealthDto) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HealthDto) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *HealthDto) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *HealthDto) SetStatus(v string) {
	o.Status = &v
}

// GetPspStatusMap returns the PspStatusMap field value if set, zero value otherwise.
func (o *HealthDto) GetPspStatusMap() map[string]string {
	if o == nil || IsNil(o.PspStatusMap) {
		var ret map[string]string
		return ret
	}
	return *o.PspStatusMap
}

// GetPspStatusMapOk returns a tuple with the PspStatusMap field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HealthDto) GetPspStatusMapOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.PspStatusMap) {
		return nil, false
	}
	return o.PspStatusMap, true
}

// HasPspStatusMap returns a boolean if a field has been set.
func (o *HealthDto) HasPspStatusMap() bool {
	if o != nil && !IsNil(o.PspStatusMap) {
		return true
	}

	return false
}

// SetPspStatusMap gets a reference to the given map[string]string and assigns it to the PspStatusMap field.
func (o *HealthDto) SetPspStatusMap(v map[string]string) {
	o.PspStatusMap = &v
}

func (o HealthDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HealthDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.PspStatusMap) {
		toSerialize["pspStatusMap"] = o.PspStatusMap
	}
	return toSerialize, nil
}

type NullableHealthDto struct {
	value *HealthDto
	isSet bool
}

func (v NullableHealthDto) Get() *HealthDto {
	return v.value
}

func (v *NullableHealthDto) Set(val *HealthDto) {
	v.value = val
	v.isSet = true
}

func (v NullableHealthDto) IsSet() bool {
	return v.isSet
}

func (v *NullableHealthDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHealthDto(val *HealthDto) *NullableHealthDto {
	return &NullableHealthDto{value: val, isSet: true}
}

func (v NullableHealthDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHealthDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


