/*
PPG: Proxy Payment Gateway

PPG is the Proxy Payment Gateway of Jibit corporation. It lets the users of 3rd-party clients (merchants, banks, organizations, ...) to purchase goodies from them using PPG as a transparent payment gateway. In back-end the user will be redirected to a PSP payment gateway (for example Saman) to pay the price of the purchase.  Using APIs of this application a client can create and initiate the purchase orders and can track the state of these purchases.  Using *Swagger Editor* you could directly call the PPG APIs and also could auto-generate a client for PPG APIs in your preferred programming language.  The base URL of PPG is: `https://napi.jibit.ir/ppg`  Full documentation is available on: https://napi.jibit.ir/ppg/v3/static/docs/index.html

API version: 3.2.48
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package jibit-ppg

import (
	"encoding/json"
	"time"
)

// checks if the PurchaseHistoryFilterCriteria type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PurchaseHistoryFilterCriteria{}

// PurchaseHistoryFilterCriteria Encapsulates the criteria for querying purchase history within a specified date range.  Supports pagination via `nextPageId` for faster loading, and optional page/size parameters.  <p>  Example Usage:  from: `2024-10-15T13:00:00Z`  to:   `2024-10-15T14:00:00Z`
type PurchaseHistoryFilterCriteria struct {
	// The start of the date range (inclusive) for querying purchase history.
	From *time.Time `json:"from,omitempty"`
	// The end of the date range (exclusive) for querying purchase history.
	To *time.Time `json:"to,omitempty"`
	// Represents the unique identifier for a purchase.  This field is used to filter purchase history records  based on a specific purchase.
	PurchaseId *int64 `json:"purchaseId,omitempty"`
	// A list representing the statuses of a purchase history.  Each state corresponds to a different status of the purchase,  such as manually successful, reversed, or unknown.
	Statuses []string `json:"statuses,omitempty"`
	// The identifier for fetching the next page of results.  Using `nextPageId` allows faster pagination than a page number parameter.  If provided, the `page` parameter will be ignored.
	NextPageId *int64 `json:"nextPageId,omitempty"`
	// The page number to fetch (1-indexed). If null, it means the first page.  Note: The max page number is 10. Use `nextPageId` for faster results.  If `nextPageId` is provided, this field is ignored.
	Page *int32 `json:"page,omitempty"`
	// The number of results per page. If null, the default size will be used.  The default page size is 10,000, and the maximum allowed size is 20,000.
	Size *int32 `json:"size,omitempty"`
}

// NewPurchaseHistoryFilterCriteria instantiates a new PurchaseHistoryFilterCriteria object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPurchaseHistoryFilterCriteria() *PurchaseHistoryFilterCriteria {
	this := PurchaseHistoryFilterCriteria{}
	return &this
}

// NewPurchaseHistoryFilterCriteriaWithDefaults instantiates a new PurchaseHistoryFilterCriteria object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPurchaseHistoryFilterCriteriaWithDefaults() *PurchaseHistoryFilterCriteria {
	this := PurchaseHistoryFilterCriteria{}
	return &this
}

// GetFrom returns the From field value if set, zero value otherwise.
func (o *PurchaseHistoryFilterCriteria) GetFrom() time.Time {
	if o == nil || IsNil(o.From) {
		var ret time.Time
		return ret
	}
	return *o.From
}

// GetFromOk returns a tuple with the From field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurchaseHistoryFilterCriteria) GetFromOk() (*time.Time, bool) {
	if o == nil || IsNil(o.From) {
		return nil, false
	}
	return o.From, true
}

// HasFrom returns a boolean if a field has been set.
func (o *PurchaseHistoryFilterCriteria) HasFrom() bool {
	if o != nil && !IsNil(o.From) {
		return true
	}

	return false
}

// SetFrom gets a reference to the given time.Time and assigns it to the From field.
func (o *PurchaseHistoryFilterCriteria) SetFrom(v time.Time) {
	o.From = &v
}

// GetTo returns the To field value if set, zero value otherwise.
func (o *PurchaseHistoryFilterCriteria) GetTo() time.Time {
	if o == nil || IsNil(o.To) {
		var ret time.Time
		return ret
	}
	return *o.To
}

// GetToOk returns a tuple with the To field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurchaseHistoryFilterCriteria) GetToOk() (*time.Time, bool) {
	if o == nil || IsNil(o.To) {
		return nil, false
	}
	return o.To, true
}

// HasTo returns a boolean if a field has been set.
func (o *PurchaseHistoryFilterCriteria) HasTo() bool {
	if o != nil && !IsNil(o.To) {
		return true
	}

	return false
}

// SetTo gets a reference to the given time.Time and assigns it to the To field.
func (o *PurchaseHistoryFilterCriteria) SetTo(v time.Time) {
	o.To = &v
}

// GetPurchaseId returns the PurchaseId field value if set, zero value otherwise.
func (o *PurchaseHistoryFilterCriteria) GetPurchaseId() int64 {
	if o == nil || IsNil(o.PurchaseId) {
		var ret int64
		return ret
	}
	return *o.PurchaseId
}

// GetPurchaseIdOk returns a tuple with the PurchaseId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurchaseHistoryFilterCriteria) GetPurchaseIdOk() (*int64, bool) {
	if o == nil || IsNil(o.PurchaseId) {
		return nil, false
	}
	return o.PurchaseId, true
}

// HasPurchaseId returns a boolean if a field has been set.
func (o *PurchaseHistoryFilterCriteria) HasPurchaseId() bool {
	if o != nil && !IsNil(o.PurchaseId) {
		return true
	}

	return false
}

// SetPurchaseId gets a reference to the given int64 and assigns it to the PurchaseId field.
func (o *PurchaseHistoryFilterCriteria) SetPurchaseId(v int64) {
	o.PurchaseId = &v
}

// GetStatuses returns the Statuses field value if set, zero value otherwise.
func (o *PurchaseHistoryFilterCriteria) GetStatuses() []string {
	if o == nil || IsNil(o.Statuses) {
		var ret []string
		return ret
	}
	return o.Statuses
}

// GetStatusesOk returns a tuple with the Statuses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurchaseHistoryFilterCriteria) GetStatusesOk() ([]string, bool) {
	if o == nil || IsNil(o.Statuses) {
		return nil, false
	}
	return o.Statuses, true
}

// HasStatuses returns a boolean if a field has been set.
func (o *PurchaseHistoryFilterCriteria) HasStatuses() bool {
	if o != nil && !IsNil(o.Statuses) {
		return true
	}

	return false
}

// SetStatuses gets a reference to the given []string and assigns it to the Statuses field.
func (o *PurchaseHistoryFilterCriteria) SetStatuses(v []string) {
	o.Statuses = v
}

// GetNextPageId returns the NextPageId field value if set, zero value otherwise.
func (o *PurchaseHistoryFilterCriteria) GetNextPageId() int64 {
	if o == nil || IsNil(o.NextPageId) {
		var ret int64
		return ret
	}
	return *o.NextPageId
}

// GetNextPageIdOk returns a tuple with the NextPageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurchaseHistoryFilterCriteria) GetNextPageIdOk() (*int64, bool) {
	if o == nil || IsNil(o.NextPageId) {
		return nil, false
	}
	return o.NextPageId, true
}

// HasNextPageId returns a boolean if a field has been set.
func (o *PurchaseHistoryFilterCriteria) HasNextPageId() bool {
	if o != nil && !IsNil(o.NextPageId) {
		return true
	}

	return false
}

// SetNextPageId gets a reference to the given int64 and assigns it to the NextPageId field.
func (o *PurchaseHistoryFilterCriteria) SetNextPageId(v int64) {
	o.NextPageId = &v
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *PurchaseHistoryFilterCriteria) GetPage() int32 {
	if o == nil || IsNil(o.Page) {
		var ret int32
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurchaseHistoryFilterCriteria) GetPageOk() (*int32, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *PurchaseHistoryFilterCriteria) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given int32 and assigns it to the Page field.
func (o *PurchaseHistoryFilterCriteria) SetPage(v int32) {
	o.Page = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *PurchaseHistoryFilterCriteria) GetSize() int32 {
	if o == nil || IsNil(o.Size) {
		var ret int32
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurchaseHistoryFilterCriteria) GetSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *PurchaseHistoryFilterCriteria) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given int32 and assigns it to the Size field.
func (o *PurchaseHistoryFilterCriteria) SetSize(v int32) {
	o.Size = &v
}

func (o PurchaseHistoryFilterCriteria) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PurchaseHistoryFilterCriteria) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.From) {
		toSerialize["from"] = o.From
	}
	if !IsNil(o.To) {
		toSerialize["to"] = o.To
	}
	if !IsNil(o.PurchaseId) {
		toSerialize["purchaseId"] = o.PurchaseId
	}
	if !IsNil(o.Statuses) {
		toSerialize["statuses"] = o.Statuses
	}
	if !IsNil(o.NextPageId) {
		toSerialize["nextPageId"] = o.NextPageId
	}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	return toSerialize, nil
}

type NullablePurchaseHistoryFilterCriteria struct {
	value *PurchaseHistoryFilterCriteria
	isSet bool
}

func (v NullablePurchaseHistoryFilterCriteria) Get() *PurchaseHistoryFilterCriteria {
	return v.value
}

func (v *NullablePurchaseHistoryFilterCriteria) Set(val *PurchaseHistoryFilterCriteria) {
	v.value = val
	v.isSet = true
}

func (v NullablePurchaseHistoryFilterCriteria) IsSet() bool {
	return v.isSet
}

func (v *NullablePurchaseHistoryFilterCriteria) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePurchaseHistoryFilterCriteria(val *PurchaseHistoryFilterCriteria) *NullablePurchaseHistoryFilterCriteria {
	return &NullablePurchaseHistoryFilterCriteria{value: val, isSet: true}
}

func (v NullablePurchaseHistoryFilterCriteria) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePurchaseHistoryFilterCriteria) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


