/*
PPG: Proxy Payment Gateway

PPG is the Proxy Payment Gateway of Jibit corporation. It lets the users of 3rd-party clients (merchants, banks, organizations, ...) to purchase goodies from them using PPG as a transparent payment gateway. In back-end the user will be redirected to a PSP payment gateway (for example Saman) to pay the price of the purchase.  Using APIs of this application a client can create and initiate the purchase orders and can track the state of these purchases.  Using *Swagger Editor* you could directly call the PPG APIs and also could auto-generate a client for PPG APIs in your preferred programming language.  The base URL of PPG is: `https://napi.jibit.ir/ppg`  Full documentation is available on: https://napi.jibit.ir/ppg/v3/static/docs/index.html

API version: 3.2.48
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ppg

import (
	"encoding/json"
)

// checks if the CollectionResponseTerminalDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CollectionResponseTerminalDto{}

// CollectionResponseTerminalDto A wrapper for the collection responses.
type CollectionResponseTerminalDto struct {
	// Represents the actual data.
	Elements []TerminalDto `json:"elements,omitempty"`
}

// NewCollectionResponseTerminalDto instantiates a new CollectionResponseTerminalDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCollectionResponseTerminalDto() *CollectionResponseTerminalDto {
	this := CollectionResponseTerminalDto{}
	return &this
}

// NewCollectionResponseTerminalDtoWithDefaults instantiates a new CollectionResponseTerminalDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCollectionResponseTerminalDtoWithDefaults() *CollectionResponseTerminalDto {
	this := CollectionResponseTerminalDto{}
	return &this
}

// GetElements returns the Elements field value if set, zero value otherwise.
func (o *CollectionResponseTerminalDto) GetElements() []TerminalDto {
	if o == nil || IsNil(o.Elements) {
		var ret []TerminalDto
		return ret
	}
	return o.Elements
}

// GetElementsOk returns a tuple with the Elements field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CollectionResponseTerminalDto) GetElementsOk() ([]TerminalDto, bool) {
	if o == nil || IsNil(o.Elements) {
		return nil, false
	}
	return o.Elements, true
}

// HasElements returns a boolean if a field has been set.
func (o *CollectionResponseTerminalDto) HasElements() bool {
	if o != nil && !IsNil(o.Elements) {
		return true
	}

	return false
}

// SetElements gets a reference to the given []TerminalDto and assigns it to the Elements field.
func (o *CollectionResponseTerminalDto) SetElements(v []TerminalDto) {
	o.Elements = v
}

func (o CollectionResponseTerminalDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CollectionResponseTerminalDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Elements) {
		toSerialize["elements"] = o.Elements
	}
	return toSerialize, nil
}

type NullableCollectionResponseTerminalDto struct {
	value *CollectionResponseTerminalDto
	isSet bool
}

func (v NullableCollectionResponseTerminalDto) Get() *CollectionResponseTerminalDto {
	return v.value
}

func (v *NullableCollectionResponseTerminalDto) Set(val *CollectionResponseTerminalDto) {
	v.value = val
	v.isSet = true
}

func (v NullableCollectionResponseTerminalDto) IsSet() bool {
	return v.isSet
}

func (v *NullableCollectionResponseTerminalDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCollectionResponseTerminalDto(val *CollectionResponseTerminalDto) *NullableCollectionResponseTerminalDto {
	return &NullableCollectionResponseTerminalDto{value: val, isSet: true}
}

func (v NullableCollectionResponseTerminalDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCollectionResponseTerminalDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


