/*
PPG: Proxy Payment Gateway

PPG is the Proxy Payment Gateway of Jibit corporation. It lets the users of 3rd-party clients (merchants, banks, organizations, ...) to purchase goodies from them using PPG as a transparent payment gateway. In back-end the user will be redirected to a PSP payment gateway (for example Saman) to pay the price of the purchase.  Using APIs of this application a client can create and initiate the purchase orders and can track the state of these purchases.  Using *Swagger Editor* you could directly call the PPG APIs and also could auto-generate a client for PPG APIs in your preferred programming language.  The base URL of PPG is: `https://napi.jibit.ir/ppg`  Full documentation is available on: https://napi.jibit.ir/ppg/v3/static/docs/index.html

API version: 3.2.48
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package jibit-ppg

import (
	"encoding/json"
)

// checks if the CreatePurchaseRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreatePurchaseRequest{}

// CreatePurchaseRequest Encapsulates the information required to create a purchase.
type CreatePurchaseRequest struct {
	// Represents the amount of purchase.
	Amount *int64 `json:"amount,omitempty"`
	// Represents the wage of purchase.  The user will pay the `amount` + `wage`.  The Default value is 0.  <b>This field can not be bigger that 15 % of the `amount` value.</b>
	Wage *int64 `json:"wage,omitempty"`
	// Represents the currency of `amount` and `wage`.
	Currency *string `json:"currency,omitempty"`
	// Represents a reference number provided by client to trace purchase in our system.  The reference number between client purchases must be unique. We will check this on our side.  The maximum length is 50 characters.
	ClientReferenceNumber *string `json:"clientReferenceNumber,omitempty"`
	// Represents the mobile number of the payer. It will be sent to Psp to autocomplete the payment fields.
	PayerMobileNumber *string `json:"payerMobileNumber,omitempty"`
	// If this flag is set to true, the payment must be paid only by a card which belongs to the owner of the phone number;  Otherwise the purchase will fail. Optional.  ** This feature is not enabled by default on certain PSPs and must be enabled by admin.  If Client uses this feature when it is not enabled, PPG simply ignores it and creates the purchase as normal. **  Note: If this flag is set to true, `payerMobileNumber` field cannot be null or else you will get an error.
	CheckPayerMobileNumber *bool `json:"checkPayerMobileNumber,omitempty"`
	// Bank card number which is required to do the transaction.  Only this card number can be used to do the transaction. Optional.  ** This feature is not enabled by default on certain PSPs and must be enabled by admin.  If Client uses this feature when it is not enabled, PPG simply ignores it and creates the purchase as normal. **
	PayerCardNumber *string `json:"payerCardNumber,omitempty"`
	// Bank card numbers which are required to do the transaction.  Only these card numbers can be used to do the transaction. Optional.  ** This feature is not enabled by default on certain PSPs and must be enabled by admin.  If Client uses this feature when it is not enabled, PPG simply ignores it and creates the purchase as normal. **
	PayerCardNumbers []string `json:"payerCardNumbers,omitempty"`
	// Represents the national code of card owner.  If provided, this Field will be matched with the national code of card owner in the IPG,  and if they don't match, the transaction will fail. Optional.  ** This feature is not enabled by default and must be enabled by admin.  If Client uses this feature when it is not enabled, PPG simply ignores it and creates the purchase as normal. **
	PayerNationalCode *string `json:"payerNationalCode,omitempty"`
	// Represents the client-provided description. Optional.  The Maximum length is 256 characters.
	Description *string `json:"description,omitempty"`
	Switching *TerminalSwitchingDto `json:"switching,omitempty"`
	// Represents the additional data provided by client in JSON format. Optional.
	AdditionalData map[string]interface{} `json:"additionalData,omitempty"`
	// Represents a callback which we should call in order to notify the client about a particular purchase state.  For example, when the user pays the purchase, we would redirect the user to this callback and let the client know about  the payment. This must be a valid URL address. Maximum length is 1024 characters.
	CallbackUrl *string `json:"callbackUrl,omitempty"`
	// Represents the user identifier in the client system.  Maximum length is 50 characters.
	UserIdentifier *string `json:"userIdentifier,omitempty"`
}

// NewCreatePurchaseRequest instantiates a new CreatePurchaseRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatePurchaseRequest() *CreatePurchaseRequest {
	this := CreatePurchaseRequest{}
	return &this
}

// NewCreatePurchaseRequestWithDefaults instantiates a new CreatePurchaseRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatePurchaseRequestWithDefaults() *CreatePurchaseRequest {
	this := CreatePurchaseRequest{}
	return &this
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *CreatePurchaseRequest) GetAmount() int64 {
	if o == nil || IsNil(o.Amount) {
		var ret int64
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePurchaseRequest) GetAmountOk() (*int64, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *CreatePurchaseRequest) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given int64 and assigns it to the Amount field.
func (o *CreatePurchaseRequest) SetAmount(v int64) {
	o.Amount = &v
}

// GetWage returns the Wage field value if set, zero value otherwise.
func (o *CreatePurchaseRequest) GetWage() int64 {
	if o == nil || IsNil(o.Wage) {
		var ret int64
		return ret
	}
	return *o.Wage
}

// GetWageOk returns a tuple with the Wage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePurchaseRequest) GetWageOk() (*int64, bool) {
	if o == nil || IsNil(o.Wage) {
		return nil, false
	}
	return o.Wage, true
}

// HasWage returns a boolean if a field has been set.
func (o *CreatePurchaseRequest) HasWage() bool {
	if o != nil && !IsNil(o.Wage) {
		return true
	}

	return false
}

// SetWage gets a reference to the given int64 and assigns it to the Wage field.
func (o *CreatePurchaseRequest) SetWage(v int64) {
	o.Wage = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *CreatePurchaseRequest) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePurchaseRequest) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *CreatePurchaseRequest) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *CreatePurchaseRequest) SetCurrency(v string) {
	o.Currency = &v
}

// GetClientReferenceNumber returns the ClientReferenceNumber field value if set, zero value otherwise.
func (o *CreatePurchaseRequest) GetClientReferenceNumber() string {
	if o == nil || IsNil(o.ClientReferenceNumber) {
		var ret string
		return ret
	}
	return *o.ClientReferenceNumber
}

// GetClientReferenceNumberOk returns a tuple with the ClientReferenceNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePurchaseRequest) GetClientReferenceNumberOk() (*string, bool) {
	if o == nil || IsNil(o.ClientReferenceNumber) {
		return nil, false
	}
	return o.ClientReferenceNumber, true
}

// HasClientReferenceNumber returns a boolean if a field has been set.
func (o *CreatePurchaseRequest) HasClientReferenceNumber() bool {
	if o != nil && !IsNil(o.ClientReferenceNumber) {
		return true
	}

	return false
}

// SetClientReferenceNumber gets a reference to the given string and assigns it to the ClientReferenceNumber field.
func (o *CreatePurchaseRequest) SetClientReferenceNumber(v string) {
	o.ClientReferenceNumber = &v
}

// GetPayerMobileNumber returns the PayerMobileNumber field value if set, zero value otherwise.
func (o *CreatePurchaseRequest) GetPayerMobileNumber() string {
	if o == nil || IsNil(o.PayerMobileNumber) {
		var ret string
		return ret
	}
	return *o.PayerMobileNumber
}

// GetPayerMobileNumberOk returns a tuple with the PayerMobileNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePurchaseRequest) GetPayerMobileNumberOk() (*string, bool) {
	if o == nil || IsNil(o.PayerMobileNumber) {
		return nil, false
	}
	return o.PayerMobileNumber, true
}

// HasPayerMobileNumber returns a boolean if a field has been set.
func (o *CreatePurchaseRequest) HasPayerMobileNumber() bool {
	if o != nil && !IsNil(o.PayerMobileNumber) {
		return true
	}

	return false
}

// SetPayerMobileNumber gets a reference to the given string and assigns it to the PayerMobileNumber field.
func (o *CreatePurchaseRequest) SetPayerMobileNumber(v string) {
	o.PayerMobileNumber = &v
}

// GetCheckPayerMobileNumber returns the CheckPayerMobileNumber field value if set, zero value otherwise.
func (o *CreatePurchaseRequest) GetCheckPayerMobileNumber() bool {
	if o == nil || IsNil(o.CheckPayerMobileNumber) {
		var ret bool
		return ret
	}
	return *o.CheckPayerMobileNumber
}

// GetCheckPayerMobileNumberOk returns a tuple with the CheckPayerMobileNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePurchaseRequest) GetCheckPayerMobileNumberOk() (*bool, bool) {
	if o == nil || IsNil(o.CheckPayerMobileNumber) {
		return nil, false
	}
	return o.CheckPayerMobileNumber, true
}

// HasCheckPayerMobileNumber returns a boolean if a field has been set.
func (o *CreatePurchaseRequest) HasCheckPayerMobileNumber() bool {
	if o != nil && !IsNil(o.CheckPayerMobileNumber) {
		return true
	}

	return false
}

// SetCheckPayerMobileNumber gets a reference to the given bool and assigns it to the CheckPayerMobileNumber field.
func (o *CreatePurchaseRequest) SetCheckPayerMobileNumber(v bool) {
	o.CheckPayerMobileNumber = &v
}

// GetPayerCardNumber returns the PayerCardNumber field value if set, zero value otherwise.
func (o *CreatePurchaseRequest) GetPayerCardNumber() string {
	if o == nil || IsNil(o.PayerCardNumber) {
		var ret string
		return ret
	}
	return *o.PayerCardNumber
}

// GetPayerCardNumberOk returns a tuple with the PayerCardNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePurchaseRequest) GetPayerCardNumberOk() (*string, bool) {
	if o == nil || IsNil(o.PayerCardNumber) {
		return nil, false
	}
	return o.PayerCardNumber, true
}

// HasPayerCardNumber returns a boolean if a field has been set.
func (o *CreatePurchaseRequest) HasPayerCardNumber() bool {
	if o != nil && !IsNil(o.PayerCardNumber) {
		return true
	}

	return false
}

// SetPayerCardNumber gets a reference to the given string and assigns it to the PayerCardNumber field.
func (o *CreatePurchaseRequest) SetPayerCardNumber(v string) {
	o.PayerCardNumber = &v
}

// GetPayerCardNumbers returns the PayerCardNumbers field value if set, zero value otherwise.
func (o *CreatePurchaseRequest) GetPayerCardNumbers() []string {
	if o == nil || IsNil(o.PayerCardNumbers) {
		var ret []string
		return ret
	}
	return o.PayerCardNumbers
}

// GetPayerCardNumbersOk returns a tuple with the PayerCardNumbers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePurchaseRequest) GetPayerCardNumbersOk() ([]string, bool) {
	if o == nil || IsNil(o.PayerCardNumbers) {
		return nil, false
	}
	return o.PayerCardNumbers, true
}

// HasPayerCardNumbers returns a boolean if a field has been set.
func (o *CreatePurchaseRequest) HasPayerCardNumbers() bool {
	if o != nil && !IsNil(o.PayerCardNumbers) {
		return true
	}

	return false
}

// SetPayerCardNumbers gets a reference to the given []string and assigns it to the PayerCardNumbers field.
func (o *CreatePurchaseRequest) SetPayerCardNumbers(v []string) {
	o.PayerCardNumbers = v
}

// GetPayerNationalCode returns the PayerNationalCode field value if set, zero value otherwise.
func (o *CreatePurchaseRequest) GetPayerNationalCode() string {
	if o == nil || IsNil(o.PayerNationalCode) {
		var ret string
		return ret
	}
	return *o.PayerNationalCode
}

// GetPayerNationalCodeOk returns a tuple with the PayerNationalCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePurchaseRequest) GetPayerNationalCodeOk() (*string, bool) {
	if o == nil || IsNil(o.PayerNationalCode) {
		return nil, false
	}
	return o.PayerNationalCode, true
}

// HasPayerNationalCode returns a boolean if a field has been set.
func (o *CreatePurchaseRequest) HasPayerNationalCode() bool {
	if o != nil && !IsNil(o.PayerNationalCode) {
		return true
	}

	return false
}

// SetPayerNationalCode gets a reference to the given string and assigns it to the PayerNationalCode field.
func (o *CreatePurchaseRequest) SetPayerNationalCode(v string) {
	o.PayerNationalCode = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreatePurchaseRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePurchaseRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreatePurchaseRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreatePurchaseRequest) SetDescription(v string) {
	o.Description = &v
}

// GetSwitching returns the Switching field value if set, zero value otherwise.
func (o *CreatePurchaseRequest) GetSwitching() TerminalSwitchingDto {
	if o == nil || IsNil(o.Switching) {
		var ret TerminalSwitchingDto
		return ret
	}
	return *o.Switching
}

// GetSwitchingOk returns a tuple with the Switching field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePurchaseRequest) GetSwitchingOk() (*TerminalSwitchingDto, bool) {
	if o == nil || IsNil(o.Switching) {
		return nil, false
	}
	return o.Switching, true
}

// HasSwitching returns a boolean if a field has been set.
func (o *CreatePurchaseRequest) HasSwitching() bool {
	if o != nil && !IsNil(o.Switching) {
		return true
	}

	return false
}

// SetSwitching gets a reference to the given TerminalSwitchingDto and assigns it to the Switching field.
func (o *CreatePurchaseRequest) SetSwitching(v TerminalSwitchingDto) {
	o.Switching = &v
}

// GetAdditionalData returns the AdditionalData field value if set, zero value otherwise.
func (o *CreatePurchaseRequest) GetAdditionalData() map[string]interface{} {
	if o == nil || IsNil(o.AdditionalData) {
		var ret map[string]interface{}
		return ret
	}
	return o.AdditionalData
}

// GetAdditionalDataOk returns a tuple with the AdditionalData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePurchaseRequest) GetAdditionalDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.AdditionalData) {
		return map[string]interface{}{}, false
	}
	return o.AdditionalData, true
}

// HasAdditionalData returns a boolean if a field has been set.
func (o *CreatePurchaseRequest) HasAdditionalData() bool {
	if o != nil && !IsNil(o.AdditionalData) {
		return true
	}

	return false
}

// SetAdditionalData gets a reference to the given map[string]interface{} and assigns it to the AdditionalData field.
func (o *CreatePurchaseRequest) SetAdditionalData(v map[string]interface{}) {
	o.AdditionalData = v
}

// GetCallbackUrl returns the CallbackUrl field value if set, zero value otherwise.
func (o *CreatePurchaseRequest) GetCallbackUrl() string {
	if o == nil || IsNil(o.CallbackUrl) {
		var ret string
		return ret
	}
	return *o.CallbackUrl
}

// GetCallbackUrlOk returns a tuple with the CallbackUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePurchaseRequest) GetCallbackUrlOk() (*string, bool) {
	if o == nil || IsNil(o.CallbackUrl) {
		return nil, false
	}
	return o.CallbackUrl, true
}

// HasCallbackUrl returns a boolean if a field has been set.
func (o *CreatePurchaseRequest) HasCallbackUrl() bool {
	if o != nil && !IsNil(o.CallbackUrl) {
		return true
	}

	return false
}

// SetCallbackUrl gets a reference to the given string and assigns it to the CallbackUrl field.
func (o *CreatePurchaseRequest) SetCallbackUrl(v string) {
	o.CallbackUrl = &v
}

// GetUserIdentifier returns the UserIdentifier field value if set, zero value otherwise.
func (o *CreatePurchaseRequest) GetUserIdentifier() string {
	if o == nil || IsNil(o.UserIdentifier) {
		var ret string
		return ret
	}
	return *o.UserIdentifier
}

// GetUserIdentifierOk returns a tuple with the UserIdentifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePurchaseRequest) GetUserIdentifierOk() (*string, bool) {
	if o == nil || IsNil(o.UserIdentifier) {
		return nil, false
	}
	return o.UserIdentifier, true
}

// HasUserIdentifier returns a boolean if a field has been set.
func (o *CreatePurchaseRequest) HasUserIdentifier() bool {
	if o != nil && !IsNil(o.UserIdentifier) {
		return true
	}

	return false
}

// SetUserIdentifier gets a reference to the given string and assigns it to the UserIdentifier field.
func (o *CreatePurchaseRequest) SetUserIdentifier(v string) {
	o.UserIdentifier = &v
}

func (o CreatePurchaseRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreatePurchaseRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.Wage) {
		toSerialize["wage"] = o.Wage
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.ClientReferenceNumber) {
		toSerialize["clientReferenceNumber"] = o.ClientReferenceNumber
	}
	if !IsNil(o.PayerMobileNumber) {
		toSerialize["payerMobileNumber"] = o.PayerMobileNumber
	}
	if !IsNil(o.CheckPayerMobileNumber) {
		toSerialize["checkPayerMobileNumber"] = o.CheckPayerMobileNumber
	}
	if !IsNil(o.PayerCardNumber) {
		toSerialize["payerCardNumber"] = o.PayerCardNumber
	}
	if !IsNil(o.PayerCardNumbers) {
		toSerialize["payerCardNumbers"] = o.PayerCardNumbers
	}
	if !IsNil(o.PayerNationalCode) {
		toSerialize["payerNationalCode"] = o.PayerNationalCode
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Switching) {
		toSerialize["switching"] = o.Switching
	}
	if !IsNil(o.AdditionalData) {
		toSerialize["additionalData"] = o.AdditionalData
	}
	if !IsNil(o.CallbackUrl) {
		toSerialize["callbackUrl"] = o.CallbackUrl
	}
	if !IsNil(o.UserIdentifier) {
		toSerialize["userIdentifier"] = o.UserIdentifier
	}
	return toSerialize, nil
}

type NullableCreatePurchaseRequest struct {
	value *CreatePurchaseRequest
	isSet bool
}

func (v NullableCreatePurchaseRequest) Get() *CreatePurchaseRequest {
	return v.value
}

func (v *NullableCreatePurchaseRequest) Set(val *CreatePurchaseRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatePurchaseRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatePurchaseRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatePurchaseRequest(val *CreatePurchaseRequest) *NullableCreatePurchaseRequest {
	return &NullableCreatePurchaseRequest{value: val, isSet: true}
}

func (v NullableCreatePurchaseRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatePurchaseRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


