/*
PPG: Proxy Payment Gateway

PPG is the Proxy Payment Gateway of Jibit corporation. It lets the users of 3rd-party clients (merchants, banks, organizations, ...) to purchase goodies from them using PPG as a transparent payment gateway. In back-end the user will be redirected to a PSP payment gateway (for example Saman) to pay the price of the purchase.  Using APIs of this application a client can create and initiate the purchase orders and can track the state of these purchases.  Using *Swagger Editor* you could directly call the PPG APIs and also could auto-generate a client for PPG APIs in your preferred programming language.  The base URL of PPG is: `https://napi.jibit.ir/ppg`  Full documentation is available on: https://napi.jibit.ir/ppg/v3/static/docs/index.html

API version: 3.2.48
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package jibit-ppg

import (
	"encoding/json"
)

// checks if the RefreshTokenRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RefreshTokenRequest{}

// RefreshTokenRequest The dto encapsulating the information to refresh the access/refresh tokens for the client.
type RefreshTokenRequest struct {
	// Represents the refresh token. Used to generate a new pair of access/refresh tokens for the client.
	RefreshToken *string `json:"refreshToken,omitempty"`
}

// NewRefreshTokenRequest instantiates a new RefreshTokenRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRefreshTokenRequest() *RefreshTokenRequest {
	this := RefreshTokenRequest{}
	return &this
}

// NewRefreshTokenRequestWithDefaults instantiates a new RefreshTokenRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRefreshTokenRequestWithDefaults() *RefreshTokenRequest {
	this := RefreshTokenRequest{}
	return &this
}

// GetRefreshToken returns the RefreshToken field value if set, zero value otherwise.
func (o *RefreshTokenRequest) GetRefreshToken() string {
	if o == nil || IsNil(o.RefreshToken) {
		var ret string
		return ret
	}
	return *o.RefreshToken
}

// GetRefreshTokenOk returns a tuple with the RefreshToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RefreshTokenRequest) GetRefreshTokenOk() (*string, bool) {
	if o == nil || IsNil(o.RefreshToken) {
		return nil, false
	}
	return o.RefreshToken, true
}

// HasRefreshToken returns a boolean if a field has been set.
func (o *RefreshTokenRequest) HasRefreshToken() bool {
	if o != nil && !IsNil(o.RefreshToken) {
		return true
	}

	return false
}

// SetRefreshToken gets a reference to the given string and assigns it to the RefreshToken field.
func (o *RefreshTokenRequest) SetRefreshToken(v string) {
	o.RefreshToken = &v
}

func (o RefreshTokenRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RefreshTokenRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RefreshToken) {
		toSerialize["refreshToken"] = o.RefreshToken
	}
	return toSerialize, nil
}

type NullableRefreshTokenRequest struct {
	value *RefreshTokenRequest
	isSet bool
}

func (v NullableRefreshTokenRequest) Get() *RefreshTokenRequest {
	return v.value
}

func (v *NullableRefreshTokenRequest) Set(val *RefreshTokenRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRefreshTokenRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRefreshTokenRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRefreshTokenRequest(val *RefreshTokenRequest) *NullableRefreshTokenRequest {
	return &NullableRefreshTokenRequest{value: val, isSet: true}
}

func (v NullableRefreshTokenRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRefreshTokenRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


