/*
PPG: Proxy Payment Gateway

PPG is the Proxy Payment Gateway of Jibit corporation. It lets the users of 3rd-party clients (merchants, banks, organizations, ...) to purchase goodies from them using PPG as a transparent payment gateway. In back-end the user will be redirected to a PSP payment gateway (for example Saman) to pay the price of the purchase.  Using APIs of this application a client can create and initiate the purchase orders and can track the state of these purchases.  Using *Swagger Editor* you could directly call the PPG APIs and also could auto-generate a client for PPG APIs in your preferred programming language.  The base URL of PPG is: `https://napi.jibit.ir/ppg`  Full documentation is available on: https://napi.jibit.ir/ppg/v3/static/docs/index.html

API version: 3.2.48
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ppg

import (
	"encoding/json"
)

// checks if the SettlementFilterCriteria type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SettlementFilterCriteria{}

// SettlementFilterCriteria Encapsulates the information to filter settlements.
type SettlementFilterCriteria struct {
	// Finds a settlement by its identifier. The `null` means no filtering at all.
	SettlementId *int64 `json:"settlementId,omitempty"`
	// Represents the page number; One indexed. The `null` means the first page.  The max page number is 20.
	Page *int32 `json:"page,omitempty"`
	// Represents the page size. The `null` means to use default size.  The default page size is 25.  The max page size is 250.
	Size *int32 `json:"size,omitempty"`
}

// NewSettlementFilterCriteria instantiates a new SettlementFilterCriteria object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSettlementFilterCriteria() *SettlementFilterCriteria {
	this := SettlementFilterCriteria{}
	return &this
}

// NewSettlementFilterCriteriaWithDefaults instantiates a new SettlementFilterCriteria object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSettlementFilterCriteriaWithDefaults() *SettlementFilterCriteria {
	this := SettlementFilterCriteria{}
	return &this
}

// GetSettlementId returns the SettlementId field value if set, zero value otherwise.
func (o *SettlementFilterCriteria) GetSettlementId() int64 {
	if o == nil || IsNil(o.SettlementId) {
		var ret int64
		return ret
	}
	return *o.SettlementId
}

// GetSettlementIdOk returns a tuple with the SettlementId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettlementFilterCriteria) GetSettlementIdOk() (*int64, bool) {
	if o == nil || IsNil(o.SettlementId) {
		return nil, false
	}
	return o.SettlementId, true
}

// HasSettlementId returns a boolean if a field has been set.
func (o *SettlementFilterCriteria) HasSettlementId() bool {
	if o != nil && !IsNil(o.SettlementId) {
		return true
	}

	return false
}

// SetSettlementId gets a reference to the given int64 and assigns it to the SettlementId field.
func (o *SettlementFilterCriteria) SetSettlementId(v int64) {
	o.SettlementId = &v
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *SettlementFilterCriteria) GetPage() int32 {
	if o == nil || IsNil(o.Page) {
		var ret int32
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettlementFilterCriteria) GetPageOk() (*int32, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *SettlementFilterCriteria) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given int32 and assigns it to the Page field.
func (o *SettlementFilterCriteria) SetPage(v int32) {
	o.Page = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *SettlementFilterCriteria) GetSize() int32 {
	if o == nil || IsNil(o.Size) {
		var ret int32
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettlementFilterCriteria) GetSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *SettlementFilterCriteria) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given int32 and assigns it to the Size field.
func (o *SettlementFilterCriteria) SetSize(v int32) {
	o.Size = &v
}

func (o SettlementFilterCriteria) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SettlementFilterCriteria) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SettlementId) {
		toSerialize["settlementId"] = o.SettlementId
	}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	return toSerialize, nil
}

type NullableSettlementFilterCriteria struct {
	value *SettlementFilterCriteria
	isSet bool
}

func (v NullableSettlementFilterCriteria) Get() *SettlementFilterCriteria {
	return v.value
}

func (v *NullableSettlementFilterCriteria) Set(val *SettlementFilterCriteria) {
	v.value = val
	v.isSet = true
}

func (v NullableSettlementFilterCriteria) IsSet() bool {
	return v.isSet
}

func (v *NullableSettlementFilterCriteria) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSettlementFilterCriteria(val *SettlementFilterCriteria) *NullableSettlementFilterCriteria {
	return &NullableSettlementFilterCriteria{value: val, isSet: true}
}

func (v NullableSettlementFilterCriteria) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSettlementFilterCriteria) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


