/*
PPG: Proxy Payment Gateway

PPG is the Proxy Payment Gateway of Jibit corporation. It lets the users of 3rd-party clients (merchants, banks, organizations, ...) to purchase goodies from them using PPG as a transparent payment gateway. In back-end the user will be redirected to a PSP payment gateway (for example Saman) to pay the price of the purchase.  Using APIs of this application a client can create and initiate the purchase orders and can track the state of these purchases.  Using *Swagger Editor* you could directly call the PPG APIs and also could auto-generate a client for PPG APIs in your preferred programming language.  The base URL of PPG is: `https://napi.jibit.ir/ppg`  Full documentation is available on: https://napi.jibit.ir/ppg/v3/static/docs/index.html

API version: 3.2.48
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package jibit-ppg

import (
	"encoding/json"
)

// checks if the ReversePurchaseRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReversePurchaseRequest{}

// ReversePurchaseRequest Encapsulated the information required to reverse a purchase.
type ReversePurchaseRequest struct {
	// Represents the reference number provided by client to trace the purchase in our system.
	ClientReferenceNumber *string `json:"clientReferenceNumber,omitempty"`
	// Represents the purchase id.
	PurchaseId *int64 `json:"purchaseId,omitempty"`
}

// NewReversePurchaseRequest instantiates a new ReversePurchaseRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReversePurchaseRequest() *ReversePurchaseRequest {
	this := ReversePurchaseRequest{}
	return &this
}

// NewReversePurchaseRequestWithDefaults instantiates a new ReversePurchaseRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReversePurchaseRequestWithDefaults() *ReversePurchaseRequest {
	this := ReversePurchaseRequest{}
	return &this
}

// GetClientReferenceNumber returns the ClientReferenceNumber field value if set, zero value otherwise.
func (o *ReversePurchaseRequest) GetClientReferenceNumber() string {
	if o == nil || IsNil(o.ClientReferenceNumber) {
		var ret string
		return ret
	}
	return *o.ClientReferenceNumber
}

// GetClientReferenceNumberOk returns a tuple with the ClientReferenceNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReversePurchaseRequest) GetClientReferenceNumberOk() (*string, bool) {
	if o == nil || IsNil(o.ClientReferenceNumber) {
		return nil, false
	}
	return o.ClientReferenceNumber, true
}

// HasClientReferenceNumber returns a boolean if a field has been set.
func (o *ReversePurchaseRequest) HasClientReferenceNumber() bool {
	if o != nil && !IsNil(o.ClientReferenceNumber) {
		return true
	}

	return false
}

// SetClientReferenceNumber gets a reference to the given string and assigns it to the ClientReferenceNumber field.
func (o *ReversePurchaseRequest) SetClientReferenceNumber(v string) {
	o.ClientReferenceNumber = &v
}

// GetPurchaseId returns the PurchaseId field value if set, zero value otherwise.
func (o *ReversePurchaseRequest) GetPurchaseId() int64 {
	if o == nil || IsNil(o.PurchaseId) {
		var ret int64
		return ret
	}
	return *o.PurchaseId
}

// GetPurchaseIdOk returns a tuple with the PurchaseId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReversePurchaseRequest) GetPurchaseIdOk() (*int64, bool) {
	if o == nil || IsNil(o.PurchaseId) {
		return nil, false
	}
	return o.PurchaseId, true
}

// HasPurchaseId returns a boolean if a field has been set.
func (o *ReversePurchaseRequest) HasPurchaseId() bool {
	if o != nil && !IsNil(o.PurchaseId) {
		return true
	}

	return false
}

// SetPurchaseId gets a reference to the given int64 and assigns it to the PurchaseId field.
func (o *ReversePurchaseRequest) SetPurchaseId(v int64) {
	o.PurchaseId = &v
}

func (o ReversePurchaseRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReversePurchaseRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ClientReferenceNumber) {
		toSerialize["clientReferenceNumber"] = o.ClientReferenceNumber
	}
	if !IsNil(o.PurchaseId) {
		toSerialize["purchaseId"] = o.PurchaseId
	}
	return toSerialize, nil
}

type NullableReversePurchaseRequest struct {
	value *ReversePurchaseRequest
	isSet bool
}

func (v NullableReversePurchaseRequest) Get() *ReversePurchaseRequest {
	return v.value
}

func (v *NullableReversePurchaseRequest) Set(val *ReversePurchaseRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableReversePurchaseRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableReversePurchaseRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReversePurchaseRequest(val *ReversePurchaseRequest) *NullableReversePurchaseRequest {
	return &NullableReversePurchaseRequest{value: val, isSet: true}
}

func (v NullableReversePurchaseRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReversePurchaseRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


