/*
PPG: Proxy Payment Gateway

PPG is the Proxy Payment Gateway of Jibit corporation. It lets the users of 3rd-party clients (merchants, banks, organizations, ...) to purchase goodies from them using PPG as a transparent payment gateway. In back-end the user will be redirected to a PSP payment gateway (for example Saman) to pay the price of the purchase.  Using APIs of this application a client can create and initiate the purchase orders and can track the state of these purchases.  Using *Swagger Editor* you could directly call the PPG APIs and also could auto-generate a client for PPG APIs in your preferred programming language.  The base URL of PPG is: `https://napi.jibit.ir/ppg`  Full documentation is available on: https://napi.jibit.ir/ppg/v3/static/docs/index.html

API version: 3.2.48
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ppg

import (
	"encoding/json"
	"time"
)

// checks if the TerminalDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TerminalDto{}

// TerminalDto Data Transfer Object representing a terminal, typically used within the context of Payment Service Providers (PSP).  This class includes details about the terminal, such as its unique identifiers, type, and associated configurations.
type TerminalDto struct {
	// Represents the unique natural identifier of a terminal.
	NaturalId *string `json:"naturalId,omitempty"`
	// Represents the unique code associated with a client.
	ClientCode *string `json:"clientCode,omitempty"`
	// Represents the name of the client associated with the terminal. `Snapp Pay`
	ClientName *string `json:"clientName,omitempty"`
	// Represents the name of payment service provider (PSP) associated with the terminal.                                        Possible values are: `saman-ipg`, `sepehr-ipg`, `behpardakht-ipg`
	PspName *string `json:"pspName,omitempty"`
	// The unique identifier of the PSP terminal.                                        This ID is used to associate a terminal with a specific PSP                                        and is essential for processing transactions through that terminal.
	PspTerminalId *string `json:"pspTerminalId,omitempty"`
	// Represents the merchant number associated with a specific PSP.                                        This field is used to uniquely identify a merchant in the PSP system.
	PspMerchantNumber *string `json:"pspMerchantNumber,omitempty"`
	// Represents the type of the terminal in the system.                                        It indicates the category of the terminal and is used to define                                        its behavior and processing type. The terminal can belong to                                        various types such as normal, payment facilitation, or auto-settling.
	Type *string `json:"type,omitempty"`
	// Represents whether the terminal supports direct settlement.                                        A terminal with direct settlement enabled allows funds to be                                        transferred directly to the settlement account without intermediary steps.
	DirectSettlement *bool `json:"directSettlement,omitempty"`
	// Represents the priority of the terminal.                                        This value generally determines the importance level                                        of the terminal in processing or ordering operations.                                        <p>                                        Higher priority means a greater chance for terminal to be used.
	Priority *int32 `json:"priority,omitempty"`
	// Indicates whether auto-verification is enabled for the terminal.
	IsAutoVerifyEnabled *bool `json:"isAutoVerifyEnabled,omitempty"`
	// Indicates whether the functionality to check if the payer's mobile number is active                                        is enabled or not. This field is used in scenarios where verifying the active status                                        of the payer's mobile number is required for processing.
	IsCheckPayerMobileNumberActive *bool `json:"isCheckPayerMobileNumberActive,omitempty"`
	// Indicates whether the functionality to check if the payer's national code is                                        enabled or not.
	IsCheckPayerNationalCodeActive *bool `json:"isCheckPayerNationalCodeActive,omitempty"`
	// Indicates whether the functionality to freeze a single card number in IPG page                                        is enabled or not.
	IsSingleCardFreezeActive *bool `json:"isSingleCardFreezeActive,omitempty"`
	// Represents the timestamp indicating when the `TerminalDto` instance was created.                                        This field is expected to store the creation time in the UTC timezone.
	CreatedAt *time.Time `json:"createdAt,omitempty"`
}

// NewTerminalDto instantiates a new TerminalDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTerminalDto() *TerminalDto {
	this := TerminalDto{}
	return &this
}

// NewTerminalDtoWithDefaults instantiates a new TerminalDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTerminalDtoWithDefaults() *TerminalDto {
	this := TerminalDto{}
	return &this
}

// GetNaturalId returns the NaturalId field value if set, zero value otherwise.
func (o *TerminalDto) GetNaturalId() string {
	if o == nil || IsNil(o.NaturalId) {
		var ret string
		return ret
	}
	return *o.NaturalId
}

// GetNaturalIdOk returns a tuple with the NaturalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerminalDto) GetNaturalIdOk() (*string, bool) {
	if o == nil || IsNil(o.NaturalId) {
		return nil, false
	}
	return o.NaturalId, true
}

// HasNaturalId returns a boolean if a field has been set.
func (o *TerminalDto) HasNaturalId() bool {
	if o != nil && !IsNil(o.NaturalId) {
		return true
	}

	return false
}

// SetNaturalId gets a reference to the given string and assigns it to the NaturalId field.
func (o *TerminalDto) SetNaturalId(v string) {
	o.NaturalId = &v
}

// GetClientCode returns the ClientCode field value if set, zero value otherwise.
func (o *TerminalDto) GetClientCode() string {
	if o == nil || IsNil(o.ClientCode) {
		var ret string
		return ret
	}
	return *o.ClientCode
}

// GetClientCodeOk returns a tuple with the ClientCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerminalDto) GetClientCodeOk() (*string, bool) {
	if o == nil || IsNil(o.ClientCode) {
		return nil, false
	}
	return o.ClientCode, true
}

// HasClientCode returns a boolean if a field has been set.
func (o *TerminalDto) HasClientCode() bool {
	if o != nil && !IsNil(o.ClientCode) {
		return true
	}

	return false
}

// SetClientCode gets a reference to the given string and assigns it to the ClientCode field.
func (o *TerminalDto) SetClientCode(v string) {
	o.ClientCode = &v
}

// GetClientName returns the ClientName field value if set, zero value otherwise.
func (o *TerminalDto) GetClientName() string {
	if o == nil || IsNil(o.ClientName) {
		var ret string
		return ret
	}
	return *o.ClientName
}

// GetClientNameOk returns a tuple with the ClientName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerminalDto) GetClientNameOk() (*string, bool) {
	if o == nil || IsNil(o.ClientName) {
		return nil, false
	}
	return o.ClientName, true
}

// HasClientName returns a boolean if a field has been set.
func (o *TerminalDto) HasClientName() bool {
	if o != nil && !IsNil(o.ClientName) {
		return true
	}

	return false
}

// SetClientName gets a reference to the given string and assigns it to the ClientName field.
func (o *TerminalDto) SetClientName(v string) {
	o.ClientName = &v
}

// GetPspName returns the PspName field value if set, zero value otherwise.
func (o *TerminalDto) GetPspName() string {
	if o == nil || IsNil(o.PspName) {
		var ret string
		return ret
	}
	return *o.PspName
}

// GetPspNameOk returns a tuple with the PspName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerminalDto) GetPspNameOk() (*string, bool) {
	if o == nil || IsNil(o.PspName) {
		return nil, false
	}
	return o.PspName, true
}

// HasPspName returns a boolean if a field has been set.
func (o *TerminalDto) HasPspName() bool {
	if o != nil && !IsNil(o.PspName) {
		return true
	}

	return false
}

// SetPspName gets a reference to the given string and assigns it to the PspName field.
func (o *TerminalDto) SetPspName(v string) {
	o.PspName = &v
}

// GetPspTerminalId returns the PspTerminalId field value if set, zero value otherwise.
func (o *TerminalDto) GetPspTerminalId() string {
	if o == nil || IsNil(o.PspTerminalId) {
		var ret string
		return ret
	}
	return *o.PspTerminalId
}

// GetPspTerminalIdOk returns a tuple with the PspTerminalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerminalDto) GetPspTerminalIdOk() (*string, bool) {
	if o == nil || IsNil(o.PspTerminalId) {
		return nil, false
	}
	return o.PspTerminalId, true
}

// HasPspTerminalId returns a boolean if a field has been set.
func (o *TerminalDto) HasPspTerminalId() bool {
	if o != nil && !IsNil(o.PspTerminalId) {
		return true
	}

	return false
}

// SetPspTerminalId gets a reference to the given string and assigns it to the PspTerminalId field.
func (o *TerminalDto) SetPspTerminalId(v string) {
	o.PspTerminalId = &v
}

// GetPspMerchantNumber returns the PspMerchantNumber field value if set, zero value otherwise.
func (o *TerminalDto) GetPspMerchantNumber() string {
	if o == nil || IsNil(o.PspMerchantNumber) {
		var ret string
		return ret
	}
	return *o.PspMerchantNumber
}

// GetPspMerchantNumberOk returns a tuple with the PspMerchantNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerminalDto) GetPspMerchantNumberOk() (*string, bool) {
	if o == nil || IsNil(o.PspMerchantNumber) {
		return nil, false
	}
	return o.PspMerchantNumber, true
}

// HasPspMerchantNumber returns a boolean if a field has been set.
func (o *TerminalDto) HasPspMerchantNumber() bool {
	if o != nil && !IsNil(o.PspMerchantNumber) {
		return true
	}

	return false
}

// SetPspMerchantNumber gets a reference to the given string and assigns it to the PspMerchantNumber field.
func (o *TerminalDto) SetPspMerchantNumber(v string) {
	o.PspMerchantNumber = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *TerminalDto) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerminalDto) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *TerminalDto) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *TerminalDto) SetType(v string) {
	o.Type = &v
}

// GetDirectSettlement returns the DirectSettlement field value if set, zero value otherwise.
func (o *TerminalDto) GetDirectSettlement() bool {
	if o == nil || IsNil(o.DirectSettlement) {
		var ret bool
		return ret
	}
	return *o.DirectSettlement
}

// GetDirectSettlementOk returns a tuple with the DirectSettlement field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerminalDto) GetDirectSettlementOk() (*bool, bool) {
	if o == nil || IsNil(o.DirectSettlement) {
		return nil, false
	}
	return o.DirectSettlement, true
}

// HasDirectSettlement returns a boolean if a field has been set.
func (o *TerminalDto) HasDirectSettlement() bool {
	if o != nil && !IsNil(o.DirectSettlement) {
		return true
	}

	return false
}

// SetDirectSettlement gets a reference to the given bool and assigns it to the DirectSettlement field.
func (o *TerminalDto) SetDirectSettlement(v bool) {
	o.DirectSettlement = &v
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *TerminalDto) GetPriority() int32 {
	if o == nil || IsNil(o.Priority) {
		var ret int32
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerminalDto) GetPriorityOk() (*int32, bool) {
	if o == nil || IsNil(o.Priority) {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *TerminalDto) HasPriority() bool {
	if o != nil && !IsNil(o.Priority) {
		return true
	}

	return false
}

// SetPriority gets a reference to the given int32 and assigns it to the Priority field.
func (o *TerminalDto) SetPriority(v int32) {
	o.Priority = &v
}

// GetIsAutoVerifyEnabled returns the IsAutoVerifyEnabled field value if set, zero value otherwise.
func (o *TerminalDto) GetIsAutoVerifyEnabled() bool {
	if o == nil || IsNil(o.IsAutoVerifyEnabled) {
		var ret bool
		return ret
	}
	return *o.IsAutoVerifyEnabled
}

// GetIsAutoVerifyEnabledOk returns a tuple with the IsAutoVerifyEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerminalDto) GetIsAutoVerifyEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.IsAutoVerifyEnabled) {
		return nil, false
	}
	return o.IsAutoVerifyEnabled, true
}

// HasIsAutoVerifyEnabled returns a boolean if a field has been set.
func (o *TerminalDto) HasIsAutoVerifyEnabled() bool {
	if o != nil && !IsNil(o.IsAutoVerifyEnabled) {
		return true
	}

	return false
}

// SetIsAutoVerifyEnabled gets a reference to the given bool and assigns it to the IsAutoVerifyEnabled field.
func (o *TerminalDto) SetIsAutoVerifyEnabled(v bool) {
	o.IsAutoVerifyEnabled = &v
}

// GetIsCheckPayerMobileNumberActive returns the IsCheckPayerMobileNumberActive field value if set, zero value otherwise.
func (o *TerminalDto) GetIsCheckPayerMobileNumberActive() bool {
	if o == nil || IsNil(o.IsCheckPayerMobileNumberActive) {
		var ret bool
		return ret
	}
	return *o.IsCheckPayerMobileNumberActive
}

// GetIsCheckPayerMobileNumberActiveOk returns a tuple with the IsCheckPayerMobileNumberActive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerminalDto) GetIsCheckPayerMobileNumberActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.IsCheckPayerMobileNumberActive) {
		return nil, false
	}
	return o.IsCheckPayerMobileNumberActive, true
}

// HasIsCheckPayerMobileNumberActive returns a boolean if a field has been set.
func (o *TerminalDto) HasIsCheckPayerMobileNumberActive() bool {
	if o != nil && !IsNil(o.IsCheckPayerMobileNumberActive) {
		return true
	}

	return false
}

// SetIsCheckPayerMobileNumberActive gets a reference to the given bool and assigns it to the IsCheckPayerMobileNumberActive field.
func (o *TerminalDto) SetIsCheckPayerMobileNumberActive(v bool) {
	o.IsCheckPayerMobileNumberActive = &v
}

// GetIsCheckPayerNationalCodeActive returns the IsCheckPayerNationalCodeActive field value if set, zero value otherwise.
func (o *TerminalDto) GetIsCheckPayerNationalCodeActive() bool {
	if o == nil || IsNil(o.IsCheckPayerNationalCodeActive) {
		var ret bool
		return ret
	}
	return *o.IsCheckPayerNationalCodeActive
}

// GetIsCheckPayerNationalCodeActiveOk returns a tuple with the IsCheckPayerNationalCodeActive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerminalDto) GetIsCheckPayerNationalCodeActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.IsCheckPayerNationalCodeActive) {
		return nil, false
	}
	return o.IsCheckPayerNationalCodeActive, true
}

// HasIsCheckPayerNationalCodeActive returns a boolean if a field has been set.
func (o *TerminalDto) HasIsCheckPayerNationalCodeActive() bool {
	if o != nil && !IsNil(o.IsCheckPayerNationalCodeActive) {
		return true
	}

	return false
}

// SetIsCheckPayerNationalCodeActive gets a reference to the given bool and assigns it to the IsCheckPayerNationalCodeActive field.
func (o *TerminalDto) SetIsCheckPayerNationalCodeActive(v bool) {
	o.IsCheckPayerNationalCodeActive = &v
}

// GetIsSingleCardFreezeActive returns the IsSingleCardFreezeActive field value if set, zero value otherwise.
func (o *TerminalDto) GetIsSingleCardFreezeActive() bool {
	if o == nil || IsNil(o.IsSingleCardFreezeActive) {
		var ret bool
		return ret
	}
	return *o.IsSingleCardFreezeActive
}

// GetIsSingleCardFreezeActiveOk returns a tuple with the IsSingleCardFreezeActive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerminalDto) GetIsSingleCardFreezeActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.IsSingleCardFreezeActive) {
		return nil, false
	}
	return o.IsSingleCardFreezeActive, true
}

// HasIsSingleCardFreezeActive returns a boolean if a field has been set.
func (o *TerminalDto) HasIsSingleCardFreezeActive() bool {
	if o != nil && !IsNil(o.IsSingleCardFreezeActive) {
		return true
	}

	return false
}

// SetIsSingleCardFreezeActive gets a reference to the given bool and assigns it to the IsSingleCardFreezeActive field.
func (o *TerminalDto) SetIsSingleCardFreezeActive(v bool) {
	o.IsSingleCardFreezeActive = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *TerminalDto) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerminalDto) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *TerminalDto) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *TerminalDto) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

func (o TerminalDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TerminalDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NaturalId) {
		toSerialize["naturalId"] = o.NaturalId
	}
	if !IsNil(o.ClientCode) {
		toSerialize["clientCode"] = o.ClientCode
	}
	if !IsNil(o.ClientName) {
		toSerialize["clientName"] = o.ClientName
	}
	if !IsNil(o.PspName) {
		toSerialize["pspName"] = o.PspName
	}
	if !IsNil(o.PspTerminalId) {
		toSerialize["pspTerminalId"] = o.PspTerminalId
	}
	if !IsNil(o.PspMerchantNumber) {
		toSerialize["pspMerchantNumber"] = o.PspMerchantNumber
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.DirectSettlement) {
		toSerialize["directSettlement"] = o.DirectSettlement
	}
	if !IsNil(o.Priority) {
		toSerialize["priority"] = o.Priority
	}
	if !IsNil(o.IsAutoVerifyEnabled) {
		toSerialize["isAutoVerifyEnabled"] = o.IsAutoVerifyEnabled
	}
	if !IsNil(o.IsCheckPayerMobileNumberActive) {
		toSerialize["isCheckPayerMobileNumberActive"] = o.IsCheckPayerMobileNumberActive
	}
	if !IsNil(o.IsCheckPayerNationalCodeActive) {
		toSerialize["isCheckPayerNationalCodeActive"] = o.IsCheckPayerNationalCodeActive
	}
	if !IsNil(o.IsSingleCardFreezeActive) {
		toSerialize["isSingleCardFreezeActive"] = o.IsSingleCardFreezeActive
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	return toSerialize, nil
}

type NullableTerminalDto struct {
	value *TerminalDto
	isSet bool
}

func (v NullableTerminalDto) Get() *TerminalDto {
	return v.value
}

func (v *NullableTerminalDto) Set(val *TerminalDto) {
	v.value = val
	v.isSet = true
}

func (v NullableTerminalDto) IsSet() bool {
	return v.isSet
}

func (v *NullableTerminalDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTerminalDto(val *TerminalDto) *NullableTerminalDto {
	return &NullableTerminalDto{value: val, isSet: true}
}

func (v NullableTerminalDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTerminalDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


