/*
PPG: Proxy Payment Gateway

PPG is the Proxy Payment Gateway of Jibit corporation. It lets the users of 3rd-party clients (merchants, banks, organizations, ...) to purchase goodies from them using PPG as a transparent payment gateway. In back-end the user will be redirected to a PSP payment gateway (for example Saman) to pay the price of the purchase.  Using APIs of this application a client can create and initiate the purchase orders and can track the state of these purchases.  Using *Swagger Editor* you could directly call the PPG APIs and also could auto-generate a client for PPG APIs in your preferred programming language.  The base URL of PPG is: `https://napi.jibit.ir/ppg`  Full documentation is available on: https://napi.jibit.ir/ppg/v3/static/docs/index.html

API version: 3.2.48
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ppg

import (
	"encoding/json"
)

// checks if the PaginatedDetailedPurchaseDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedDetailedPurchaseDto{}

// PaginatedDetailedPurchaseDto DTO to wrap paginated collection of elements.
type PaginatedDetailedPurchaseDto struct {
	// The current 1-index page number.
	PageNumber *int32 `json:"pageNumber,omitempty"`
	// The size of current page.
	Size *int32 `json:"size,omitempty"`
	// Total number of elements.
	NumberOfElements *int64 `json:"numberOfElements,omitempty"`
	// Can this page be followed by another page after it?
	HasNext *bool `json:"hasNext,omitempty"`
	// Is there a previous page for this page?
	HasPrevious *bool `json:"hasPrevious,omitempty"`
	// The actual paginated elements.
	Elements []DetailedPurchaseDto `json:"elements,omitempty"`
}

// NewPaginatedDetailedPurchaseDto instantiates a new PaginatedDetailedPurchaseDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedDetailedPurchaseDto() *PaginatedDetailedPurchaseDto {
	this := PaginatedDetailedPurchaseDto{}
	return &this
}

// NewPaginatedDetailedPurchaseDtoWithDefaults instantiates a new PaginatedDetailedPurchaseDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedDetailedPurchaseDtoWithDefaults() *PaginatedDetailedPurchaseDto {
	this := PaginatedDetailedPurchaseDto{}
	return &this
}

// GetPageNumber returns the PageNumber field value if set, zero value otherwise.
func (o *PaginatedDetailedPurchaseDto) GetPageNumber() int32 {
	if o == nil || IsNil(o.PageNumber) {
		var ret int32
		return ret
	}
	return *o.PageNumber
}

// GetPageNumberOk returns a tuple with the PageNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedDetailedPurchaseDto) GetPageNumberOk() (*int32, bool) {
	if o == nil || IsNil(o.PageNumber) {
		return nil, false
	}
	return o.PageNumber, true
}

// HasPageNumber returns a boolean if a field has been set.
func (o *PaginatedDetailedPurchaseDto) HasPageNumber() bool {
	if o != nil && !IsNil(o.PageNumber) {
		return true
	}

	return false
}

// SetPageNumber gets a reference to the given int32 and assigns it to the PageNumber field.
func (o *PaginatedDetailedPurchaseDto) SetPageNumber(v int32) {
	o.PageNumber = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *PaginatedDetailedPurchaseDto) GetSize() int32 {
	if o == nil || IsNil(o.Size) {
		var ret int32
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedDetailedPurchaseDto) GetSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *PaginatedDetailedPurchaseDto) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given int32 and assigns it to the Size field.
func (o *PaginatedDetailedPurchaseDto) SetSize(v int32) {
	o.Size = &v
}

// GetNumberOfElements returns the NumberOfElements field value if set, zero value otherwise.
func (o *PaginatedDetailedPurchaseDto) GetNumberOfElements() int64 {
	if o == nil || IsNil(o.NumberOfElements) {
		var ret int64
		return ret
	}
	return *o.NumberOfElements
}

// GetNumberOfElementsOk returns a tuple with the NumberOfElements field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedDetailedPurchaseDto) GetNumberOfElementsOk() (*int64, bool) {
	if o == nil || IsNil(o.NumberOfElements) {
		return nil, false
	}
	return o.NumberOfElements, true
}

// HasNumberOfElements returns a boolean if a field has been set.
func (o *PaginatedDetailedPurchaseDto) HasNumberOfElements() bool {
	if o != nil && !IsNil(o.NumberOfElements) {
		return true
	}

	return false
}

// SetNumberOfElements gets a reference to the given int64 and assigns it to the NumberOfElements field.
func (o *PaginatedDetailedPurchaseDto) SetNumberOfElements(v int64) {
	o.NumberOfElements = &v
}

// GetHasNext returns the HasNext field value if set, zero value otherwise.
func (o *PaginatedDetailedPurchaseDto) GetHasNext() bool {
	if o == nil || IsNil(o.HasNext) {
		var ret bool
		return ret
	}
	return *o.HasNext
}

// GetHasNextOk returns a tuple with the HasNext field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedDetailedPurchaseDto) GetHasNextOk() (*bool, bool) {
	if o == nil || IsNil(o.HasNext) {
		return nil, false
	}
	return o.HasNext, true
}

// HasHasNext returns a boolean if a field has been set.
func (o *PaginatedDetailedPurchaseDto) HasHasNext() bool {
	if o != nil && !IsNil(o.HasNext) {
		return true
	}

	return false
}

// SetHasNext gets a reference to the given bool and assigns it to the HasNext field.
func (o *PaginatedDetailedPurchaseDto) SetHasNext(v bool) {
	o.HasNext = &v
}

// GetHasPrevious returns the HasPrevious field value if set, zero value otherwise.
func (o *PaginatedDetailedPurchaseDto) GetHasPrevious() bool {
	if o == nil || IsNil(o.HasPrevious) {
		var ret bool
		return ret
	}
	return *o.HasPrevious
}

// GetHasPreviousOk returns a tuple with the HasPrevious field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedDetailedPurchaseDto) GetHasPreviousOk() (*bool, bool) {
	if o == nil || IsNil(o.HasPrevious) {
		return nil, false
	}
	return o.HasPrevious, true
}

// HasHasPrevious returns a boolean if a field has been set.
func (o *PaginatedDetailedPurchaseDto) HasHasPrevious() bool {
	if o != nil && !IsNil(o.HasPrevious) {
		return true
	}

	return false
}

// SetHasPrevious gets a reference to the given bool and assigns it to the HasPrevious field.
func (o *PaginatedDetailedPurchaseDto) SetHasPrevious(v bool) {
	o.HasPrevious = &v
}

// GetElements returns the Elements field value if set, zero value otherwise.
func (o *PaginatedDetailedPurchaseDto) GetElements() []DetailedPurchaseDto {
	if o == nil || IsNil(o.Elements) {
		var ret []DetailedPurchaseDto
		return ret
	}
	return o.Elements
}

// GetElementsOk returns a tuple with the Elements field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedDetailedPurchaseDto) GetElementsOk() ([]DetailedPurchaseDto, bool) {
	if o == nil || IsNil(o.Elements) {
		return nil, false
	}
	return o.Elements, true
}

// HasElements returns a boolean if a field has been set.
func (o *PaginatedDetailedPurchaseDto) HasElements() bool {
	if o != nil && !IsNil(o.Elements) {
		return true
	}

	return false
}

// SetElements gets a reference to the given []DetailedPurchaseDto and assigns it to the Elements field.
func (o *PaginatedDetailedPurchaseDto) SetElements(v []DetailedPurchaseDto) {
	o.Elements = v
}

func (o PaginatedDetailedPurchaseDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedDetailedPurchaseDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PageNumber) {
		toSerialize["pageNumber"] = o.PageNumber
	}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	if !IsNil(o.NumberOfElements) {
		toSerialize["numberOfElements"] = o.NumberOfElements
	}
	if !IsNil(o.HasNext) {
		toSerialize["hasNext"] = o.HasNext
	}
	if !IsNil(o.HasPrevious) {
		toSerialize["hasPrevious"] = o.HasPrevious
	}
	if !IsNil(o.Elements) {
		toSerialize["elements"] = o.Elements
	}
	return toSerialize, nil
}

type NullablePaginatedDetailedPurchaseDto struct {
	value *PaginatedDetailedPurchaseDto
	isSet bool
}

func (v NullablePaginatedDetailedPurchaseDto) Get() *PaginatedDetailedPurchaseDto {
	return v.value
}

func (v *NullablePaginatedDetailedPurchaseDto) Set(val *PaginatedDetailedPurchaseDto) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedDetailedPurchaseDto) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedDetailedPurchaseDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedDetailedPurchaseDto(val *PaginatedDetailedPurchaseDto) *NullablePaginatedDetailedPurchaseDto {
	return &NullablePaginatedDetailedPurchaseDto{value: val, isSet: true}
}

func (v NullablePaginatedDetailedPurchaseDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedDetailedPurchaseDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


