/*
PPG: Proxy Payment Gateway

PPG is the Proxy Payment Gateway of Jibit corporation. It lets the users of 3rd-party clients (merchants, banks, organizations, ...) to purchase goodies from them using PPG as a transparent payment gateway. In back-end the user will be redirected to a PSP payment gateway (for example Saman) to pay the price of the purchase.  Using APIs of this application a client can create and initiate the purchase orders and can track the state of these purchases.  Using *Swagger Editor* you could directly call the PPG APIs and also could auto-generate a client for PPG APIs in your preferred programming language.  The base URL of PPG is: `https://napi.jibit.ir/ppg`  Full documentation is available on: https://napi.jibit.ir/ppg/v3/static/docs/index.html

API version: 3.2.48
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package jibit-ppg

import (
	"encoding/json"
	"time"
)

// checks if the DetailedPurchaseDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DetailedPurchaseDto{}

// DetailedPurchaseDto Encapsulates a detailed view of a purchase.
type DetailedPurchaseDto struct {
	// Represents the purchase identifier.
	PurchaseId *int64 `json:"purchaseId,omitempty"`
	// Represents the purchase identifier as String to bypass deserialization issues in some programming languages e.x. Javascript and Typescript.
	PurchaseIdStr *string `json:"purchaseIdStr,omitempty"`
	// Represents the amount of purchase.
	Amount *int64 `json:"amount,omitempty"`
	// Represents the wage of purchase given by client.
	Wage *int64 `json:"wage,omitempty"`
	// Represents the Jibit fee for this purchase.
	Fee *int64 `json:"fee,omitempty"`
	// Represents the payment type of purchase fee.
	FeePaymentType *string `json:"feePaymentType,omitempty"`
	// Represents the Shaparak fee for this purchase.
	ShaparakFee *int64 `json:"shaparakFee,omitempty"`
	// Represents the reseller code for this purchase.
	ResellerCode *string `json:"resellerCode,omitempty"`
	// Represents the reseller affiliate fee for this purchase.
	AffiliateFee *int64 `json:"affiliateFee,omitempty"`
	// Represents the net amount of purchase that will be settled with the client.  `Net Amount == Amount + Wage - Prepaid Fee - Prepaid Affiliate Fee - Shaparak Fee`.  If the client has no reseller, affiliate fee will be assumed as 0 in the above formula.  Fee and Affiliate Fee are decreased from purchase amount only in pre-paid mode.  Notes: In any case, The `Amount + Wage` will be added to the client's wallet default balance type (WLT) on purchase success.  After Shaparak (or PSP) settlement, the net amount will be added to the client's settleable balance type (STL) or settled directly to the client's IBAN.  This is available only if the **Early Fee Calculation** feature is enabled.
	NetAmount *int64 `json:"netAmount,omitempty"`
	// Represents the currency type.
	Currency *string `json:"currency,omitempty"`
	// Represents a callback which we should call in order to notify the client about a particular purchase state.  For example, when the user pays the purchase, we would redirect the user to this callback and let the client know about the payment.
	CallbackUrl *string `json:"callbackUrl,omitempty"`
	// Represents the simple purchase state.  <p>  The following states indicate the purchase had a contradiction and now is resolved.  <p>  * `MANUALLY_SUCCESS`: The purchase has been successful manually.  * `REVERSED`: The purchase has been reversed manually.
	State *string `json:"state,omitempty"`
	// A string value from client side to trace purchase in our system. This value is unique between client purchases.
	ClientReferenceNumber *string `json:"clientReferenceNumber,omitempty"`
	// Represents the PSP name which the purchase belongs to.
	PspName *string `json:"pspName,omitempty"`
	// Represents the PSP Retrieval Reference Number, a key to uniquely identify a card transaction based on the ISO 8583 standard.
	PspRrn *string `json:"pspRrn,omitempty"`
	// Represents the PSP reference number.
	PspReferenceNumber *string `json:"pspReferenceNumber,omitempty"`
	// Represents the PSP trace number.
	PspTraceNumber *string `json:"pspTraceNumber,omitempty"`
	// When has the purchase been expired?
	ExpirationDate *time.Time `json:"expirationDate,omitempty"`
	// Identifies the user in the client system.
	UserIdentifier *string `json:"userIdentifier,omitempty"`
	// Represents the user mobile number.
	PayerMobileNumber *string `json:"payerMobileNumber,omitempty"`
	// Represents the user card number that the purchase is forced to do the transaction.
	PayerCardNumber *string `json:"payerCardNumber,omitempty"`
	// Represents the user national code that is used to check the owner of the PSP payer card.
	PayerNationalCode *string `json:"payerNationalCode,omitempty"`
	// An optional client provided description for the purchase.
	Description *string `json:"description,omitempty"`
	// An optional additional data provided by the client in JSON format.
	AdditionalData map[string]interface{} `json:"additionalData,omitempty"`
	// Masked bank card number used to do the transaction.
	PspMaskedCardNumber *string `json:"pspMaskedCardNumber,omitempty"`
	// Hashed bank card number used to do the transaction. Provided by PSP.
	PspHashedCardNumber *string `json:"pspHashedCardNumber,omitempty"`
	// Represents the card owner name.
	PspCardOwner *string `json:"pspCardOwner,omitempty"`
	// Represents the PSP fail reason.  **DEPRECATED. For removal in the future. Use `pspFailReasons` instead.**
	// Deprecated
	PspFailReason *string `json:"pspFailReason,omitempty"`
	// Represents the list of PSP fail reasons.
	PspFailReasons []PspFailReason `json:"pspFailReasons,omitempty"`
	// The IP address of the user calling the payment URL generated by us.
	InitPayerIp *string `json:"initPayerIp,omitempty"`
	// The IP address of the user reported by the PSP.
	RedirectPayerIp *string `json:"redirectPayerIp,omitempty"`
	// Whether the PSP settled the payment.
	PspSettled *bool `json:"pspSettled,omitempty"`
	// Whether the purchase is refunded.
	Refunded *bool `json:"refunded,omitempty"`
	RefundInquiryResult *RefundInquiryResult `json:"refundInquiryResult,omitempty"`
	// Represents the refundable amount. It is equal to or less than `amount + wage`.
	RefundableAmount *int64 `json:"refundableAmount,omitempty"`
	// When the purchase created?
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// When was the billing date? Used to generate the billing receipt.
	BillingDate *time.Time `json:"billingDate,omitempty"`
	// When was the payment verification date?
	VerifiedAt *time.Time `json:"verifiedAt,omitempty"`
	// When the PSP settled the payment?
	PspSettledAt *time.Time `json:"pspSettledAt,omitempty"`
	// Indicates the identifier of the settlement which the purchase is settled by.
	SettlementId *int64 `json:"settlementId,omitempty"`
	// Indicates whether the purchase had a contradiction or not.
	HasContradiction *bool `json:"hasContradiction,omitempty"`
}

// NewDetailedPurchaseDto instantiates a new DetailedPurchaseDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDetailedPurchaseDto() *DetailedPurchaseDto {
	this := DetailedPurchaseDto{}
	return &this
}

// NewDetailedPurchaseDtoWithDefaults instantiates a new DetailedPurchaseDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDetailedPurchaseDtoWithDefaults() *DetailedPurchaseDto {
	this := DetailedPurchaseDto{}
	return &this
}

// GetPurchaseId returns the PurchaseId field value if set, zero value otherwise.
func (o *DetailedPurchaseDto) GetPurchaseId() int64 {
	if o == nil || IsNil(o.PurchaseId) {
		var ret int64
		return ret
	}
	return *o.PurchaseId
}

// GetPurchaseIdOk returns a tuple with the PurchaseId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedPurchaseDto) GetPurchaseIdOk() (*int64, bool) {
	if o == nil || IsNil(o.PurchaseId) {
		return nil, false
	}
	return o.PurchaseId, true
}

// HasPurchaseId returns a boolean if a field has been set.
func (o *DetailedPurchaseDto) HasPurchaseId() bool {
	if o != nil && !IsNil(o.PurchaseId) {
		return true
	}

	return false
}

// SetPurchaseId gets a reference to the given int64 and assigns it to the PurchaseId field.
func (o *DetailedPurchaseDto) SetPurchaseId(v int64) {
	o.PurchaseId = &v
}

// GetPurchaseIdStr returns the PurchaseIdStr field value if set, zero value otherwise.
func (o *DetailedPurchaseDto) GetPurchaseIdStr() string {
	if o == nil || IsNil(o.PurchaseIdStr) {
		var ret string
		return ret
	}
	return *o.PurchaseIdStr
}

// GetPurchaseIdStrOk returns a tuple with the PurchaseIdStr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedPurchaseDto) GetPurchaseIdStrOk() (*string, bool) {
	if o == nil || IsNil(o.PurchaseIdStr) {
		return nil, false
	}
	return o.PurchaseIdStr, true
}

// HasPurchaseIdStr returns a boolean if a field has been set.
func (o *DetailedPurchaseDto) HasPurchaseIdStr() bool {
	if o != nil && !IsNil(o.PurchaseIdStr) {
		return true
	}

	return false
}

// SetPurchaseIdStr gets a reference to the given string and assigns it to the PurchaseIdStr field.
func (o *DetailedPurchaseDto) SetPurchaseIdStr(v string) {
	o.PurchaseIdStr = &v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *DetailedPurchaseDto) GetAmount() int64 {
	if o == nil || IsNil(o.Amount) {
		var ret int64
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedPurchaseDto) GetAmountOk() (*int64, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *DetailedPurchaseDto) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given int64 and assigns it to the Amount field.
func (o *DetailedPurchaseDto) SetAmount(v int64) {
	o.Amount = &v
}

// GetWage returns the Wage field value if set, zero value otherwise.
func (o *DetailedPurchaseDto) GetWage() int64 {
	if o == nil || IsNil(o.Wage) {
		var ret int64
		return ret
	}
	return *o.Wage
}

// GetWageOk returns a tuple with the Wage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedPurchaseDto) GetWageOk() (*int64, bool) {
	if o == nil || IsNil(o.Wage) {
		return nil, false
	}
	return o.Wage, true
}

// HasWage returns a boolean if a field has been set.
func (o *DetailedPurchaseDto) HasWage() bool {
	if o != nil && !IsNil(o.Wage) {
		return true
	}

	return false
}

// SetWage gets a reference to the given int64 and assigns it to the Wage field.
func (o *DetailedPurchaseDto) SetWage(v int64) {
	o.Wage = &v
}

// GetFee returns the Fee field value if set, zero value otherwise.
func (o *DetailedPurchaseDto) GetFee() int64 {
	if o == nil || IsNil(o.Fee) {
		var ret int64
		return ret
	}
	return *o.Fee
}

// GetFeeOk returns a tuple with the Fee field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedPurchaseDto) GetFeeOk() (*int64, bool) {
	if o == nil || IsNil(o.Fee) {
		return nil, false
	}
	return o.Fee, true
}

// HasFee returns a boolean if a field has been set.
func (o *DetailedPurchaseDto) HasFee() bool {
	if o != nil && !IsNil(o.Fee) {
		return true
	}

	return false
}

// SetFee gets a reference to the given int64 and assigns it to the Fee field.
func (o *DetailedPurchaseDto) SetFee(v int64) {
	o.Fee = &v
}

// GetFeePaymentType returns the FeePaymentType field value if set, zero value otherwise.
func (o *DetailedPurchaseDto) GetFeePaymentType() string {
	if o == nil || IsNil(o.FeePaymentType) {
		var ret string
		return ret
	}
	return *o.FeePaymentType
}

// GetFeePaymentTypeOk returns a tuple with the FeePaymentType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedPurchaseDto) GetFeePaymentTypeOk() (*string, bool) {
	if o == nil || IsNil(o.FeePaymentType) {
		return nil, false
	}
	return o.FeePaymentType, true
}

// HasFeePaymentType returns a boolean if a field has been set.
func (o *DetailedPurchaseDto) HasFeePaymentType() bool {
	if o != nil && !IsNil(o.FeePaymentType) {
		return true
	}

	return false
}

// SetFeePaymentType gets a reference to the given string and assigns it to the FeePaymentType field.
func (o *DetailedPurchaseDto) SetFeePaymentType(v string) {
	o.FeePaymentType = &v
}

// GetShaparakFee returns the ShaparakFee field value if set, zero value otherwise.
func (o *DetailedPurchaseDto) GetShaparakFee() int64 {
	if o == nil || IsNil(o.ShaparakFee) {
		var ret int64
		return ret
	}
	return *o.ShaparakFee
}

// GetShaparakFeeOk returns a tuple with the ShaparakFee field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedPurchaseDto) GetShaparakFeeOk() (*int64, bool) {
	if o == nil || IsNil(o.ShaparakFee) {
		return nil, false
	}
	return o.ShaparakFee, true
}

// HasShaparakFee returns a boolean if a field has been set.
func (o *DetailedPurchaseDto) HasShaparakFee() bool {
	if o != nil && !IsNil(o.ShaparakFee) {
		return true
	}

	return false
}

// SetShaparakFee gets a reference to the given int64 and assigns it to the ShaparakFee field.
func (o *DetailedPurchaseDto) SetShaparakFee(v int64) {
	o.ShaparakFee = &v
}

// GetResellerCode returns the ResellerCode field value if set, zero value otherwise.
func (o *DetailedPurchaseDto) GetResellerCode() string {
	if o == nil || IsNil(o.ResellerCode) {
		var ret string
		return ret
	}
	return *o.ResellerCode
}

// GetResellerCodeOk returns a tuple with the ResellerCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedPurchaseDto) GetResellerCodeOk() (*string, bool) {
	if o == nil || IsNil(o.ResellerCode) {
		return nil, false
	}
	return o.ResellerCode, true
}

// HasResellerCode returns a boolean if a field has been set.
func (o *DetailedPurchaseDto) HasResellerCode() bool {
	if o != nil && !IsNil(o.ResellerCode) {
		return true
	}

	return false
}

// SetResellerCode gets a reference to the given string and assigns it to the ResellerCode field.
func (o *DetailedPurchaseDto) SetResellerCode(v string) {
	o.ResellerCode = &v
}

// GetAffiliateFee returns the AffiliateFee field value if set, zero value otherwise.
func (o *DetailedPurchaseDto) GetAffiliateFee() int64 {
	if o == nil || IsNil(o.AffiliateFee) {
		var ret int64
		return ret
	}
	return *o.AffiliateFee
}

// GetAffiliateFeeOk returns a tuple with the AffiliateFee field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedPurchaseDto) GetAffiliateFeeOk() (*int64, bool) {
	if o == nil || IsNil(o.AffiliateFee) {
		return nil, false
	}
	return o.AffiliateFee, true
}

// HasAffiliateFee returns a boolean if a field has been set.
func (o *DetailedPurchaseDto) HasAffiliateFee() bool {
	if o != nil && !IsNil(o.AffiliateFee) {
		return true
	}

	return false
}

// SetAffiliateFee gets a reference to the given int64 and assigns it to the AffiliateFee field.
func (o *DetailedPurchaseDto) SetAffiliateFee(v int64) {
	o.AffiliateFee = &v
}

// GetNetAmount returns the NetAmount field value if set, zero value otherwise.
func (o *DetailedPurchaseDto) GetNetAmount() int64 {
	if o == nil || IsNil(o.NetAmount) {
		var ret int64
		return ret
	}
	return *o.NetAmount
}

// GetNetAmountOk returns a tuple with the NetAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedPurchaseDto) GetNetAmountOk() (*int64, bool) {
	if o == nil || IsNil(o.NetAmount) {
		return nil, false
	}
	return o.NetAmount, true
}

// HasNetAmount returns a boolean if a field has been set.
func (o *DetailedPurchaseDto) HasNetAmount() bool {
	if o != nil && !IsNil(o.NetAmount) {
		return true
	}

	return false
}

// SetNetAmount gets a reference to the given int64 and assigns it to the NetAmount field.
func (o *DetailedPurchaseDto) SetNetAmount(v int64) {
	o.NetAmount = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *DetailedPurchaseDto) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedPurchaseDto) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *DetailedPurchaseDto) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *DetailedPurchaseDto) SetCurrency(v string) {
	o.Currency = &v
}

// GetCallbackUrl returns the CallbackUrl field value if set, zero value otherwise.
func (o *DetailedPurchaseDto) GetCallbackUrl() string {
	if o == nil || IsNil(o.CallbackUrl) {
		var ret string
		return ret
	}
	return *o.CallbackUrl
}

// GetCallbackUrlOk returns a tuple with the CallbackUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedPurchaseDto) GetCallbackUrlOk() (*string, bool) {
	if o == nil || IsNil(o.CallbackUrl) {
		return nil, false
	}
	return o.CallbackUrl, true
}

// HasCallbackUrl returns a boolean if a field has been set.
func (o *DetailedPurchaseDto) HasCallbackUrl() bool {
	if o != nil && !IsNil(o.CallbackUrl) {
		return true
	}

	return false
}

// SetCallbackUrl gets a reference to the given string and assigns it to the CallbackUrl field.
func (o *DetailedPurchaseDto) SetCallbackUrl(v string) {
	o.CallbackUrl = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *DetailedPurchaseDto) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedPurchaseDto) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *DetailedPurchaseDto) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *DetailedPurchaseDto) SetState(v string) {
	o.State = &v
}

// GetClientReferenceNumber returns the ClientReferenceNumber field value if set, zero value otherwise.
func (o *DetailedPurchaseDto) GetClientReferenceNumber() string {
	if o == nil || IsNil(o.ClientReferenceNumber) {
		var ret string
		return ret
	}
	return *o.ClientReferenceNumber
}

// GetClientReferenceNumberOk returns a tuple with the ClientReferenceNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedPurchaseDto) GetClientReferenceNumberOk() (*string, bool) {
	if o == nil || IsNil(o.ClientReferenceNumber) {
		return nil, false
	}
	return o.ClientReferenceNumber, true
}

// HasClientReferenceNumber returns a boolean if a field has been set.
func (o *DetailedPurchaseDto) HasClientReferenceNumber() bool {
	if o != nil && !IsNil(o.ClientReferenceNumber) {
		return true
	}

	return false
}

// SetClientReferenceNumber gets a reference to the given string and assigns it to the ClientReferenceNumber field.
func (o *DetailedPurchaseDto) SetClientReferenceNumber(v string) {
	o.ClientReferenceNumber = &v
}

// GetPspName returns the PspName field value if set, zero value otherwise.
func (o *DetailedPurchaseDto) GetPspName() string {
	if o == nil || IsNil(o.PspName) {
		var ret string
		return ret
	}
	return *o.PspName
}

// GetPspNameOk returns a tuple with the PspName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedPurchaseDto) GetPspNameOk() (*string, bool) {
	if o == nil || IsNil(o.PspName) {
		return nil, false
	}
	return o.PspName, true
}

// HasPspName returns a boolean if a field has been set.
func (o *DetailedPurchaseDto) HasPspName() bool {
	if o != nil && !IsNil(o.PspName) {
		return true
	}

	return false
}

// SetPspName gets a reference to the given string and assigns it to the PspName field.
func (o *DetailedPurchaseDto) SetPspName(v string) {
	o.PspName = &v
}

// GetPspRrn returns the PspRrn field value if set, zero value otherwise.
func (o *DetailedPurchaseDto) GetPspRrn() string {
	if o == nil || IsNil(o.PspRrn) {
		var ret string
		return ret
	}
	return *o.PspRrn
}

// GetPspRrnOk returns a tuple with the PspRrn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedPurchaseDto) GetPspRrnOk() (*string, bool) {
	if o == nil || IsNil(o.PspRrn) {
		return nil, false
	}
	return o.PspRrn, true
}

// HasPspRrn returns a boolean if a field has been set.
func (o *DetailedPurchaseDto) HasPspRrn() bool {
	if o != nil && !IsNil(o.PspRrn) {
		return true
	}

	return false
}

// SetPspRrn gets a reference to the given string and assigns it to the PspRrn field.
func (o *DetailedPurchaseDto) SetPspRrn(v string) {
	o.PspRrn = &v
}

// GetPspReferenceNumber returns the PspReferenceNumber field value if set, zero value otherwise.
func (o *DetailedPurchaseDto) GetPspReferenceNumber() string {
	if o == nil || IsNil(o.PspReferenceNumber) {
		var ret string
		return ret
	}
	return *o.PspReferenceNumber
}

// GetPspReferenceNumberOk returns a tuple with the PspReferenceNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedPurchaseDto) GetPspReferenceNumberOk() (*string, bool) {
	if o == nil || IsNil(o.PspReferenceNumber) {
		return nil, false
	}
	return o.PspReferenceNumber, true
}

// HasPspReferenceNumber returns a boolean if a field has been set.
func (o *DetailedPurchaseDto) HasPspReferenceNumber() bool {
	if o != nil && !IsNil(o.PspReferenceNumber) {
		return true
	}

	return false
}

// SetPspReferenceNumber gets a reference to the given string and assigns it to the PspReferenceNumber field.
func (o *DetailedPurchaseDto) SetPspReferenceNumber(v string) {
	o.PspReferenceNumber = &v
}

// GetPspTraceNumber returns the PspTraceNumber field value if set, zero value otherwise.
func (o *DetailedPurchaseDto) GetPspTraceNumber() string {
	if o == nil || IsNil(o.PspTraceNumber) {
		var ret string
		return ret
	}
	return *o.PspTraceNumber
}

// GetPspTraceNumberOk returns a tuple with the PspTraceNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedPurchaseDto) GetPspTraceNumberOk() (*string, bool) {
	if o == nil || IsNil(o.PspTraceNumber) {
		return nil, false
	}
	return o.PspTraceNumber, true
}

// HasPspTraceNumber returns a boolean if a field has been set.
func (o *DetailedPurchaseDto) HasPspTraceNumber() bool {
	if o != nil && !IsNil(o.PspTraceNumber) {
		return true
	}

	return false
}

// SetPspTraceNumber gets a reference to the given string and assigns it to the PspTraceNumber field.
func (o *DetailedPurchaseDto) SetPspTraceNumber(v string) {
	o.PspTraceNumber = &v
}

// GetExpirationDate returns the ExpirationDate field value if set, zero value otherwise.
func (o *DetailedPurchaseDto) GetExpirationDate() time.Time {
	if o == nil || IsNil(o.ExpirationDate) {
		var ret time.Time
		return ret
	}
	return *o.ExpirationDate
}

// GetExpirationDateOk returns a tuple with the ExpirationDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedPurchaseDto) GetExpirationDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ExpirationDate) {
		return nil, false
	}
	return o.ExpirationDate, true
}

// HasExpirationDate returns a boolean if a field has been set.
func (o *DetailedPurchaseDto) HasExpirationDate() bool {
	if o != nil && !IsNil(o.ExpirationDate) {
		return true
	}

	return false
}

// SetExpirationDate gets a reference to the given time.Time and assigns it to the ExpirationDate field.
func (o *DetailedPurchaseDto) SetExpirationDate(v time.Time) {
	o.ExpirationDate = &v
}

// GetUserIdentifier returns the UserIdentifier field value if set, zero value otherwise.
func (o *DetailedPurchaseDto) GetUserIdentifier() string {
	if o == nil || IsNil(o.UserIdentifier) {
		var ret string
		return ret
	}
	return *o.UserIdentifier
}

// GetUserIdentifierOk returns a tuple with the UserIdentifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedPurchaseDto) GetUserIdentifierOk() (*string, bool) {
	if o == nil || IsNil(o.UserIdentifier) {
		return nil, false
	}
	return o.UserIdentifier, true
}

// HasUserIdentifier returns a boolean if a field has been set.
func (o *DetailedPurchaseDto) HasUserIdentifier() bool {
	if o != nil && !IsNil(o.UserIdentifier) {
		return true
	}

	return false
}

// SetUserIdentifier gets a reference to the given string and assigns it to the UserIdentifier field.
func (o *DetailedPurchaseDto) SetUserIdentifier(v string) {
	o.UserIdentifier = &v
}

// GetPayerMobileNumber returns the PayerMobileNumber field value if set, zero value otherwise.
func (o *DetailedPurchaseDto) GetPayerMobileNumber() string {
	if o == nil || IsNil(o.PayerMobileNumber) {
		var ret string
		return ret
	}
	return *o.PayerMobileNumber
}

// GetPayerMobileNumberOk returns a tuple with the PayerMobileNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedPurchaseDto) GetPayerMobileNumberOk() (*string, bool) {
	if o == nil || IsNil(o.PayerMobileNumber) {
		return nil, false
	}
	return o.PayerMobileNumber, true
}

// HasPayerMobileNumber returns a boolean if a field has been set.
func (o *DetailedPurchaseDto) HasPayerMobileNumber() bool {
	if o != nil && !IsNil(o.PayerMobileNumber) {
		return true
	}

	return false
}

// SetPayerMobileNumber gets a reference to the given string and assigns it to the PayerMobileNumber field.
func (o *DetailedPurchaseDto) SetPayerMobileNumber(v string) {
	o.PayerMobileNumber = &v
}

// GetPayerCardNumber returns the PayerCardNumber field value if set, zero value otherwise.
func (o *DetailedPurchaseDto) GetPayerCardNumber() string {
	if o == nil || IsNil(o.PayerCardNumber) {
		var ret string
		return ret
	}
	return *o.PayerCardNumber
}

// GetPayerCardNumberOk returns a tuple with the PayerCardNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedPurchaseDto) GetPayerCardNumberOk() (*string, bool) {
	if o == nil || IsNil(o.PayerCardNumber) {
		return nil, false
	}
	return o.PayerCardNumber, true
}

// HasPayerCardNumber returns a boolean if a field has been set.
func (o *DetailedPurchaseDto) HasPayerCardNumber() bool {
	if o != nil && !IsNil(o.PayerCardNumber) {
		return true
	}

	return false
}

// SetPayerCardNumber gets a reference to the given string and assigns it to the PayerCardNumber field.
func (o *DetailedPurchaseDto) SetPayerCardNumber(v string) {
	o.PayerCardNumber = &v
}

// GetPayerNationalCode returns the PayerNationalCode field value if set, zero value otherwise.
func (o *DetailedPurchaseDto) GetPayerNationalCode() string {
	if o == nil || IsNil(o.PayerNationalCode) {
		var ret string
		return ret
	}
	return *o.PayerNationalCode
}

// GetPayerNationalCodeOk returns a tuple with the PayerNationalCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedPurchaseDto) GetPayerNationalCodeOk() (*string, bool) {
	if o == nil || IsNil(o.PayerNationalCode) {
		return nil, false
	}
	return o.PayerNationalCode, true
}

// HasPayerNationalCode returns a boolean if a field has been set.
func (o *DetailedPurchaseDto) HasPayerNationalCode() bool {
	if o != nil && !IsNil(o.PayerNationalCode) {
		return true
	}

	return false
}

// SetPayerNationalCode gets a reference to the given string and assigns it to the PayerNationalCode field.
func (o *DetailedPurchaseDto) SetPayerNationalCode(v string) {
	o.PayerNationalCode = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *DetailedPurchaseDto) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedPurchaseDto) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *DetailedPurchaseDto) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *DetailedPurchaseDto) SetDescription(v string) {
	o.Description = &v
}

// GetAdditionalData returns the AdditionalData field value if set, zero value otherwise.
func (o *DetailedPurchaseDto) GetAdditionalData() map[string]interface{} {
	if o == nil || IsNil(o.AdditionalData) {
		var ret map[string]interface{}
		return ret
	}
	return o.AdditionalData
}

// GetAdditionalDataOk returns a tuple with the AdditionalData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedPurchaseDto) GetAdditionalDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.AdditionalData) {
		return map[string]interface{}{}, false
	}
	return o.AdditionalData, true
}

// HasAdditionalData returns a boolean if a field has been set.
func (o *DetailedPurchaseDto) HasAdditionalData() bool {
	if o != nil && !IsNil(o.AdditionalData) {
		return true
	}

	return false
}

// SetAdditionalData gets a reference to the given map[string]interface{} and assigns it to the AdditionalData field.
func (o *DetailedPurchaseDto) SetAdditionalData(v map[string]interface{}) {
	o.AdditionalData = v
}

// GetPspMaskedCardNumber returns the PspMaskedCardNumber field value if set, zero value otherwise.
func (o *DetailedPurchaseDto) GetPspMaskedCardNumber() string {
	if o == nil || IsNil(o.PspMaskedCardNumber) {
		var ret string
		return ret
	}
	return *o.PspMaskedCardNumber
}

// GetPspMaskedCardNumberOk returns a tuple with the PspMaskedCardNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedPurchaseDto) GetPspMaskedCardNumberOk() (*string, bool) {
	if o == nil || IsNil(o.PspMaskedCardNumber) {
		return nil, false
	}
	return o.PspMaskedCardNumber, true
}

// HasPspMaskedCardNumber returns a boolean if a field has been set.
func (o *DetailedPurchaseDto) HasPspMaskedCardNumber() bool {
	if o != nil && !IsNil(o.PspMaskedCardNumber) {
		return true
	}

	return false
}

// SetPspMaskedCardNumber gets a reference to the given string and assigns it to the PspMaskedCardNumber field.
func (o *DetailedPurchaseDto) SetPspMaskedCardNumber(v string) {
	o.PspMaskedCardNumber = &v
}

// GetPspHashedCardNumber returns the PspHashedCardNumber field value if set, zero value otherwise.
func (o *DetailedPurchaseDto) GetPspHashedCardNumber() string {
	if o == nil || IsNil(o.PspHashedCardNumber) {
		var ret string
		return ret
	}
	return *o.PspHashedCardNumber
}

// GetPspHashedCardNumberOk returns a tuple with the PspHashedCardNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedPurchaseDto) GetPspHashedCardNumberOk() (*string, bool) {
	if o == nil || IsNil(o.PspHashedCardNumber) {
		return nil, false
	}
	return o.PspHashedCardNumber, true
}

// HasPspHashedCardNumber returns a boolean if a field has been set.
func (o *DetailedPurchaseDto) HasPspHashedCardNumber() bool {
	if o != nil && !IsNil(o.PspHashedCardNumber) {
		return true
	}

	return false
}

// SetPspHashedCardNumber gets a reference to the given string and assigns it to the PspHashedCardNumber field.
func (o *DetailedPurchaseDto) SetPspHashedCardNumber(v string) {
	o.PspHashedCardNumber = &v
}

// GetPspCardOwner returns the PspCardOwner field value if set, zero value otherwise.
func (o *DetailedPurchaseDto) GetPspCardOwner() string {
	if o == nil || IsNil(o.PspCardOwner) {
		var ret string
		return ret
	}
	return *o.PspCardOwner
}

// GetPspCardOwnerOk returns a tuple with the PspCardOwner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedPurchaseDto) GetPspCardOwnerOk() (*string, bool) {
	if o == nil || IsNil(o.PspCardOwner) {
		return nil, false
	}
	return o.PspCardOwner, true
}

// HasPspCardOwner returns a boolean if a field has been set.
func (o *DetailedPurchaseDto) HasPspCardOwner() bool {
	if o != nil && !IsNil(o.PspCardOwner) {
		return true
	}

	return false
}

// SetPspCardOwner gets a reference to the given string and assigns it to the PspCardOwner field.
func (o *DetailedPurchaseDto) SetPspCardOwner(v string) {
	o.PspCardOwner = &v
}

// GetPspFailReason returns the PspFailReason field value if set, zero value otherwise.
// Deprecated
func (o *DetailedPurchaseDto) GetPspFailReason() string {
	if o == nil || IsNil(o.PspFailReason) {
		var ret string
		return ret
	}
	return *o.PspFailReason
}

// GetPspFailReasonOk returns a tuple with the PspFailReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
// Deprecated
func (o *DetailedPurchaseDto) GetPspFailReasonOk() (*string, bool) {
	if o == nil || IsNil(o.PspFailReason) {
		return nil, false
	}
	return o.PspFailReason, true
}

// HasPspFailReason returns a boolean if a field has been set.
func (o *DetailedPurchaseDto) HasPspFailReason() bool {
	if o != nil && !IsNil(o.PspFailReason) {
		return true
	}

	return false
}

// SetPspFailReason gets a reference to the given string and assigns it to the PspFailReason field.
// Deprecated
func (o *DetailedPurchaseDto) SetPspFailReason(v string) {
	o.PspFailReason = &v
}

// GetPspFailReasons returns the PspFailReasons field value if set, zero value otherwise.
func (o *DetailedPurchaseDto) GetPspFailReasons() []PspFailReason {
	if o == nil || IsNil(o.PspFailReasons) {
		var ret []PspFailReason
		return ret
	}
	return o.PspFailReasons
}

// GetPspFailReasonsOk returns a tuple with the PspFailReasons field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedPurchaseDto) GetPspFailReasonsOk() ([]PspFailReason, bool) {
	if o == nil || IsNil(o.PspFailReasons) {
		return nil, false
	}
	return o.PspFailReasons, true
}

// HasPspFailReasons returns a boolean if a field has been set.
func (o *DetailedPurchaseDto) HasPspFailReasons() bool {
	if o != nil && !IsNil(o.PspFailReasons) {
		return true
	}

	return false
}

// SetPspFailReasons gets a reference to the given []PspFailReason and assigns it to the PspFailReasons field.
func (o *DetailedPurchaseDto) SetPspFailReasons(v []PspFailReason) {
	o.PspFailReasons = v
}

// GetInitPayerIp returns the InitPayerIp field value if set, zero value otherwise.
func (o *DetailedPurchaseDto) GetInitPayerIp() string {
	if o == nil || IsNil(o.InitPayerIp) {
		var ret string
		return ret
	}
	return *o.InitPayerIp
}

// GetInitPayerIpOk returns a tuple with the InitPayerIp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedPurchaseDto) GetInitPayerIpOk() (*string, bool) {
	if o == nil || IsNil(o.InitPayerIp) {
		return nil, false
	}
	return o.InitPayerIp, true
}

// HasInitPayerIp returns a boolean if a field has been set.
func (o *DetailedPurchaseDto) HasInitPayerIp() bool {
	if o != nil && !IsNil(o.InitPayerIp) {
		return true
	}

	return false
}

// SetInitPayerIp gets a reference to the given string and assigns it to the InitPayerIp field.
func (o *DetailedPurchaseDto) SetInitPayerIp(v string) {
	o.InitPayerIp = &v
}

// GetRedirectPayerIp returns the RedirectPayerIp field value if set, zero value otherwise.
func (o *DetailedPurchaseDto) GetRedirectPayerIp() string {
	if o == nil || IsNil(o.RedirectPayerIp) {
		var ret string
		return ret
	}
	return *o.RedirectPayerIp
}

// GetRedirectPayerIpOk returns a tuple with the RedirectPayerIp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedPurchaseDto) GetRedirectPayerIpOk() (*string, bool) {
	if o == nil || IsNil(o.RedirectPayerIp) {
		return nil, false
	}
	return o.RedirectPayerIp, true
}

// HasRedirectPayerIp returns a boolean if a field has been set.
func (o *DetailedPurchaseDto) HasRedirectPayerIp() bool {
	if o != nil && !IsNil(o.RedirectPayerIp) {
		return true
	}

	return false
}

// SetRedirectPayerIp gets a reference to the given string and assigns it to the RedirectPayerIp field.
func (o *DetailedPurchaseDto) SetRedirectPayerIp(v string) {
	o.RedirectPayerIp = &v
}

// GetPspSettled returns the PspSettled field value if set, zero value otherwise.
func (o *DetailedPurchaseDto) GetPspSettled() bool {
	if o == nil || IsNil(o.PspSettled) {
		var ret bool
		return ret
	}
	return *o.PspSettled
}

// GetPspSettledOk returns a tuple with the PspSettled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedPurchaseDto) GetPspSettledOk() (*bool, bool) {
	if o == nil || IsNil(o.PspSettled) {
		return nil, false
	}
	return o.PspSettled, true
}

// HasPspSettled returns a boolean if a field has been set.
func (o *DetailedPurchaseDto) HasPspSettled() bool {
	if o != nil && !IsNil(o.PspSettled) {
		return true
	}

	return false
}

// SetPspSettled gets a reference to the given bool and assigns it to the PspSettled field.
func (o *DetailedPurchaseDto) SetPspSettled(v bool) {
	o.PspSettled = &v
}

// GetRefunded returns the Refunded field value if set, zero value otherwise.
func (o *DetailedPurchaseDto) GetRefunded() bool {
	if o == nil || IsNil(o.Refunded) {
		var ret bool
		return ret
	}
	return *o.Refunded
}

// GetRefundedOk returns a tuple with the Refunded field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedPurchaseDto) GetRefundedOk() (*bool, bool) {
	if o == nil || IsNil(o.Refunded) {
		return nil, false
	}
	return o.Refunded, true
}

// HasRefunded returns a boolean if a field has been set.
func (o *DetailedPurchaseDto) HasRefunded() bool {
	if o != nil && !IsNil(o.Refunded) {
		return true
	}

	return false
}

// SetRefunded gets a reference to the given bool and assigns it to the Refunded field.
func (o *DetailedPurchaseDto) SetRefunded(v bool) {
	o.Refunded = &v
}

// GetRefundInquiryResult returns the RefundInquiryResult field value if set, zero value otherwise.
func (o *DetailedPurchaseDto) GetRefundInquiryResult() RefundInquiryResult {
	if o == nil || IsNil(o.RefundInquiryResult) {
		var ret RefundInquiryResult
		return ret
	}
	return *o.RefundInquiryResult
}

// GetRefundInquiryResultOk returns a tuple with the RefundInquiryResult field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedPurchaseDto) GetRefundInquiryResultOk() (*RefundInquiryResult, bool) {
	if o == nil || IsNil(o.RefundInquiryResult) {
		return nil, false
	}
	return o.RefundInquiryResult, true
}

// HasRefundInquiryResult returns a boolean if a field has been set.
func (o *DetailedPurchaseDto) HasRefundInquiryResult() bool {
	if o != nil && !IsNil(o.RefundInquiryResult) {
		return true
	}

	return false
}

// SetRefundInquiryResult gets a reference to the given RefundInquiryResult and assigns it to the RefundInquiryResult field.
func (o *DetailedPurchaseDto) SetRefundInquiryResult(v RefundInquiryResult) {
	o.RefundInquiryResult = &v
}

// GetRefundableAmount returns the RefundableAmount field value if set, zero value otherwise.
func (o *DetailedPurchaseDto) GetRefundableAmount() int64 {
	if o == nil || IsNil(o.RefundableAmount) {
		var ret int64
		return ret
	}
	return *o.RefundableAmount
}

// GetRefundableAmountOk returns a tuple with the RefundableAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedPurchaseDto) GetRefundableAmountOk() (*int64, bool) {
	if o == nil || IsNil(o.RefundableAmount) {
		return nil, false
	}
	return o.RefundableAmount, true
}

// HasRefundableAmount returns a boolean if a field has been set.
func (o *DetailedPurchaseDto) HasRefundableAmount() bool {
	if o != nil && !IsNil(o.RefundableAmount) {
		return true
	}

	return false
}

// SetRefundableAmount gets a reference to the given int64 and assigns it to the RefundableAmount field.
func (o *DetailedPurchaseDto) SetRefundableAmount(v int64) {
	o.RefundableAmount = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *DetailedPurchaseDto) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedPurchaseDto) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *DetailedPurchaseDto) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *DetailedPurchaseDto) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetBillingDate returns the BillingDate field value if set, zero value otherwise.
func (o *DetailedPurchaseDto) GetBillingDate() time.Time {
	if o == nil || IsNil(o.BillingDate) {
		var ret time.Time
		return ret
	}
	return *o.BillingDate
}

// GetBillingDateOk returns a tuple with the BillingDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedPurchaseDto) GetBillingDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.BillingDate) {
		return nil, false
	}
	return o.BillingDate, true
}

// HasBillingDate returns a boolean if a field has been set.
func (o *DetailedPurchaseDto) HasBillingDate() bool {
	if o != nil && !IsNil(o.BillingDate) {
		return true
	}

	return false
}

// SetBillingDate gets a reference to the given time.Time and assigns it to the BillingDate field.
func (o *DetailedPurchaseDto) SetBillingDate(v time.Time) {
	o.BillingDate = &v
}

// GetVerifiedAt returns the VerifiedAt field value if set, zero value otherwise.
func (o *DetailedPurchaseDto) GetVerifiedAt() time.Time {
	if o == nil || IsNil(o.VerifiedAt) {
		var ret time.Time
		return ret
	}
	return *o.VerifiedAt
}

// GetVerifiedAtOk returns a tuple with the VerifiedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedPurchaseDto) GetVerifiedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.VerifiedAt) {
		return nil, false
	}
	return o.VerifiedAt, true
}

// HasVerifiedAt returns a boolean if a field has been set.
func (o *DetailedPurchaseDto) HasVerifiedAt() bool {
	if o != nil && !IsNil(o.VerifiedAt) {
		return true
	}

	return false
}

// SetVerifiedAt gets a reference to the given time.Time and assigns it to the VerifiedAt field.
func (o *DetailedPurchaseDto) SetVerifiedAt(v time.Time) {
	o.VerifiedAt = &v
}

// GetPspSettledAt returns the PspSettledAt field value if set, zero value otherwise.
func (o *DetailedPurchaseDto) GetPspSettledAt() time.Time {
	if o == nil || IsNil(o.PspSettledAt) {
		var ret time.Time
		return ret
	}
	return *o.PspSettledAt
}

// GetPspSettledAtOk returns a tuple with the PspSettledAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedPurchaseDto) GetPspSettledAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.PspSettledAt) {
		return nil, false
	}
	return o.PspSettledAt, true
}

// HasPspSettledAt returns a boolean if a field has been set.
func (o *DetailedPurchaseDto) HasPspSettledAt() bool {
	if o != nil && !IsNil(o.PspSettledAt) {
		return true
	}

	return false
}

// SetPspSettledAt gets a reference to the given time.Time and assigns it to the PspSettledAt field.
func (o *DetailedPurchaseDto) SetPspSettledAt(v time.Time) {
	o.PspSettledAt = &v
}

// GetSettlementId returns the SettlementId field value if set, zero value otherwise.
func (o *DetailedPurchaseDto) GetSettlementId() int64 {
	if o == nil || IsNil(o.SettlementId) {
		var ret int64
		return ret
	}
	return *o.SettlementId
}

// GetSettlementIdOk returns a tuple with the SettlementId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedPurchaseDto) GetSettlementIdOk() (*int64, bool) {
	if o == nil || IsNil(o.SettlementId) {
		return nil, false
	}
	return o.SettlementId, true
}

// HasSettlementId returns a boolean if a field has been set.
func (o *DetailedPurchaseDto) HasSettlementId() bool {
	if o != nil && !IsNil(o.SettlementId) {
		return true
	}

	return false
}

// SetSettlementId gets a reference to the given int64 and assigns it to the SettlementId field.
func (o *DetailedPurchaseDto) SetSettlementId(v int64) {
	o.SettlementId = &v
}

// GetHasContradiction returns the HasContradiction field value if set, zero value otherwise.
func (o *DetailedPurchaseDto) GetHasContradiction() bool {
	if o == nil || IsNil(o.HasContradiction) {
		var ret bool
		return ret
	}
	return *o.HasContradiction
}

// GetHasContradictionOk returns a tuple with the HasContradiction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedPurchaseDto) GetHasContradictionOk() (*bool, bool) {
	if o == nil || IsNil(o.HasContradiction) {
		return nil, false
	}
	return o.HasContradiction, true
}

// HasHasContradiction returns a boolean if a field has been set.
func (o *DetailedPurchaseDto) HasHasContradiction() bool {
	if o != nil && !IsNil(o.HasContradiction) {
		return true
	}

	return false
}

// SetHasContradiction gets a reference to the given bool and assigns it to the HasContradiction field.
func (o *DetailedPurchaseDto) SetHasContradiction(v bool) {
	o.HasContradiction = &v
}

func (o DetailedPurchaseDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DetailedPurchaseDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PurchaseId) {
		toSerialize["purchaseId"] = o.PurchaseId
	}
	if !IsNil(o.PurchaseIdStr) {
		toSerialize["purchaseIdStr"] = o.PurchaseIdStr
	}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.Wage) {
		toSerialize["wage"] = o.Wage
	}
	if !IsNil(o.Fee) {
		toSerialize["fee"] = o.Fee
	}
	if !IsNil(o.FeePaymentType) {
		toSerialize["feePaymentType"] = o.FeePaymentType
	}
	if !IsNil(o.ShaparakFee) {
		toSerialize["shaparakFee"] = o.ShaparakFee
	}
	if !IsNil(o.ResellerCode) {
		toSerialize["resellerCode"] = o.ResellerCode
	}
	if !IsNil(o.AffiliateFee) {
		toSerialize["affiliateFee"] = o.AffiliateFee
	}
	if !IsNil(o.NetAmount) {
		toSerialize["netAmount"] = o.NetAmount
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.CallbackUrl) {
		toSerialize["callbackUrl"] = o.CallbackUrl
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.ClientReferenceNumber) {
		toSerialize["clientReferenceNumber"] = o.ClientReferenceNumber
	}
	if !IsNil(o.PspName) {
		toSerialize["pspName"] = o.PspName
	}
	if !IsNil(o.PspRrn) {
		toSerialize["pspRrn"] = o.PspRrn
	}
	if !IsNil(o.PspReferenceNumber) {
		toSerialize["pspReferenceNumber"] = o.PspReferenceNumber
	}
	if !IsNil(o.PspTraceNumber) {
		toSerialize["pspTraceNumber"] = o.PspTraceNumber
	}
	if !IsNil(o.ExpirationDate) {
		toSerialize["expirationDate"] = o.ExpirationDate
	}
	if !IsNil(o.UserIdentifier) {
		toSerialize["userIdentifier"] = o.UserIdentifier
	}
	if !IsNil(o.PayerMobileNumber) {
		toSerialize["payerMobileNumber"] = o.PayerMobileNumber
	}
	if !IsNil(o.PayerCardNumber) {
		toSerialize["payerCardNumber"] = o.PayerCardNumber
	}
	if !IsNil(o.PayerNationalCode) {
		toSerialize["payerNationalCode"] = o.PayerNationalCode
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.AdditionalData) {
		toSerialize["additionalData"] = o.AdditionalData
	}
	if !IsNil(o.PspMaskedCardNumber) {
		toSerialize["pspMaskedCardNumber"] = o.PspMaskedCardNumber
	}
	if !IsNil(o.PspHashedCardNumber) {
		toSerialize["pspHashedCardNumber"] = o.PspHashedCardNumber
	}
	if !IsNil(o.PspCardOwner) {
		toSerialize["pspCardOwner"] = o.PspCardOwner
	}
	if !IsNil(o.PspFailReason) {
		toSerialize["pspFailReason"] = o.PspFailReason
	}
	if !IsNil(o.PspFailReasons) {
		toSerialize["pspFailReasons"] = o.PspFailReasons
	}
	if !IsNil(o.InitPayerIp) {
		toSerialize["initPayerIp"] = o.InitPayerIp
	}
	if !IsNil(o.RedirectPayerIp) {
		toSerialize["redirectPayerIp"] = o.RedirectPayerIp
	}
	if !IsNil(o.PspSettled) {
		toSerialize["pspSettled"] = o.PspSettled
	}
	if !IsNil(o.Refunded) {
		toSerialize["refunded"] = o.Refunded
	}
	if !IsNil(o.RefundInquiryResult) {
		toSerialize["refundInquiryResult"] = o.RefundInquiryResult
	}
	if !IsNil(o.RefundableAmount) {
		toSerialize["refundableAmount"] = o.RefundableAmount
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.BillingDate) {
		toSerialize["billingDate"] = o.BillingDate
	}
	if !IsNil(o.VerifiedAt) {
		toSerialize["verifiedAt"] = o.VerifiedAt
	}
	if !IsNil(o.PspSettledAt) {
		toSerialize["pspSettledAt"] = o.PspSettledAt
	}
	if !IsNil(o.SettlementId) {
		toSerialize["settlementId"] = o.SettlementId
	}
	if !IsNil(o.HasContradiction) {
		toSerialize["hasContradiction"] = o.HasContradiction
	}
	return toSerialize, nil
}

type NullableDetailedPurchaseDto struct {
	value *DetailedPurchaseDto
	isSet bool
}

func (v NullableDetailedPurchaseDto) Get() *DetailedPurchaseDto {
	return v.value
}

func (v *NullableDetailedPurchaseDto) Set(val *DetailedPurchaseDto) {
	v.value = val
	v.isSet = true
}

func (v NullableDetailedPurchaseDto) IsSet() bool {
	return v.isSet
}

func (v *NullableDetailedPurchaseDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDetailedPurchaseDto(val *DetailedPurchaseDto) *NullableDetailedPurchaseDto {
	return &NullableDetailedPurchaseDto{value: val, isSet: true}
}

func (v NullableDetailedPurchaseDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDetailedPurchaseDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


