/*
PPG: Proxy Payment Gateway

PPG is the Proxy Payment Gateway of Jibit corporation. It lets the users of 3rd-party clients (merchants, banks, organizations, ...) to purchase goodies from them using PPG as a transparent payment gateway. In back-end the user will be redirected to a PSP payment gateway (for example Saman) to pay the price of the purchase.  Using APIs of this application a client can create and initiate the purchase orders and can track the state of these purchases.  Using *Swagger Editor* you could directly call the PPG APIs and also could auto-generate a client for PPG APIs in your preferred programming language.  The base URL of PPG is: `https://napi.jibit.ir/ppg`  Full documentation is available on: https://napi.jibit.ir/ppg/v3/static/docs/index.html

API version: 3.2.48
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package jibit-ppg

import (
	"encoding/json"
	"time"
)

// checks if the DetailedPurchaseHistoryDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DetailedPurchaseHistoryDto{}

// DetailedPurchaseHistoryDto Encapsulates a detailed view of a purchase history.
type DetailedPurchaseHistoryDto struct {
	// Represents the purchase identifier.
	PurchaseId *int64 `json:"purchaseId,omitempty"`
	// Represents the client reference number.  A string value from client side to trace purchase in our system. This value is unique between client purchases.
	ClientRefNum *string `json:"clientRefNum,omitempty"`
	// Represents the simplified version of purchase new state.  <p>  The following states indicate the purchase had a contradiction and now is resolved.  <p>  * `MANUALLY_SUCCESS`: The purchase has been successful manually.  * `REVERSED`: The purchase has been reversed manually.  **Note: ** `REVERSED` does not indicate a contradiction if the client reverts a purchase.
	NewState *string `json:"newState,omitempty"`
	// Represents the creation time of this purchase history, which indicates when purchase status got changed.  Example: 2024-10-20T13:25:30.946Z
	CreatedAt *time.Time `json:"createdAt,omitempty"`
}

// NewDetailedPurchaseHistoryDto instantiates a new DetailedPurchaseHistoryDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDetailedPurchaseHistoryDto() *DetailedPurchaseHistoryDto {
	this := DetailedPurchaseHistoryDto{}
	return &this
}

// NewDetailedPurchaseHistoryDtoWithDefaults instantiates a new DetailedPurchaseHistoryDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDetailedPurchaseHistoryDtoWithDefaults() *DetailedPurchaseHistoryDto {
	this := DetailedPurchaseHistoryDto{}
	return &this
}

// GetPurchaseId returns the PurchaseId field value if set, zero value otherwise.
func (o *DetailedPurchaseHistoryDto) GetPurchaseId() int64 {
	if o == nil || IsNil(o.PurchaseId) {
		var ret int64
		return ret
	}
	return *o.PurchaseId
}

// GetPurchaseIdOk returns a tuple with the PurchaseId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedPurchaseHistoryDto) GetPurchaseIdOk() (*int64, bool) {
	if o == nil || IsNil(o.PurchaseId) {
		return nil, false
	}
	return o.PurchaseId, true
}

// HasPurchaseId returns a boolean if a field has been set.
func (o *DetailedPurchaseHistoryDto) HasPurchaseId() bool {
	if o != nil && !IsNil(o.PurchaseId) {
		return true
	}

	return false
}

// SetPurchaseId gets a reference to the given int64 and assigns it to the PurchaseId field.
func (o *DetailedPurchaseHistoryDto) SetPurchaseId(v int64) {
	o.PurchaseId = &v
}

// GetClientRefNum returns the ClientRefNum field value if set, zero value otherwise.
func (o *DetailedPurchaseHistoryDto) GetClientRefNum() string {
	if o == nil || IsNil(o.ClientRefNum) {
		var ret string
		return ret
	}
	return *o.ClientRefNum
}

// GetClientRefNumOk returns a tuple with the ClientRefNum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedPurchaseHistoryDto) GetClientRefNumOk() (*string, bool) {
	if o == nil || IsNil(o.ClientRefNum) {
		return nil, false
	}
	return o.ClientRefNum, true
}

// HasClientRefNum returns a boolean if a field has been set.
func (o *DetailedPurchaseHistoryDto) HasClientRefNum() bool {
	if o != nil && !IsNil(o.ClientRefNum) {
		return true
	}

	return false
}

// SetClientRefNum gets a reference to the given string and assigns it to the ClientRefNum field.
func (o *DetailedPurchaseHistoryDto) SetClientRefNum(v string) {
	o.ClientRefNum = &v
}

// GetNewState returns the NewState field value if set, zero value otherwise.
func (o *DetailedPurchaseHistoryDto) GetNewState() string {
	if o == nil || IsNil(o.NewState) {
		var ret string
		return ret
	}
	return *o.NewState
}

// GetNewStateOk returns a tuple with the NewState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedPurchaseHistoryDto) GetNewStateOk() (*string, bool) {
	if o == nil || IsNil(o.NewState) {
		return nil, false
	}
	return o.NewState, true
}

// HasNewState returns a boolean if a field has been set.
func (o *DetailedPurchaseHistoryDto) HasNewState() bool {
	if o != nil && !IsNil(o.NewState) {
		return true
	}

	return false
}

// SetNewState gets a reference to the given string and assigns it to the NewState field.
func (o *DetailedPurchaseHistoryDto) SetNewState(v string) {
	o.NewState = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *DetailedPurchaseHistoryDto) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailedPurchaseHistoryDto) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *DetailedPurchaseHistoryDto) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *DetailedPurchaseHistoryDto) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

func (o DetailedPurchaseHistoryDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DetailedPurchaseHistoryDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PurchaseId) {
		toSerialize["purchaseId"] = o.PurchaseId
	}
	if !IsNil(o.ClientRefNum) {
		toSerialize["clientRefNum"] = o.ClientRefNum
	}
	if !IsNil(o.NewState) {
		toSerialize["newState"] = o.NewState
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	return toSerialize, nil
}

type NullableDetailedPurchaseHistoryDto struct {
	value *DetailedPurchaseHistoryDto
	isSet bool
}

func (v NullableDetailedPurchaseHistoryDto) Get() *DetailedPurchaseHistoryDto {
	return v.value
}

func (v *NullableDetailedPurchaseHistoryDto) Set(val *DetailedPurchaseHistoryDto) {
	v.value = val
	v.isSet = true
}

func (v NullableDetailedPurchaseHistoryDto) IsSet() bool {
	return v.isSet
}

func (v *NullableDetailedPurchaseHistoryDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDetailedPurchaseHistoryDto(val *DetailedPurchaseHistoryDto) *NullableDetailedPurchaseHistoryDto {
	return &NullableDetailedPurchaseHistoryDto{value: val, isSet: true}
}

func (v NullableDetailedPurchaseHistoryDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDetailedPurchaseHistoryDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


